### ISSUE TITLE
Onboard & Offboard: Internship Project

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#123]
### Overview
We need to have a checklist of items to do when a product manager onboard and offboards so that the process can be consistent and fast.

### Action Items
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

```
#### Onboard
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] [REPLACE with name of primary vault]
       - [ ] [REPLACE with name of secondary vault]
       - [ ] Zoom vault
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite
```
```
#### Offboard
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] [REPLACE with name of primary vault]
       - [ ] [REPLACE with name of secondary vault]
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
```

### Resources/Instructions
- 1password.com
- [REPLACE with Google Drive Link]
- [REPLACE with GitHub Team URL]
   - [base (read)]
   - [write]
   - [maintain]
   - [triage]
   - [admin]
   - [other]

**Comment by priyatalwar** [comment]
#### Onboard

- [ ] Grace
- [ ] Bilkish

- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Zoom vault
- [ ] Add to team page
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty I added the Zoom Setup set to the template on this issue but you will need to Edit the Org Template and Changelog...

**Comment by gracieama** [comment]
#### Onboard

#### New PMs
- [ ] Annie

- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns```
- [ ] Add to Google calendar invites
   - [ ] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
Bilkish
#### Offboard
- [x] Remove from Google calendar invite
   - [x] Monday PM meeting
   - [x] Tuesday BA meeting
   - [x] Tuesday UX Research meeting
   - [x] Wednesday PM meeting (ad-hoc)
   - [x] Thursday All-team meeting
 - [x] 1password setup
    - [x] remove from team vaults
       - [x] Internship program
       - [x] Internship - UI/UX
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] remove from write team
     - [x] demote to member on base team
- [x] Figma
  - [x] remove from team
- [x] Help them delete the desktop shortcut to email address if they made one
- [x] Remove from email address(s)
   - [x] internship@hackforla.org
   - [x] internship-ux@hackforla.org
- ~Remove from Social Media Accounts with role assignment~
   - ~Facebook~ there is no facebook page
- [ ] WIKI
  - [ ] move to new place on team page

**Comment by epierotti3** [comment]
Seena
#### Offboard
- [ ] Remove from Google calendar invite
   - [] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship - UI/UX
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] remove from write team
     - [ ] demote to member on base team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- ~Remove from Social Media Accounts with role assignment~
   - ~Facebook~ there is no facebook page
- [ ] WIKI
  - [ ] move to new place on team page

**Comment by epierotti3** [comment]
Grace
#### Offboard
- [x] Remove from Google calendar invite
   - [x] Monday PM meeting
   - [x] Tuesday BA meeting
   - [x] Tuesday UX Research meeting
   - [x] Wednesday PM meeting (ad-hoc)
   - [x] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship - UI/UX
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] remove from write team
     - [x] demote to member on base team
- [x] Figma
  - [x] remove from team
- [x] Help them delete the desktop shortcut to email address if they made one
- [x] Remove from email address(s)
   - [x] internship@hackforla.org
   - [x] internship-ux@hackforla.org
- ~Remove from Social Media Accounts with role assignment~
   - ~Facebook~ there is no facebook page
- [x] WIKI
  - [x] move to new place on team page

**Comment by epierotti3** [comment]
@ExperimentsInHonesty Hi Bonnie, when you have a chance can you complete these two off-boardings for Seena and Grace (above) by removing them from 1password? Thanks

**Comment by epierotti3** [comment]
#### Offboard Elizabeth
- [ ] Remove from Google calendar invite
   - [ ] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Wedneday UX lead/PM meeting
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] WIKI
  - [ ] move to new place on team page

**Comment by ExperimentsInHonesty** [comment]
#### Onboard Sharon Gupta 2022-09-26
- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns```
 - [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Add to Google calendar invites
   - [ ] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101 and add them to role call and accountability check 
     - [ ] Assign them to the issue #49 and add them to role call and accountability check 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
Please copy the template below here to a new issue
```
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
```

**Comment by ExperimentsInHonesty** [comment]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
Copy this text to a comment after you are done with the issue
```
some text here
``

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ExperimentsInHonesty** [comment]
#### Onboard
- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns```
 - [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Add to Google calendar invites
   - [ ] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101 and add them to role call and accountability check 
     - [ ] Assign them to the issue #49 and add them to role call and accountability check 
     - [ ] Assign them to the issue #315 and add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by priyatalwar** [comment]
#### Offboard Sharon Gupta - Product
- [ ] Remove from Google calendar invite
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Wedneday UX lead/PM meeting
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101,  remove them from role call and accountability check 
     - [ ] Un Assign them to the issue #49,  remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] WIKI
  - [ ] move to new place on team page

**Comment by cbutcher318** [comment]
#### Onboard
- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns```
 - [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Add to Google calendar invites
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101 and add them to role call and accountability check 
     - [ ] Assign them to the issue #49 and add them to role call and accountability check 
     - [ ] Assign them to the issue #315 and add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Confirm that product member has access to Zoom Meeting Setup spreadsheet (if they are part of the product community of practice they will have access)
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by cbutcher318** [comment]
#### Onboard Kathleen Francois
2023-02-01
- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns```
 - [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Add to Google calendar invites
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101 and add them to role call and accountability check 
     - [ ] Assign them to the issue #49 and add them to role call and accountability check 
     - [ ] Assign them to the issue #315 and add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Confirm that product member has access to Zoom Meeting Setup spreadsheet (if they are part of the product community of practice they will have access)
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by cbutcher318** [comment]
#### Offboard Dionne
- [ ] Remove from Google calendar invite
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Wednesday UX lead/PM meeting
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101,  remove them from role call and accountability check 
     - [ ] Un Assign them to the issue #49,  remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)

**Comment by cbutcher318** [comment]
Issue removing a guest from all future meetings

**Comment by priyatalwar** [comment]
#### Offboard Kathleen Francois
- [ ] confirm that volunteer is not working on any guides in community of practice (if person does not respond to communication you can assume they are not active in the CoP)
- [ ] Remove from Google calendar invite
   - You need to log into the internship@gmail.com account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the internship project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Wedneday UX lead/PM meeting
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] Internship (ie., project)  
      - [ ] demote to viewer
   - [ ] Product Management
      - [ ] demote to viewer
         - ask admin channel for support if you don't have access
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101,  remove them from role call and accountability check 
     - [ ] Un Assign them to the issue #49,  remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)

**Comment by ExperimentsInHonesty** [comment]
Offboard Christian 2023-04-27

#### Offboard
- [ ] confirm that volunteer is not working on any guides in community of practice (if person does not respond to communication you can assume they are not active in the CoP)
- [ ] Remove from Google calendar invite
   - You need to log into the internship@gmail.com account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the internship project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Wedneday UX lead/PM meeting
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Remove access from VRMS
   - ask admin if you don't have access
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] Internship (ie., project)  
      - [ ] demote to viewer
   - [ ] Product Management
      - [ ] demote to viewer
         - ask admin channel for support if you don't have access
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101,  remove them from role call and accountability check 
     - [ ] Un Assign them to the issue #49,  remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)

**Comment by ExperimentsInHonesty** [comment]
Must log into internship@hackforla.org to remove from figma

**Comment by joshfishman** [comment]
#### Onboard
- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns```
 - [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Add to Google calendar invites
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101 and add them to role call and accountability check 
     - [ ] Assign them to the issue #49 and add them to role call and accountability check 
     - [ ] Assign them to the issue #315 and add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Confirm that product member has access to Zoom Meeting Setup spreadsheet (if they are part of the product community of practice they will have access)
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
#### Onboard 2024-02-05 KC
- [ ] Slack channel membership
  - [ ] ```#internship```
  - [ ] ```#interns```
 - [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Add to Google calendar invites
   - [ ] Monday PM meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub
     - [ ] Add to write team
        - [ ] Change membership to maintainer
     - [ ] Add to read team
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github  
     - [ ] Assign them to the issue #101 and add them to role call and accountability check 
     - [ ] Assign them to the issue #49 and add them to role call and accountability check 
     - [ ] Assign them to the issue #315 and add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Confirm that product member has access to Zoom Meeting Setup spreadsheet (if they are part of the product community of practice they will have access)
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Add to email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by KC-skc** [comment]
Unable to add Sonalika to gmail because asking for two step verification on iPhone.

**Comment by ExperimentsInHonesty** [comment]
@KC-skc 

> Unable to add Sonalika to gmail because asking for two step verification on iPhone.

You just select the Try another way option at the bottom

> I also do not have access to Zoom Meeting Access Spreadsheet.

Do you have access to [product-management google drive](https://drive.google.com/drive/folders/1_kxLe5tX0jCDXXeD7UaikiLfjUvNB7eD)?  If not, ask me to add you at the next team meeting.

**Comment by KC-skc** [comment]
#### Offboard Annie Truong
- [ ] confirm that volunteer is not working on any guides in community of practice (if person does not respond to communication you can assume they are not active in the CoP)
- [ ] Remove from Google calendar invite
   - You need to log into the internship@gmail.com account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the internship project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Monday PM meeting
   - [ ] Monday PM/Research Lead (templates)
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting
   - [ ] Wedneday UX lead/PM meeting
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Remove access from VRMS
   - ask admin if you don't have access
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] Internship (ie., project)  
      - [ ] demote to viewer
   - [ ] Product Management
      - [ ] demote to viewer
         - ask admin channel for support if you don't have access
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101,  remove them from role call and accountability check 
     - [ ] Un Assign them to the issue #49,  remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)

**Comment by KC-skc** [comment]
VRMS created for self. Will require BW approval.

**Comment by KC-skc** [comment]
To Do Items for Admin/BW to update Offboarding.

Remove from 1password 
- [ ] Seena

**Comment by ExperimentsInHonesty** [comment]
@KC-skc I have confirmed removal of the people above

**Comment by priyatalwar** [comment]
#### Offboard Sonalika
- [ ] confirm that volunteer is not working on any guides in community of practice (if person does not respond to communication you can assume they are not active in the CoP)
- [ ] Remove from Google calendar invite
   - You need to log into the internship@gmail.com account in order to remove the person from all future events
   - Choose to remove from "This and all following events"
   - Send the following cancelation message:
      - ``You have been removed from this event because you are listed as an inactive member of the internship project team. If you have been removed by mistake, please reach out to a product manager.``  
   - [ ] Monday PM meeting
   - [ ] Monday PM/Research Lead (templates)
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting
   - [ ] Wedneday UX lead/PM meeting
   - [ ] Thursday All-team meeting
 - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Internship UI/UX
       - [ ] Zoom vault
- [ ] Remove access from VRMS
   - ask admin if you don't have access
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] Internship (ie., project)  
      - [ ] demote to viewer
   - [ ] Product Management
      - [ ] demote to viewer
         - ask admin channel for support if you don't have access
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101,  remove them from role call and accountability check 
     - [ ] Un Assign them to the issue #49,  remove them from role call and accountability check 
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team (you must be logged in with project email account)
- [ ] Help them delete the desktop shortcut to email address if they made one
- [ ] Remove from email address(s)
   - [ ] internship@hackforla.org
   - [ ] internship-ux@hackforla.org
- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Update team page on WIKI
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)

**Comment by priyatalwar** [comment]
Removed from all except Figma since I don't have admin access.

**Comment by ExperimentsInHonesty** [comment]
@priyatalwar 

>Removed from all except Figma, Zoom, VRMS and PM CoP since I don't have admin access.
 
- Remove her from figma by logging into 1password vault.  Remove from all other resources by adding a comment (see product managmenet agenda for template) to the product management agenda issue https://github.com/hackforla/product-management/issues/386
