### ISSUE TITLE
Onboard and Offboard : UX

### ISSUE THREAD

**Issue by aditipaulphd** [hackforla/internship#124]
### Overview
We need to have a checklist of items to do when a UXer onboard and offboards so that the process can be consistent and fast.

### Action Items
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

```
#### Onboard
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Zoom vault
- [ ] Add to team page on Wiki
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite
```
```
#### Offboard
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship program
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] WIKI
  - [ ] move to new place on team page
```

### Resources/Instructions
- [1password.com](https://1password.com/)
- [Google Drive Link](https://drive.google.com/drive/folders/1z3I2SLQzYWBHIypNZO-sTdSO0A8c5pvt?usp=sharing)
- Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
- [GitHub Team URL](https://github.com/hackforla/internship)
   - [base (read)](https://github.com/orgs/hackforla/teams/internship/members)
   - [write](https://github.com/orgs/hackforla/teams/internship-write/members)
   - [maintain](https://github.com/orgs/hackforla/teams/internship-maintain/members)
   - [triage] - does not exist
   - [admin](https://github.com/orgs/hackforla/teams/internship-admin)
   - [other] - does not exist
- WIKI team page: https://github.com/hackforla/internship/wiki/The-Team
- Figma [Internship Figma](https://www.figma.com/files/team/1022346700206546118/Internship?fuid=1022346694215618345)

**Comment by aditipaulphd** [comment]
#### Onboard Maria 02/15/2022
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Zoom vault
- [ ] Add to team page on Wiki
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
#### Onboard Aditi  (added retroactively) 
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
apaulmsu@gmail.com

sort out the 1password vaults for ui/ux

**Comment by ExperimentsInHonesty** [comment]
#### Onboard Christine El Ouardani 2022-05-18
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
#### Onboard - not a lead
- [ ] Google Drive
   - [ ] Add to drive as Manager -1
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
  - [ ] Check for 2FA
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
     - [ ] Confirm that their name is on their Github 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org - not yet
- [ ] Train how to 
   - [ ] login to team email account - not yet
   - [ ] use zoom spreadsheet, vault and accounts - not yet
   - [ ] calendar invite

**Comment by epierotti3** [comment]
@ExperimentsInHonesty Hi Bonnie, please add Koyel Ranu (koyelranu@gmail.com) to one password when you have a moment. Thanks!

**Comment by epierotti3** [comment]
#### Offboard Snigdha (UX not lead)
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship - ux program
       - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] WIKI
  - [ ] move to new place on team page
- [ ] Remove from email address(s)
   - [ ] internship-ux@hackforla.org

**Comment by christine-el** [comment]
> #### Onboard - Koyel Ranu (Not UX Lead, based on template above)
> * [x]  Google Drive
>   
>   * [x]  Add to drive as Content Manager
> * [x]  Roster
>   
>   * [x]  Send link
>   * [x]  Team member adds themselves
>   * [x]  Check for Public
>   * [x]  Check for 2FA
> * [ ]  GitHub
>   
>   * [x]  Add to team write team
>   * [ ]  Add to read vault
>   * [x]  Confirm that their name is on their Github
> * [x]  Figma
>   
>   * [x]  invite
>   * [x]  acceptance
> * [ ]  1password
>   
>   * [ ]  invitation
>   * [ ]  acceptance
>   * [ ]  add to vaults
>     
>     * [ ]  Internship- ux program
>     * [ ]  Zoom vault
> * [x]  Grant access to Zoom Meeting Setup spreadsheet
> * [x]  Add to team page on Wiki
> * [ ]  Add to email address(s)
>   
>   * [ ]  [internship-ux@hackforla.org](mailto:internship-ux@hackforla.org) - not yet
> * [ ]  Train how to
>   
>   * [ ]  login to team email account - not yet
>   * [ ]  use zoom spreadsheet, vault and accounts - not yet
>   * [ ]  calendar invite

@epierotti3 @ExperimentsInHonesty Koyel has left HFLA, so should not be onboarded to this project.

**Comment by christine-el** [comment]
#### Onboard - Sara Brady (UX Co-Lead)  8-17-22
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by epierotti3** [comment]
#### Offboard Koyel Ranu (UX not lead) from HfLA
  - [] 1password setup
    - [] remove from team vaults
       - [x] Internship - ux program
       - [x] Zoom vault
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] demote member to read only team and remove from write team
- [x] Figma
  - [x] remove from team
- [x] WIKI
  - [x] move to new place on team page
- [x] Remove from email address(s)
   - [x] internship-ux@hackforla.org

**Comment by epierotti3** [comment]
#### Onboard - Natalia V (Not UX Lead, based on template above)
- [x] Google Drive
   - [x] Add to drive as Content Manager
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public
  - [x] Check for 2FA
- [ ] GitHub
     - [x] Add to team write team
     - [ ] Add to read vault
     - [x] Confirm that their name is on their Github 
- [x] Figma
  - [x] invite
  - [x] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [x] Grant access to Zoom Meeting Setup spreadsheet
- [x] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org - not yet
- [ ] Train how to 
   - [ ] login to team email account - not yet
   - [ ] use zoom spreadsheet, vault and accounts - not yet
   - [ ] calendar invite

**Comment by bradyse** [comment]
#### Onboard - Yingjie Ou (UX Research Lead) - 2022-11-13
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
     - [ ] Assign them to the issue #62, add them to role call and accountability check  
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Add to team page on Wiki
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by cbutcher318** [comment]
#### Onboard
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
     - [ ] Assign them to the issue #62, add them to role call and accountability check  
     - [ ] Assign them to the issue #315, add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki) 
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by pandanista** [comment]
#### Onboard - Sandy Oh - 2023-02-02
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
     - [ ] Assign them to the issue #62, add them to role call and accountability check  
     - [ ] Assign them to the issue #315, add them to role call and accountability check
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki) 
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
Notes
Design System Figma Link

Each color or component should be linked to its style and the action item for doing that is called "organized component" and lives in each component issue .  See epic #397 for links to all the component issues

We have not yet implemented the new feature variables or dev mode

Handoff documented process

Bryanna 

Current

**Comment by RobinElayn** [comment]
What is the ultimate goal of the TWE project, and how does the website fit into achieving that goal?
Understanding the project's larger context will help inform design decisions and ensure that the website aligns with the project's overall mission
Ex: The ultimate goal of the TWE project may be to provide high school students with valuable work experience that prepares them for future careers. The website may serve as a tool to connect students with potential internship opportunities and provide them with resources to prepare for and succeed in those internships.
What are the key user needs that the website should address, and how will those needs vary across different user groups?
Identifying user needs and personas will inform the design and content of the website, ensuring that it is user-friendly and meets the needs of its target audience.
Ex: Students may need a user-friendly application process and resources to prepare for internships, while potential employers may need information on how to participate in the program and connect with students.
What are the technical requirements for the website? Will it require any specific integrations or functionalities (e.g., payment processing, scheduling software, etc.)?
Understanding the technical requirements will help ensure that the website is designed to function effectively and that any necessary integrations are included.
Ex: The website may require a secure application portal for students to submit applications and a content management system to easily update and manage website content.
What is the project's branding strategy, and how should that be reflected in the website's design and messaging?
Understanding the branding strategy will ensure that the website's design and messaging align with the project's overall image and messaging.
Ex: The project's branding strategy may be focused on promoting diversity and inclusivity, and the website's design and messaging should reflect those values through the use of diverse imagery and inclusive language.
What are the key success metrics for the website? How will success be measured and evaluated?
Understanding the project's success metrics will ensure that the website is designed to meet those metrics and that it can be effectively evaluated to track progress.
Ex: Key success metrics for the website may include the number of student applications received, the number of internships secured by students, and user satisfaction ratings. These metrics can be measured through website analytics and user surveys.
What are the potential barriers to website adoption and success, and how can those be addressed in the website's design and messaging?
Understanding potential barriers to adoption (e.g., lack of awareness, difficulty navigating the website, etc.) will ensure that the website is designed to address those barriers and maximize adoption and success.
Ex: Potential barriers to adoption may include a lack of awareness about the TWE project among high school students and potential employers. These barriers can be addressed through clear messaging about the benefits of participating in the program and targeted outreach efforts to reach those user groups.
How will the website be updated and maintained over time, and what resources will be needed to ensure that it remains up-to-date and effective?
Understanding the ongoing maintenance needs of the website will ensure that it remains effective and up-to-date over time.
Ex: The website may require ongoing updates to internship listings and resources, as well as regular maintenance to ensure that it remains secure and functional. A content management system and dedicated website administrator may be needed to ensure that the website is kept up-to-date and effective over time.

**Comment by pandanista** [comment]
#### Offboard - Sara Brady - 2024-01-23
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Internship - ux program
       - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Internship shared Google Drive
   - [ ] demote to viewer
- [ ] Internship - PII Google Drive
   - [ ] Remove access to the drive
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101, remove them from role call and accountability check  
     - [ ] Un Assign them to the issue #62, remove them from role call and accountability check   
     - [ ] Un-assign them to the issue #315, remove them from the roll call and accountability check
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team
- [ ] Update team page on wiki
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Remove from email address(s)
   - [ ] internship-ux@hackforla.org

**Comment by pandanista** [comment]
#### Onboard Jinran - UX Research Co-Lead
- [ ] Internship shared Google Drive
   - [ ] Add to drive as Manager
- [ ] Internship - PII Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
     - [ ] Assign them to the issue #62, add them to role call and accountability check  
     - [ ] Assign them to the issue #315, add them to role call and accountability check
- [ ] Add to Google calendar invites
   - [ ] Tuesday Design System Meeting (if necessary)
      - [ ] not needed 
   - [ ] Tuesday BA meeting (if necessary)
      - [ ] not needed
   - [ ] Tuesday UX Research meeting (if necessary)
      - [ ] not needed
   - [ ] Thursday All-team meeting
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki) 
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by ExperimentsInHonesty** [comment]
#### Onboard Erin Ryan
- [ ] Internship shared Google Drive
   - [ ] Add to drive as Manager
- [ ] Internship - PII Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
     - [ ] Confirm that their name is on their Github 
     - [ ] Assign them to the issue #101, add them to role call and accountability check 
     - [ ] Assign them to the issue #62, add them to role call and accountability check  
     - [ ] Assign them to the issue #315, add them to role call and accountability check
- [ ] Add to Google calendar invites
   - [ ] Tuesday Design System Meeting (if necessary)
      - [ ] not needed 
   - [ ] Tuesday BA meeting (if necessary)
      - [ ] not needed
   - [ ] Tuesday UX Research meeting (if necessary)
      - [ ] not needed
   - [ ] Thursday All-team meeting
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Internship- ux program
       - [ ] Zoom vault
- [ ] Grant access to Zoom Meeting Setup spreadsheet
- [ ] Update team page on Wiki
   - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki) 
- [ ] Add to email address(s)
   - [ ] internship-ux@hackforla.org
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by pandanista** [comment]
#### Offboard Jinyan - UX Research Co-Lead
- [ ] Remove from Google calendar invite
   - [ ] Monday PM meeting
   - [ ] Tuesday BA meeting
   - [ ] Tuesday UX Research meeting
   - [ ] Wednesday PM meeting (ad-hoc)
   - [ ] Thursday All-team meeting
- [ ] 1password setup
   - [ ] remove from team vaults
   - [ ] Internship - ux program
   - [ ] Zoom vault
- [ ] Revoke access from Zoom Meeting Setup spreadsheet
- [ ] Internship shared Google Drive
   - [ ] demote to viewer
- [ ] Internship - PII Google Drive
   - [ ] Remove access to the drive
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
     - [ ] Un Assign them to the issue #101, remove them from role call and accountability check  
     - [ ] Un Assign them to the issue #62, remove them from role call and accountability check   
     - [ ] Un-assign them to the issue #315, remove them from the roll call and accountability check
     - [ ] Check their Assignment status on the Issue tab, to make sure they are no longer assigned to any issues
- [ ] Figma
  - [ ] remove from team
- [ ] Update team page on wiki
  - [How to activate-inactivate team members from roster and wiki](https://github.com/hackforla/internship/wiki/How-to-activate-inactivate-team-members-from-roster-and-wiki)
- [ ] Remove from email address(s)
   - [ ] internship-ux@hackforla.org
