### ISSUE TITLE
Create framework for design system in Figma

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#126]
### Overview
We need a design system framework so as we make changes to components we have a place to store our decisions.

### Action Items
- [x] Review the Design Systems Guidance Draft page in figma and make a list of the elements that we will need.
- [x] Review with the team to determine priority
- [x] Meet with Design Systems Team as soon as they have guidance for us to use.
- [x] In the meantime, start creating our Design System by copying the parts of theirs that we are ready to work on.
- [ ] Define the sections needed to create a compressive DS
   - [ ] Create issues with product

### Resources/Instructions
[Design System page in Figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A11)
[Hack for la webstite figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)

**Comment by ExperimentsInHonesty** [comment]
Rabia Shaikh:
> Hi Jeanette,
> No worries...I hope your interviews went well.
> We have a new designer on our team...Cherilyn...who has been given the OK by Bonnie
> to be on the Design Systems project as well...she needs to be onboarded to your team as 
> a designer...thereby giving her access to the repo and invites to the meetings...I believe she 
> had reached out on the channel as well...her slack id is Cherilyn...

Jeanette Renema:
> Aaaah, now I understand. We are in need of a designer indeed. Maybe it will be best to onboard 
> her at the end of this week, maybe on Friday?! Then we can also point her to our ticket 
> onboarding system. In the meantime, you can refer her to this so that she is aware of 
> the meeting timings, etc: 
> https://github.com/hackforla/design-systems/wiki/Getting-Started
> This wiki page will set her up with regards to the onboarding procedures.


Bonnie followed up with this message in the design team's slack channel 2022-02-24 at 9:19 am

> Yasaman Roostaeian Jeanette Renema I have sent a team member Cherilyn from the Internship project to be the first person that tests the guidance that your team is creating. She will test it on her project (internship).
> 
> Just for extra clarification: She is NOT the Design Team's new designer.

**Comment by seetho-c** [comment]
Color System is in progress - @Susanz7 and I made updates for the primary, neutral, secondary (functional and accent) and text colors. 

We used Hack for LA and CivicTech as a reference to define each of the color shades and color usage.

Below is the screenshot from the Internship Figma file
(Color System suggestions with Airtable as a reference for color usage)
![Screenshot (14)](https://user-images.githubusercontent.com/29762834/162099709-391bae77-6031-42d9-b153-18956b46c589.png)

**Comment by ale22arevalo** [comment]
Update 7/7: Looked over Hack for LA's design system, started working on color system for our design system, reached out to Design Systems to team to attend their next weekly meeting to get a better understanding of their design process and how we can apply it to our own system.

**Comment by ale22arevalo** [comment]
Update 7/12: Met with Design Systems team. They provided me with several resources to build our own design system. 

- https://docs.google.com/document/d/14BZYFEa5s5FESeASNorEDLH6zEW0LTYcpD1NVyE66iM/edit
- https://www.figma.com/community/file/928108847914589057
- https://www.smashingmagazine.com/provide/eBooks/design-systems.pdf

I decided to start with the color palette. I input all over primary colors into Adobe Color (a tool to check whether your colors are accessible to color blind folks), I will share the findings of this in our next meeting (you can see screenshots in our Design System Figma file).

**Comment by ExperimentsInHonesty** [comment]
Resource from another project

### Accessibility standards
Title III of the Americans with Disabilities Act (ADA) requires that all websites be accessible to people with disabilities. The World Wide Web (W3C) Consortium's Web Content Accessibility Guidelines (WCAG) 2.0 Level AA function as the current legal standard for website accessibility. 

Get acquainted with accessibility: https://www.ada.gov/pcatoolkit/chap5toolkit.htm  

List of [WCAG 2.0 Compliance Checkers](https://github.com/hackforla/website/wiki/WCAG-2.0-Compliance-Checkers)

**Comment by ale22arevalo** [comment]
Wiki color contrast review outcomes:
- [aXe](https://www.deque.com/axe/): tool couldn't analyze wiki
- [SiteImprove](https://chrome.google.com/webstore/detail/siteimprove-accessibility/efcfolpjihicnikpmhnmphjhhpiclljc): didn't identify issues with current color contrasts
- [Tenon](https://tenon.io/): didn't show any issues
- [WAVE](https://wave.webaim.org/extension/): approved color contrasts
<img width="422" alt="Screen Shot 2022-07-25 at 9 24 10 AM" src="https://user-images.githubusercontent.com/44823677/180787992-792d4d42-1616-4735-9226-35b8dcae48db.png">
- Google Chrome Lighthouse: no c
[Site optimization report.pdf](https://github.com/hackforla/internship/files/9181571/Site.optimization.report.pdf)
olor issues found

**Comment by ale22arevalo** [comment]
Update 8/18: I've been working on iconography, typography and layout for web and mobile interfaces. Our design system uses [HfLA's website design system](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) as reference, but other resources to continue this work include [Material UI](https://mui.com/) and [Figma's design system](https://www.figma.com/community/file/928108847914589057)
- Latest addition to design system: Basic anatomy of webpage (desktop and mobile) https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=1705%3A6168

**Comment by ale22arevalo** [comment]
1. Progress: Came up with three issues to breakdown into smaller tasks this big issue and make it easier to tackle + currently making updates to design system (adding on hover states, error messages and modals)
2. Blockers: No blockers
3. Availability: ~6hours
4. ETA: Sep. 14

**Comment by ale22arevalo** [comment]
Create elements for component library

- Secondary Buttons
- Shape Style
- Text input fields
- Text Area
- Cards, lists
- Selection Area
- Dropdowns
- Modals

Create a UX Writing language guide for website

- Text used for buttons, commands, error messages etc.
- Copywriting for cards, messages, text boxes

Define interactions states of interactive elements

- Hover States
- Clicks
- Selection State
- Disabled/Activated
- Drag
- Pressed

**Comment by cbutcher318** [comment]
@cbutcher318 need to decompose into smaller issues

**Comment by cbutcher318** [comment]
Progress: Started to break this down by creating #358

**Comment by priyatalwar** [comment]
Design team needs guidance on the requirements of the design system

**Comment by priyatalwar** [comment]
- This issue is being replaced by #358
