### ISSUE TITLE
TWI: Product development

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#127]
### Overview
We need to streamline our documents and processes so that we can produce a out-of-the-box internship program for schools/companies.

#### Product

- [ ] Draft a template for internship openings
- [ ] Draft a guide on how to reach out to potential partners

  #### UX Research

- [ ] Draft forms for
  - [ ] Preselection Intern interviews
  - [ ] Internship Check-In
  - [ ] Exit interviews

  #### UX Writer

- [ ] A

  #### UI/UX Design

- [ ] A
