### ISSUE TITLE
Make issues from Agenda Task Items (never closes)

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#128]
### Overview
We need to be able to make issues quickly from task items brought up during meetings and when working on other issues.

### Action Items
Create an item here as a checkbox
Convert Item to issue

### Resources/Instructions
- #49
- #101 
- #62 

### Task Items carried forward
- [ ] Make issues
   - [ ] IS22: Create acceptance letter
     -  [ ] See prior acceptance letter [IS21: Internship acceptance messaging](https://docs.google.com/document/d/1qW1Jo2217HpJZRw-NtOlPBWCF03WiCH-bQMPfyZ91cc/edit)
  - [ ] IS22: Create new check in form for Interns
     - [ ] see [Summer Internship Check-In](https://docs.google.com/forms/d/1dLnvtsApjcWHgcvzjNoBAy_5LJSZ8YJpfJNV4NkeFIM/edit) (missing design elements)

**Comment by ExperimentsInHonesty** [comment]
```
### Resources/Instructions
- [Internship Figma, Color Mood Board - Cherilyn ](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A14)
- [Internship Figma, Style Guide](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A2)

#### Other teams
- [Internship Figma, Style Guide](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A2) - they are in the process of figuring out what they want to do 
- [Hack for LA website team Figma, Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) - this team has a working design system and color palette
 ```

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty 
- Can we remove the 'Items Carried Forward' heading and just put the issues under the Issues to Make heading? It's confusing this way.
- I was able to access the [Internship AMA 2021](https://docs.google.com/document/d/1v_ZUO0sK-CFkkOCcTA1MejDS-ohCHCzDFFG2bVciJQY/edit) document, so is it safe to assume that this has been resolved?

**Comment by Rabia2219** [comment]
For Service Hours issue:
Link to new shared drive. 
https://us02st1.zoom.us/web_client/zsc0psq/html/externalLinkPage.html?ref=https://drive.google.com/drive/folders/1LZUi6Kh4ed7grLmrtzzV8I9IPJuzahLD?usp=sharing

**Comment by Rabia2219** [comment]
> @Rabia2219 @ExperimentsInHonesty
> 
> Is this Issue to be created: IS22: Interview script draft different from this issue: IS22: Internship Interviews #135

Looks like a duplicate of #138 
We can remove it after confirming what PM meeting it was added during...

**Comment by ExperimentsInHonesty** [comment]
Time sensitive items for today
- #129
- Writing a letter for Mateo to school #156

**Comment by epierotti3** [comment]
Update:
1. Progress: made correspondence issues #307 and #308, updated the links for the mentor off- boarding issues, started working on the empty wiki pages issue and created #306 which has been assigned to a new UX team member. Many other empty wiki pages mentioned on that issue have since been tackled through the epic #276 . 
2. Blockers: unsure of next step on empty wiki pages - there may be some pages we find we do not need any longer.
3. Availability: none - leaving HfLA for time being so this needs to be picked up by another PM.
4. ETA: N/A

**Comment by priyatalwar** [comment]
as per 3/13/23 meeting Issues to be created
- Create a design roadmap
- Create an epic to list the things we need to get our project on the HfLA website

**Comment by sunannie27** [comment]
1. Progress: Tried create issue to review service hours but the links provided were not accessible and I was confused about the point of the issue. I also was unsure how to create a new issue template
2. Blockers: Links not accessible
3. Availability: 5
4. ETA: In the next week

**Comment by sunannie27** [comment]
Done with changes to the self offboarding issue, now waiting to prioritize
