### ISSUE TITLE
Intern Linkedin Setup Checklist: Sakari

### ISSUE THREAD

**Issue by Zytko** [hackforla/internship#13]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items
Check off each of the items as you complete it, adding the content of what you wrote under the item.

#### Top

- [x] Name
- [x] Photo
- [x] Title
- [x] Organization
- [x] City
- [x] Email

#### Customize your url
- [x] Make sure you get rid of the numbers, generally firstnamelastname, lastname-firstname firstnameMiddleInitialLastname, etc.

#### About

- [x] Description
- [x] List of skills (see [slide 48](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_50) for example

#### Featured

- [ ] Two articles or an article and a portfolio

#### Activity

- [ ] Comments 
- [ ] Posts

#### Experience

- [ ] Hack for LA
   - [ ] Fill out [Spreadsheet]( https://docs.google.com/spreadsheets/d/1SMNhL34zfCsIWOnHZ2hXjXLL7ZfX54LXSglkGZb-Xms/edit?ouid=103640526393818575616&usp=sheets_home&ths=true)
   - [ ] Meet with Bonnie and revise wording
   - [ ] Post to Linkedin

#### Education

- [ ] List of schools attended

#### Skills and Endorsements

- [ ] List your skills 
- [ ] Give your team members endorsements when they help you with one of the skills

#### Recommendations

- [ ] Ask for recommendations
- [ ] Review submitted recommendations
- [ ] Accept recommendation

#### Accomplishments

- [ ] Items that don't fit anywhere else (old, or outside of experience you want to list)

#### Interests

- [ ] add three

### Resources/Instructions

[Linkedin](https://www.linkedin.com)
[Linkedin deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Sakari Saminiitty LinkedIn](https://www.linkedin.com/in/sakari-salminiitty/)

**Comment by Zytko** [comment]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items

#### Top

- [ ] Name
- [ ] Photo
- [ ] Title
- [ ] Organization
- [ ] City
- [ ] Email

#### About

- [ ] Description
- [ ] List of skills

#### Featured

- [ ] Two articles or portfolios

#### Activity

- [ ] 

#### Experience

- [ ] 

#### Education

- [ ] List of schools attended

#### Skills and Endorsements

- [ ] 

#### Recommendations

- [ ] 

#### Accomplishments

- [ ] 

#### Interests

- [ ] 

### Resources/Instructions

[Linkedin](https://www.linkedin.com)
[Linkedin deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)

**Comment by ExperimentsInHonesty** [comment]
Left off at fixing a few remaining items on spreadsheet.

**Comment by ExperimentsInHonesty** [comment]
@Zak234 you still have some outstanding items

- [ ] Have you listed all your skills under skills section?  
- [ ] When you are done doing that don't forget to ask people who have reviewed your prs to give you endorsements on those skills.
- [ ] Let us know when you are done with the linkedin profile

**Comment by ExperimentsInHonesty** [comment]
@Zak234 I recommend the following additional steps
- [ ] Go into the Hack for LA team roster and connect with each person who did a pr review or issue completed for you
- [ ] Once they have accepted your linkedin request, go to their profile and endorse them for the skills that your issue required.  So if your issue was a Figma issue, then endorse them for that, etc.
- [ ] Then wait a few days, and write to them asking them if they would consider endorsing you for that skill and reminding them of the pr or issue (including putting a link to the item). 
#### Note: you only NEED one endorsement per skill to make it show up when recruiters are searching for you.  But you do need at least one.

Snapshot of current
![image](https://user-images.githubusercontent.com/37763229/131389403-8079fbc2-d169-4d22-bd39-dc8c399887e4.png)

**Comment by ExperimentsInHonesty** [comment]
Sakari is connected to Josh, Adam, Abel, QiQi

**Comment by ExperimentsInHonesty** [comment]
Sent Sakari this email
Hi Sakari,

I assume we are not meeting today.  If you do want to meet today, let me know.

Here are some outstanding items for you for your linkedin to be complete for the internship.
https://github.com/hackforla/internship/issues/13#issuecomment-908596961
https://github.com/hackforla/internship/issues/13#issuecomment-911915037

Bonnie

**Comment by ExperimentsInHonesty** [comment]
@Zak234 We just did a check in to see if you were able to successfully finish up your networking.  Here are the outstanding items,

Sakari is not yet connected to: Akib, Kristine, Danielle - you can find most of their linkedin urls on the team roster
Sakari performed many pr reviews and should connect with each of those people: https://github.com/hackforla/website/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me

Sakari has not received endorsements for the some of the skills obtained during the internship
https://github.com/hackforla/internship/issues/13#issuecomment-908596961

**Comment by priyatalwar** [comment]
@Zak234 Friendly reminder looks like you were not able to finish networking. It is not too late.  Here are the outstanding items,

Sakari is not yet connected to: Akib, Kristine, Danielle - you can find most of their linkedin urls on the team roster
Sakari performed many pr reviews and should connect with each of those people: https://github.com/hackforla/website/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me

Sakari has not received endorsements for the some of the skills obtained during the internship
https://github.com/hackforla/internship/issues/13#issuecomment-908596961
