### ISSUE TITLE
Linkedin Setup Checklist: Sophia

### ISSUE THREAD

**Issue by Zytko** [hackforla/internship#14]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items
Check off each of the items as you complete it, adding the content of what you wrote under the item.

#### Top

- [x] Name
- [x] Photo
- [x] Title
- [x] Organization
- [x] City
- [x] Email
#### Customize your url
- [x] Make sure you get rid of the numbers, generally firstnamelastname, lastname-firstname firstnameMiddleInitialLastname, etc.

#### About

- [x] Description
- [x] List of skills  (see [slide 48](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_50) for example

#### Featured

- [ ] Two articles or an article and a portfolio

#### Activity

- [ ] Comments 
- [ ] Posts

#### Experience
- [x] other experience
  - [x] add to linkedin
- [x] Hack for LA
   - [x] Fill out Spreadsheet and add link below
   - [x] Meet with Bonnie and revise wording
   - [x] Post to Linkedin

#### Education

- [x] List of schools attended

#### Skills and Endorsements

- [x] List your skills 
- [x] Give your team members endorsements when they help you with one of the skills

#### Recommendations

- [ ] Ask for recommendations
- [ ] Review submitted recommendations
- [ ] Accept recommendations

#### Accomplishments

- [x] Items that don't fit anywhere else (old, or outside of experience you want to list)

#### Interests

- [ ] add three

### Resources/Instructions

[Linkedin](https://www.linkedin.com)
[Linkedin deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Sophia Ling Linkedin](https://www.linkedin.com/in/ling-sophia/)
[Sakari's Activity Log example](https://docs.google.com/spreadsheets/d/1SMNhL34zfCsIWOnHZ2hXjXLL7ZfX54LXSglkGZb-Xms/edit#gid=0)
[Sophia's Activity Log](https://docs.google.com/spreadsheets/d/17lCDtjuB25eahvjg67Jy8no-eVheKvTlUwnqlkQtED0/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
ideas for portfolio

**Show your work**
screenshots of visually interesting work
Comics
Before and after image with text in Mandarin and the after with the same in English

Hack for LA
finished screen shot from figma
talk about creating a new asset using the design system established by previous designer
screen shot showing desktop and mobile design you made based on the live (backfilling the design catalog) in figma so that they have a record of as-is state in order to enable future iterations.
blah blah blah about responsiveness and identifying desired behavior for best experience.

**Philosophy**

**Contact info and the type of work you are open to.**

**Comment by ExperimentsInHonesty** [comment]
@anonymousanemone will add the relevant Computer Science and Art classes to the Brentwood School section

**Comment by ExperimentsInHonesty** [comment]
We stopped at the spreadsheet on row 11 because we went on a tangent about where/how css files should be.

**Comment by ExperimentsInHonesty** [comment]
you can customize your header to match your portfolio

**Comment by ExperimentsInHonesty** [comment]
@anonymousanemone please finish updating your linkedin profile and let us know when you are done;

**Comment by ExperimentsInHonesty** [comment]
@anonymousanemone I recommend the following additional steps
- [ ] Go into the Hack for LA team roster and connect with each person who did a pr review or issue completed for you
- [ ] Once they have accepted your linkedin request, go to their profile and endorse them for the skills that your issue required.  So if your issue was a Figma issue, then endorse them for that, etc.
- [ ] Then wait a few days, and write to them asking them if they would consider endorsing you for that skill and reminding them of the pr or issue (including putting a link to the item). 
#### Note: you only NEED one endorsement per skill to make it show up when recruiters are searching for you.  But you do need at least one.

**Comment by ExperimentsInHonesty** [comment]
these people reviewed pr issues for Sophia: akib, ava, sakari, adam, Kristine, Matthew

hard to tell what looked at non pr issues

**Comment by ExperimentsInHonesty** [comment]
@anonymousanemone can you give us an update on your progress here: https://github.com/hackforla/internship/issues/14#issuecomment-908558229

it looks like you are still not connected to akib, ava, adam, & Matthew
You can find their linkedin profile in the roster: https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0
except for Ava.  I'll reach out to her to ask her to add it.

**Comment by ExperimentsInHonesty** [comment]
Sent her an email with the details from above

**Comment by ExperimentsInHonesty** [comment]
Sophia reached out to the list of people we mentioned and got the needed endorsements she could gather from the HfLA team.
