### ISSUE TITLE
Linkedin Setup Checklist: Jason

### ISSUE THREAD

**Issue by Zytko** [hackforla/internship#16]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

#### Top
- [x] Name
- [x] Photo
- [x] Title
- [x] Organization
- [x] City
- [x] Email

#### Customize your url
- [x] Make sure you get rid of the numbers, generally firstnamelastname, lastname-firstname firstnameMiddleInitialLastname, etc.

#### About
- [x] Description
- [x] List of skills
- [Draft](https://docs.google.com/document/d/13LL-9dRLiJ3VQSTc1QG2ZDM1dItSltvvt56dMDGFUqg/edit)

#### Featured
- [ ] Two articles or an article and a portfolio

#### Activity
- [ ] Comments 
- [ ] Posts

#### Experience
- [ ] Hack for LA
   - [x] Fill out [Spreadsheet]
   - [x] Meet with Bonnie and revise wording
   - [x] Post to Linkedin

#### Education
- [x] List of schools attended

#### Skills and Endorsements
- [x] List your skills 
- [x] Give your team members endorsements when they help you with one of the skills

#### Recommendations
- [ ] Ask for recommendations
- [ ] Review submitted recommendations
- [ ] Accept recommendations

#### Accomplishments
- [x] Items that don't fit anywhere else (old, or outside of experience you want to list)

#### Interests
- [ ] add three

### Resources/Instructions
[Linkedin](https://www.linkedin.com)
[Linkedin deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Template for recording Activity](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=0)
[Jason's Activity Spreadsheet](https://docs.google.com/spreadsheets/d/1quTmv3kH4JmVDdFefVHrtTpphaThYIuK8GPP_ltt0-0/edit#gid=0)
[Sakari's Activity Log example](https://docs.google.com/spreadsheets/d/1SMNhL34zfCsIWOnHZ2hXjXLL7ZfX54LXSglkGZb-Xms/edit#gid=0)
[Jason's LinkedIn profile](https://www.linkedin.com/in/jasonuranta/)

**Comment by Zytko** [comment]
This is to help you keep track of your progress in our Linkedin Workshops

**Comment by JasonUranta** [comment]
Thank you!

**Comment by ExperimentsInHonesty** [comment]
@JasonUranta All next steps on your linkedin profile are optional.  Feel free to close this issue

**Comment by JasonUranta** [comment]
Thank you!!
