### ISSUE TITLE
Linkedin Setup Checklist: Mateo

### ISSUE THREAD

**Issue by Zytko** [hackforla/internship#17]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

#### Top

- [x] Name
- [ ] Photo
- [x] Title
- [x] Organization
- [x] City
- [x] Email

#### Customize your url
- [x] Make sure you get rid of the numbers, generally firstnamelastname, lastname-firstname firstnameMiddleInitialLastname, etc.

#### About

- [x] Description (see notes in [comment](https://github.com/hackforla/internship/issues/17#issuecomment-886857648) below)
- [x] List of skills

#### Featured

- [ ] Two articles or an article and a portfolio

#### Activity

- [ ] Comments 
- [ ] Posts

#### Experience

- [ ] Hack for LA
   - [ ] Fill out [Spreadsheet](https://docs.google.com/spreadsheets/d/1dzvR8F0UWWo8rQ3pMGNO7mC9DlPUOdFHJ7p8uqmADGc/edit#gid=0)
   - [ ] Meet with Bonnie and revise wording
   - [ ] Post to Linkedin

#### Education

- [x] List of schools attended

#### Skills and Endorsements

- [x] List your skills 
- [ ] Give your team members endorsements when they help you with one of the skills

#### Recommendations

- [ ] Ask for recommendations
- [ ] Review submitted recommendations
- [ ] Accept recommendations

#### Accomplishments

- [ ] Items that don't fit anywhere else (old, or outside of experience you want to list)

#### Interests

- [x] add three

### Resources/Instructions

[Linkedin](https://www.linkedin.com)
[Linkedin deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Mateo LinkedIn Profile](https://linkedin.com/in/mateogodoy)
[Sakari's Activity Log example](https://docs.google.com/spreadsheets/d/1SMNhL34zfCsIWOnHZ2hXjXLL7ZfX54LXSglkGZb-Xms/edit#gid=0)

**Comment by Zytko** [comment]
This is to help you keep track of your progress in our Linkedin workshops

**Comment by ExperimentsInHonesty** [comment]
**current**
I am a student-athlete at Princeton University with a passion for complex challenges and problem solving in the realm of computer science and neuroscience - looking for collaborative spaces to thoughtfully attack the intersection of both fields where I can work on a team to have an impact while continuously learning and improving.

**new**
I am a student-athlete at Princeton University looking for opportunities to collaborate with high energy teams on the frontier of computer science and neuroscience; exploring complex challenges and creating next generation solutions.

**Comment by ExperimentsInHonesty** [comment]
Check out Sophia Alice's linkedin profile for her skills listed in the about section: https://www.linkedin.com/in/sophia-alice/

**Comment by ExperimentsInHonesty** [comment]
deliverable for next week
- [ ] Write up the GitHub action item on Activity Log
- [ ] Write up the guide (based on what Sophia says)
https://github.com/hackforla/engineering/issues/17#issuecomment-891177672
- [ ] Photo

Additional items not related to Linked
- [ ] write up issue for donate page removing the redirect

**Comment by ExperimentsInHonesty** [comment]
Updated spreadsheet with @mgodoy2023  and provided next steps
Reach out to Gideon for review on the bullet points and ordering by value
Write up Responsible for text
Add to linkedin
Ask for recommendation from Gideon for your linkedin Profile (after you have added the work experience), providing them with 3 bullet points you would like them to expand on, that you think are not covered by the Activity listed (ex: empathetic leader)
```
Hi X.

Thank you for offering to write a recommendation.  After looking at the details of my work at [insert name of their company], which you can see here: [insert link to linkedin profile], I realize that what is not portrayed is the kind of employee I am.  I think it does not communicate that I am. 
- [insert thing]
- [insert thing]
- [insert thing]
I hope your recommendation will help fill in the human aspect of the Gideon Internship Story.
```
Here is an example of the bullets that led me to write this about Tim:
- Quick Study
- Eye for Design
- Dependable
- Good Communicator

When Tim joined the Hack for LA Host Home team, we were 3 weeks away from proof of concept demo to a key potential project funder meeting and we were not going to hit the target deadline. Because Tim is an extremely quick study he was able to use an unfamiliar language (TypeScript) and his eye for design, to sort out the inconsistencies in our mock ups and produce/restructure/fix the entire front end.

In the months that followed, the team has grown around some dependable key members, with Tim being the Front End Lead and providing a collaborative and supportive environment for new devs, and effective communication with all other Leads and the Product team (the PM and myself as the portfolio owner/stakeholder representative).

I am very proud of the important work that the Host Homes team is doing on the vital issue of housing youth experiencing homelessness. Tim is an invaluable part of that team and he would be an excellent asset to any technical team or office.

-
