### ISSUE TITLE
Build a tracking tool/checklist for intern non-work related accomplishments

### ISSUE THREAD

**Issue by Annie-Truong** [hackforla/internship#196]
### Overview
We need to create a tracking tool/checklist in order to track intern non-work related accomplishments. 

### Action Items

- [ ] Brainstorm ideas on how to build tracking tool
- [ ] Create a draft
- [ ] Review the solution
- [ ] Finalize the solution 
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
- IS21 Skills [tracker](https://docs.google.com/spreadsheets/d/11KC6P07dr_DEIq5lGZ_vqyakq-rfOEBSTqqduFLiVbs/edit#gid=305914592)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
