### ISSUE TITLE
TWE: Set up Intern Intake Interview Training Session

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#202]
### Dependencies
- #187

### Overview
We need to set up an Intern Intake Interview training session for UXRs so that they are prepared to conduct the intake interviews on the day the interns are onboarded.

### Action Items

- [x] Create an instruction guide on how to practice for the Intern Intake Interview
- [x] Create slide deck for presenting on the day-of
- [x] #205 
- [x] #206 
- [x] #207 
- [x] Setup Easy retro:
   - [x]  For Q&A during presentation
   - [x] For Q&A during the practice interviews
- [x] Create a form for uploading the recordings
- [x] Set up Zoom meeting for the training day (June 15th)
- [x] Create a spreadsheet to monitor and approve respondents from form
- [x] Send out acceptance emails to approved UXRs
- [x] Add approved UXRs to the meeting invite
- [x] Setup roll call session table for the day of training
- [x] Create post training feedback form
- [x] Conduct training on Wednesday, June 15 from 5 - 7 pm
- [x] Transfer/Delete recordings to make room for actual day-of recordings
- [x] Update relevant WIKI page (See resources)

#### Examples
- [BOP Interview Training Deck](https://docs.google.com/presentation/d/1kX6K1KWhPMz97CpJIUK9QTgrIlmxt_oLvC2m0lJJm_E/edit#slide=id.g974edb4642_0_0)
- [BOP UXR Interview Instructions](https://docs.google.com/document/d/1dLre3WRLXG8KzvM3McSWCtu0EVBSvGPt2O368sfa0z8/edit)
- [01 TDM Calculator UXR Onboarding ](https://docs.google.com/presentation/d/1Cy5f1uDY7vW1vlsuDXdDvCpygUcQoct24VD6k0pRMGs/edit#slide=id.gcf645e8492_3_8)
- [BOP Interview Upload Form](https://docs.google.com/forms/d/e/1FAIpQLSd_eQ6u06IySOLpkf1Qgv_B9py4XhRiW_DmO4o1ckHvcaFPvA/viewform)

#### TWE Resources
- [TWE Interview Training Deck](https://docs.google.com/presentation/d/1kAo2QSam5rCAsffk14PQb-lqkVZykCNqsU_kHZQXmxY/edit#slide=id.p)
- [TWE Interview Instructions](https://docs.google.com/document/d/1UwjsKQcVc3ZQRCaePmygM4o-b9paSEsbczTZV0RFucY/edit?pli=1)
- [Google Form TWE Onboarding Interview Script](https://docs.google.com/forms/d/e/1FAIpQLSeukVnzqTUx-6s1qB44tRsaq6VfbZve8WmYGj65yuuyVOG7yg/viewform?usp=pp_url&entry.998411156=Mugtaba&entry.963624865=1&entry.618797341=No)
- [TWE: RP6: Intern Intake Interview Session Table](https://docs.google.com/spreadsheets/d/11agqyxXr-sD_nCbUQJoh49NACqr9GiThd25lGe6ajQw/edit#gid=1585831764)
- [Duplicate questions reconciliation (on Intern Intake Interview Form)](https://docs.google.com/spreadsheets/d/1_CHYIgL33t09cdvqazj7vsrn1kzuabldpo1dR3xgwLU/edit#gid=0)
- [Internship Wiki, Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

#### Training Day Resources
- Training session timer link
https://cuckoo.team/InternIntakeInterviewTraining
- Roll call session table
[TWE: RP6: Intern Intake Interview Session Table, rollcall](https://docs.google.com/spreadsheets/d/11agqyxXr-sD_nCbUQJoh49NACqr9GiThd25lGe6ajQw/edit#gid=0)
- Deck
[TWE RP6 Intern Intake Interview Training-IS 22 Slides](https://docs.google.com/presentation/d/1kAo2QSam5rCAsffk14PQb-lqkVZykCNqsU_kHZQXmxY/)
- Instructions document
[TWE RP6 Intern Intake Interview Instructions](https://docs.google.com/document/d/1UwjsKQcVc3ZQRCaePmygM4o-b9paSEsbczTZV0RFucY)
- Copy of Intern Intake Interview form
[TWE RP6 Intern Intake Interview Script/Form - Practice Copy](https://docs.google.com/forms/d/e/1FAIpQLSeukVnzqTUx-6s1qB44tRsaq6VfbZve8WmYGj65yuuyVOG7yg/viewform?usp=pp_url&entry.998411156=Mugtaba&entry.963624865=1&entry.618797341=No)
- Easy Retro
   - [TWE: UXR Intake Interview Instructions Q&A](https://easyretro.io/publicboard/Mnp86bSJqeYqvY8Gpu2QdfXYxfe2/3f10c27c-eb1f-4d6f-91ec-5ca0cc1b7c8e)
   - [TWE: UXR Interview Practice Q&A](https://easyretro.io/publicboard/Mnp86bSJqeYqvY8Gpu2QdfXYxfe2/f0870d06-9ad8-4f19-88f8-fd7d34c61c9b)
- Recording upload form
[Finishing up: Sending your Recording to TWE team](https://docs.google.com/forms/d/1vjFMf6RiUs0FerIbCNl4xM_dTBkSBBTIOQuyHu5vJ6c/edit)
- Post training feedback
[Feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeEwSAO5NQrXNQGxzHiPtdWqoWP9lH2NQ0sLBRqrw2UssOysw/viewform)

**Comment by christine-el** [comment]
@ExperimentsInHonesty --Was there another link to the copy of the BOP training slide deck that you were starting to edit?  I feel like there are some slide missing from this one:  https://docs.google.com/presentation/d/1kX6K1KWhPMz97CpJIUK9QTgrIlmxt_oLvC2m0lJJm_E/edit#slide=id.g974edb4642_0_0

**Comment by christine-el** [comment]
@ExperimentsInHonesty **Draft of recruitment message to send out over slack--Please revise as needed**:  The internship project is looking for UX researchers who can help us to conduct interviews with our incoming cohort of summer interns!  You must be available on Wednesday, June 15 from 5-6pm PST for a brief training and then again on Monday, June 20 from 12:00-1:00 to conduct the interviews.  Please contact [@Christine El Ouardani](https://hackforla.slack.com/team/U036N7DJRF0) if you are interested in participating.

**Comment by ExperimentsInHonesty** [comment]
Fun Retro Boards 
[TWE: UXR Interview Instructions Q&A](https://easyretro.io/publicboard/Mnp86bSJqeYqvY8Gpu2QdfXYxfe2/3f10c27c-eb1f-4d6f-91ec-5ca0cc1b7c8e)
[TWE: UXR Interview Practice Q&A](https://easyretro.io/publicboard/Mnp86bSJqeYqvY8Gpu2QdfXYxfe2/f0870d06-9ad8-4f19-88f8-fd7d34c61c9b)

**Comment by ExperimentsInHonesty** [comment]
I am working on a draft... these are my notes, you can ignore.
Hack for LA's Internship project is looking for researchers to conduct interviews on Monday, June 20th at noon PST.  Training will be provided.  Read our overview page to find answers to all your questions

The internship project is looking for UX researchers who can help us to conduct interviews with our incoming cohort of summer interns! You must be available on Wednesday, June 15 from 5-6pm PST for a brief training and then again on Monday, June 20 from 12:00-1:00 to conduct the interviews. Please contact [@Christine El Ouardani](https://hackforla.slack.com/team/U036N7DJRF0) if you are interested in participating.

**Comment by ExperimentsInHonesty** [comment]
next steps to avoid spending too much labor on automatable things
- [ ] Create landing page on wiki with info for [perspective UXRs](https://github.com/hackforla/internship/wiki/RP6:-UXR-Training)
- [ ] Create form for them to express Interest
- [ ] Send out slack message
```
@channel Hack for LA's #Internship project is ** 👀 looking for researchers to conduct interviews** on ⏰Monday, June 20th at noon PST.  🎉Training will be provided. [Read our overview page](https://github.com/hackforla/internship/wiki/RP6:-UXR-Training) to find answers to all your questions ⁉️
```

**Comment by ExperimentsInHonesty** [comment]
Just sent to UI/UX channel 2022-06-11-2:19
![image](https://user-images.githubusercontent.com/37763229/173205209-2651801d-52a6-4b27-9408-e934f7e21787.png)

**Comment by ExperimentsInHonesty** [comment]
- Bonnie will update meetup and provide link here
- Bonnie will write up draft message to send to [ui/ux channels](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/preview)

**Comment by christine-el** [comment]
- [ ] Item #3 on - [Google Form TWE Onboarding Interview Script](https://docs.google.com/forms/d/17MC9FRH3ToYvM4BFEZGxJHdOVAl1CeJw96xQpqSCLG8/edit) needs to be clarified

**Comment by christine-el** [comment]
@Rabia2219 Here is a copy of the BOP Interview Upload form and I'll also put it under the resources above:  https://docs.google.com/forms/d/e/1FAIpQLSd_eQ6u06IySOLpkf1Qgv_B9py4XhRiW_DmO4o1ckHvcaFPvA/viewform

**Comment by ExperimentsInHonesty** [comment]
```
Looking to build up your resume as a UI/UX researcher with hands-on experience conducting interviews? Hack for LA's Internship project is :eyes: looking for volunteer researchers to conduct interviews with our high school and college-age interns.
:point_right: Onboarding happens tonight, Monday, June 13th from 6-8pm PST
:tada:Training will be provided Wednesday, June 15 from 5-6pm PST.
:alarm_clock: Interviews are scheduled for Monday, June 20th at 12pm (noon) PST.
:interrobang:Read our overview page to find answers to all your questions and Let us know you are interested!
```

**Comment by ExperimentsInHonesty** [comment]
@christine-el we are looking for the instructions document you are creating

**Comment by ExperimentsInHonesty** [comment]
Document for instructions should have a day of checklist that includes
them confirming that they are cohosts
that they record session

**Comment by ExperimentsInHonesty** [comment]
We made some changes to the script and want to discuss them with you
[Duplicate questions reconciliation](https://docs.google.com/spreadsheets/d/1_CHYIgL33t09cdvqazj7vsrn1kzuabldpo1dR3xgwLU/edit#gid=0)

**Comment by christine-el** [comment]
@ExperimentsInHonesty Here is the link to the interview instructions:  https://docs.google.com/document/d/1I1rpMIrUw7uySYUA3zVhVIM38c2m6EPf8-nRWV9Xgis/edit  It is titled "TWE Interview Instructions" under Resources above.

**Comment by Rabia2219** [comment]
@ale22arevalo 
Hi Alejandra,
You need to check this [spreadsheet](https://docs.google.com/spreadsheets/d/1smQ2jWwh6e8oI5R3jFjqAHvjlIbSDtxc-7YfCsIcJ5g/edit#gid=716489189) to see what channels Christine was able to post the recruitment message to and pick up where she left off. The message to post is in this [slack comment](https://hackforla.slack.com/archives/C01VAUPU788/p1655145709817809).

**Comment by ExperimentsInHonesty** [comment]
@christine-el We made some changes to the script to simplify the process for the UXRs to ask only the high school or college questions based on the user they are interviewing.  We still need to re-number then questions, but wanted to run through the flow with you before we do that.  When would be a good time for us to talk again?  

- [Google Form TWE Onboarding Interview Script](https://docs.google.com/forms/d/17MC9FRH3ToYvM4BFEZGxJHdOVAl1CeJw96xQpqSCLG8/edit)

- [Duplicate questions reconciliation](https://docs.google.com/spreadsheets/d/1_CHYIgL33t09cdvqazj7vsrn1kzuabldpo1dR3xgwLU/edit#gid=0)

**Comment by christine-el** [comment]
- [ ] Once the google form has been finalized and approved, create a practice version to be used during the training
- [ ] Link either the original or the practice version of the google form into the interview instructions

**Comment by christine-el** [comment]
@ExperimentsInHonesty @Rabia2219 I've made my final edits to the [Google Form TWE Onboarding Interview Script](https://docs.google.com/forms/d/17MC9FRH3ToYvM4BFEZGxJHdOVAl1CeJw96xQpqSCLG8/edit), [TWE Interview Instructions](https://docs.google.com/document/d/1I1rpMIrUw7uySYUA3zVhVIM38c2m6EPf8-nRWV9Xgis/edit), and [TWE Interview Instructions](https://docs.google.com/document/d/1I1rpMIrUw7uySYUA3zVhVIM38c2m6EPf8-nRWV9Xgis/edit) and they are ready for a final review.  

In the comment above I've created a checklist of outstanding items that I will need help with.

Otherwise, I think I'm good to go for tomorrow!

**Comment by bradyse** [comment]
> 

@christine-el 

@adarosh, Bonnie, and I worked on editing TWE Interview Instructions document, ensuring slides that got skipped had info in the document. We also went through and updated the Google Form TW Onboarding Interview with some minor edits.

**Comment by Annie-Truong** [comment]
We need to update the link to the TWE Interview Instructions to: https://docs.google.com/document/d/1UwjsKQcVc3ZQRCaePmygM4o-b9paSEsbczTZV0RFucY/edit?pli=1

**Comment by Rabia2219** [comment]
The people added to the spreadsheet all have Editor access except one

**Comment by Rabia2219** [comment]
Notes from training
- Update your Zoom before joining onboarding
- Have the participants join a breakout room and check if they are able to record or not before the actual session starts

**Comment by Rabia2219** [comment]
### Overview
We need to create a training slide deck, recruit interviewers, and carry out the training in order to prepare researchers to conduct interviews during the June 20th intern onboarding.  

### Action Items

- [x] Create a draft messageto send out over Slack to recruit UX researchers for this project.
- [x] Christine will reach out to Linda to see if she can help with the deck.
- [x] Set up a time to pilot the training with Elizabeth on Monday or Tuesday.
- [x] Bonnie will set up the Easy Retro account to use in the training.
- [x] Christine will draft the copy of the training slide deck.
- [x] Alejandra will design the deck.
- [x] Christine will draft the UXR Interview Instructions.
- [x] Christine will revise the Google From Interview Script.
- [x] Review deck with Bonnie at a Sunday meeting at 2pm PST (see google calendar invite).
- [x] Set up a Zoom meeting time for the training and link.  
- [x] Review the deck with Elizabeth
- [x] Create following issues
    - [x] #206
    - [x] #205
    - [x] #207
- [x] Conduct training on Wednesday, June 15 from 5-6pm. 
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
#### Examples
- [BOP Interview Training Deck](https://docs.google.com/presentation/d/1kX6K1KWhPMz97CpJIUK9QTgrIlmxt_oLvC2m0lJJm_E/edit#slide=id.g974edb4642_0_0)
- [BOP UXR Interview Instructions](https://docs.google.com/document/d/1dLre3WRLXG8KzvM3McSWCtu0EVBSvGPt2O368sfa0z8/edit)
- [01 TDM Calculator UXR Onboarding ](https://docs.google.com/presentation/d/1Cy5f1uDY7vW1vlsuDXdDvCpygUcQoct24VD6k0pRMGs/edit#slide=id.gcf645e8492_3_8)
- [BOP Interview Upload Form](https://docs.google.com/forms/d/e/1FAIpQLSd_eQ6u06IySOLpkf1Qgv_B9py4XhRiW_DmO4o1ckHvcaFPvA/viewform)

#### TWE Resources
- [TWE Interview Training Deck](https://docs.google.com/presentation/d/1kAo2QSam5rCAsffk14PQb-lqkVZykCNqsU_kHZQXmxY/edit#slide=id.p)
- [TWE Interview Instructions](https://docs.google.com/document/d/1UwjsKQcVc3ZQRCaePmygM4o-b9paSEsbczTZV0RFucY/edit?pli=1)
- [Google Form TWE Onboarding Interview Script](https://docs.google.com/forms/d/e/1FAIpQLSeukVnzqTUx-6s1qB44tRsaq6VfbZve8WmYGj65yuuyVOG7yg/viewform?usp=pp_url&entry.998411156=Mugtaba&entry.963624865=1&entry.618797341=No)
- [TWE: RP6: Intern Intake Interview Session Table](https://docs.google.com/spreadsheets/d/11agqyxXr-sD_nCbUQJoh49NACqr9GiThd25lGe6ajQw/edit#gid=1585831764)
- [Duplicate questions reconciliation (on Intern Intake Interview Form)](https://docs.google.com/spreadsheets/d/1_CHYIgL33t09cdvqazj7vsrn1kzuabldpo1dR3xgwLU/edit#gid=0)
- [Internship Wiki, Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by ExperimentsInHonesty** [comment]
I have copied all the relevant links and notes to the wiki page
https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews
and am closing this issue
