### ISSUE TITLE
TWE'22: Project Roadmap for Mentor Research

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/internship#208]
### Overview

The 'Mentor Research Project Roadmap' serves as the Epic GitHub issue/ Master document for all aspects pertaining to research of the Mentorship Program. This holds all the initial planning, progress and assets for Mentor Research TWE'22. It also creates a baseline for conceptualization, progress and future assessment. 

### Action Items
- [x]   Use Intern Research as the model for planning Mentor Research
     - Review #187 and identify best practices
     - Review [Guardians Research Plan and Goals](https://github.com/hackforla/internship/wiki/Intern-Research-Plans-and-Goals) and identify best practices
- [x]   [Create roadmap for TWE'22 Mentor Program_Total Mentor Research Overview](https://docs.google.com/document/d/1ywAYj0NMXQy53kVuEOmtVUdvGy51HqT67xak0EJrFXE/edit) (with data collection & data analysis methods discussed and documented) 
- [x] Research participant (Mentor) recruitment: Create and send recruitment surveys https://github.com/hackforla/internship/issues/249
- [x] Formulate Consent Forms for Mentor Research https://github.com/hackforla/internship/issues/245
- [x]  -~Create Research Plan RP8: Mentor Intake Interviews~ [NOT DONE IN 2022]
- [x] Create Research Plan RP13: #244
- [x] Create Research Plan RP14: Create Mentor Exit Interviews
         - Relevant to RP14: #246
         - Relevant to RP14: https://github.com/hackforla/internship/issues/266
- [x] Create Research Plan RP15: Mentor Exit Surveys https://github.com/hackforla/internship/issues/251
- [x] Other research needed
Intern feedback survey (technical skills gained, soft skills, mentorship evaluation, 1 Survey at the end of the program, a feedback form) [Tracked In: #242]
- [x] -~Create Interview Guide for Ethnography/contextual inquiry~ [ON HOLD]

### Resources/Instructions

[Google Drive Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing)
[Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
[Mentor Research Overview](https://github.com/hackforla/internship/wiki/Mentor-Research-Overview)
[Research](https://github.com/hackforla/internship/wiki/Research)
[UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates)

**Comment by Aparna1Gopal** [comment]
**Notes:** 

The tasks have been split up for this short 2-week project for efficiency 

@Aparna1Gopal Currently working on the Research Plan
@bradyse Currently working on the Consent form, Survey Design, Interview Guide

**Comment by lkawentel** [comment]
Is the interview guide for the exit interviews still open? If so, I would be interested in working on that.

**Comment by sniux** [comment]
Sarah & Snig / 24-6
- TWE: [Mentor Survey Draft 90% done. ](https://docs.google.com/document/d/1b8aerTkz2evVezCIuqMUWRrAJHhAcElkk9tU5wwYLfY/edit#)
- Finalized the research plan for the survey

Next up:
- Finalize 'perceived challenges' questions
- Confirm mentor onboarding slides with Bonnie to finish the knowledge items

Blocker:
- Bonnie needs to confirm with the mentors

**Comment by Aparna1Gopal** [comment]
**Notes:** 

**Consent Forms**

Consent Forms for UX Research: A Starter Template
Do you have permission for that? How to write an easy-to-understand informed consent form, plus the template we use at User Interviews.
https://www.userinterviews.com/blog/how-to-write-research-participant-consent-forms?utm_source=autopilotResearcher&utm_medium=email&utm_campaign=FV&utm_content=220

**Comment by bradyse** [comment]
### Notes:
@christine-el  (please fix Wiki)

#### Tasks to Complete, UXRs currently working on:

Research Plan (Aparna G)
**RP12:** Surveys – post onboarding, weekly, transfer from Google .doc to .form (Sara.B, Snigdha)
Consent forms – for mentors & interns to participate in various interviewing activities, audio/video/writing (Angela, Aparna G.)
Other research needed -- could be an asset to **RP13 and RP12**; look at RP6 Informed Consent folder as an example
**RP10 (mentor evaluation):** Intern feedback survey (technical skills gained, soft skills, **mentorship evaluation**, 1 Survey at the end of the program, a feedback form) (Sara B., Snigdha)
**RP13:** Interview Guide – Exit Interview (Linda)
Interview Guide – Ethnography/contextual inquiry (Angela, Aparna G.)

#### To do:

- Reorganize Wiki to reflect new RP numbers @christine-el 
   - RP8 will remain Mentor Intake Interviews @Aparna1Gopal 
   - RP10 is Intern Evaluation of Mentor Survey; see @Rabia2219 and @epierotti3 
   - RP12 is new and will encompass the quantitative mentor intake survey (post-onboarding); @bradyse @sniux 
   - RP13 is new and will be the Mentor Exit Interviews; @lkawentel 
- Create Google Drive folders for new RPs
- Create consent form templates for all mentor research @adarosh 
- Take [Research Plan Notes document](https://docs.google.com/document/d/123ylPvkIlpGyHssOXNpWoxeD2isf3iS6LzYlJ-PKLB4/edit?usp=sharing) and branch this information out into our own RP folders

**Comment by Aparna1Gopal** [comment]
@lkawentel Just an FYI, I have created a new issue for the Interview Guide: Exit Interviews and assigned you. The issue can be found here https://github.com/hackforla/internship/issues/246

(I was cleaning up and streamlining our current above workspace #208). 

Please feel free to make any updates/changes/edits as you work through the Interview Guide: Exit Interviews issue.

**Comment by christine-el** [comment]
I have updated the Wiki page to add all of the new research projects we discussed yesterday here:  https://github.com/hackforla/internship/wiki/Research-Output-Overview.  Please go in and fill out the description of each project you're working on, along the lines of what I've done here:  https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews.  New google drive folders have also been created, so make sure to deposit all assets for each project in the correct file.

**Comment by christine-el** [comment]
I have also created a new label for each research project, so please go ahead and add or change the labels for each of the issues that you have been assigned.

**Comment by christine-el** [comment]
@Aparna1Gopal @bradyse I'm wondering if we should actually create new issues for each new research project, as I think each issue is supposed to only have one feature label.  What do you think?  I'm happy to do this if you agree, although I may need your help.

**Comment by Aparna1Gopal** [comment]
**Notes from Slack**


[To Christine El Ouardani]
 Yes, we did decide to create new issues for each new research project. I did go ahead and create new issues for each project yesterday. As I was cleaning up and streamlining the #208 project workspace. I have also updated each issue with the newly created feature labels, so we are all set. Thanks for creating the labels!

**Comment by Aparna1Gopal** [comment]
**Notes from Slack**

[From: Aparna Gopal, To: Sara Brady] 

Based on our Teams call, the following has been updated:

Details regarding Mentor Intake Interviews (or rather, lack thereof due to time constraints) have been updated in RP8, https://docs.google.com/document/d/1ywAYj0NMXQy53kVuEOmtVUdvGy51HqT67xak0EJrFXE/edit

These details have been updated in the Mentor Intake Interviews’ Wiki, as well https://github.com/hackforla/internship/wiki/Research-Plan-8:-Mentor-Intake-Interviews

I have reviewed all items related to RP8 for naming and language consistency across all our work. I have renamed RP 8 related items to ‘Total Mentor Research Overview’ (which in essence does serve as our Master Document/GitHub issue for all things pertaining to the Mentor program). If you do come across any other sections pertaining to RP 8 that needs renaming, please let me know and I will do the same. Thank You and hope you had a good weekend!

**Comment by bradyse** [comment]
- Restructured epic issue to keep track of all relevant mentor issues.
- Some new issues need to be created as a result.

**Comment by Aparna1Gopal** [comment]
**Notes**

- This RP 008 (#208) serves as the project roadmap. Need to clarify with the PM and UX Lead on the nomenclature for this issue (whether epic or project roadmap or something else). To align with the overall naming and numbering pattern utilized by the PM Team in this project. 
- Comments made in the RP 8 document for RP8 clean-up https://docs.google.com/document/d/1ywAYj0NMXQy53kVuEOmtVUdvGy51HqT67xak0EJrFXE/edit#
- Need to align all aspects of this GitHUB Issue, Research Plan 8 and Wiki. This will be the focus of the Mentor Project focus in the next few weeks in collaboration with the UX Lead.

**Comment by Aparna1Gopal** [comment]
**Notes**

To clean-up this issue for documentation kit the following need to be done

- [ ] Create issue for RP 8 - Mentor Intake interview, and document the reasons for not conducting interview this year 
- [ ] Create label RP 19- To document this above Mentor Research Roadmap 
- [ ] Update the RP 8 label for Mentor Intake Interview 
- [ ] Update RP 19 Label for all relevant issues pertaining to the roadmap, remove RP 8 from these as this was how these relevant issues were previously named
- [ ] Update Wiki for RP 19 and RP 8. Clean-up and follow RP 6 template for updated documentation 
- [ ] Inform the UX Leads and PMs on Slack regarding the changes

**Comment by Aparna1Gopal** [comment]
To clean up this issue and create the complete documentation kit, the following steps have been completed pertaining to this issue: 

- [ ] Cleaned-up Epic Issue: Reworked on naming Action Items with action verbs and direction of research 
- [ ] Cleaned-up Epic Issue: Identifying and tagging all Research Plans (RP labels) related to this Project Roadmap
- [ ] Creating Project Roadmap Wiki
- [ ] Cross-checking all the resources listed on the Project Roadmap Wiki

**Comment by Aparna1Gopal** [comment]
Notes: 

UX Research Minutes of Meetings recorded here: https://github.com/hackforla/internship/issues/62

**Comment by Aparna1Gopal** [comment]
**Notes:** 

Following up after one-on-one meeting with Sara B, UXR Lead on 09/17/2022 
Relevant Resources: 
Research Roadmap Template: https://docs.google.com/document/d/1kUteb9OtMmKFX422HkomiJr6JkSU4XNBlauw4_EqjBY/edit

**Comment by bradyse** [comment]
@priyatalwar 
This issue has been checked. For future, do not use this template for any future issue creation. Use this [roadmap issue template](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research%2C+feature%3A+roadmap%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+0.50pt&template=research--roadmap.md&title=TWE%3A+Research+Roadmap+%5Bname+of+type%5D) instead.
