### ISSUE TITLE
TWE: Create Agenda for Day 1 of Intern Onboarding

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#211]
### Overview
We need to create an agenda for the first day of onboarding so that we can have a smooth and complete onboarding.

### Action Items

- [x] Create a list of activities for the first day
   - Presentation
     - Include Code of Conduct Overview
   - Icebreaker activities
   - Intake Interview
   - Schedule, project and duty overview
   - Intern Self Onboarding
   - Q&A
- [x] Create the following issues for Day 1 activities:
    ~- [ ] #191~
    - [x] #193
    ~- [ ] #196~
    - [x] #198
    - [x] #203
    - [x] #204 
~- [ ] Setup Easy Retro for Q&A~
- [x] Set up Day 2 expectations
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [TWE: Onboarding IS22 - Deck](https://docs.google.com/presentation/d/13tSA70FfojhQgiFoeKM5po29hOdH31wTROs1Ec2M4b8/edit#slide=id.p)
- [Day 1 activities spreadsheet](https://docs.google.com/spreadsheets/d/1GTA7ULcliiQY7NvI199i6r8XrqC3CN-Sm98UWzP3ZA4/edit#gid=1907978168)
- [HfLA Resume Builder Tool](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=1559833848)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Rabia2219** [comment]
### Pre internship
- setup lettucemeet.com and email messaging to ask them to fill out so that we can schedule items such as linkedin workshop and mentorship

### Prior to the internship
- Send them the code of conduct and ask for them to send back passphrase or password
- Create linkedin coaching workshop and train the mentors
- rename all intern folders starting with TWE:
- tutorial for accessing folder
- clean up the linkedin deck by holding internal workshops to define how much we could accomplish in a hour.
- explore raising money to pay Robeus and laptop
- get UX research plan done for doing intake interviews. [Research Plan 6: Onboarding Interns](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Onboarding-Interns)
- design an activity design (icebreakers in breakout rooms) with multiple choice activities
- design a recruitment strategy for mentors
  - recruit and assign mentors 1.5 hours per week commitment
- setup of new repo and move all the old issue for last cohort interns to that repo
- time card setup solution
- Build a tracking tool/Checklist for all interns for non work related accomplishments

**Comment by Rabia2219** [comment]
Students are guided through a day of Intake interviews to create baselines, Meet and Greet with the other interns, Overview about schedules, Code of Conduct , Introduction to Team members who will provide guidance, scheduling of negotiable meetings, Technical onboarding (GitHub, Google Docs, Slack, Roster), etc. and creating their first two issues.

Day 1
- show them how to access their folders on the first day
- do a LinkedIn workshop on the first day
  - setting up a linked profile
  - making a copy of the Resume Content Building Tool
- interviews
- meet and greet (includes icebreakers)
- meet mentor
- Overview about schedules
- negotiation of specific meeting (lettucemeet.com)
- Code of Conduct
- Team members who will provide guidance
- Technical onboarding (GitHub, Google Docs, Slack, Roster) to project team 
- creating their first two issues on intern repo (linkedin, checkllist)
- Time card spreadsheet introduction

Day 2
- developers creating prework issue on project repo

**Comment by bradyse** [comment]
Hi @Rabia2219 I added the link of the Resume Content Building Tool to the resources and your comment.

**Comment by Rabia2219** [comment]
Updated https://github.com/hackforla/internship/wiki/The-2022-Internship-Program-Process-Overview/_edit with onboarding deck and day 1 activities spreadsheet.
