### ISSUE TITLE
TWE: Create a IS22 LinkedIn Profile Checklist Template

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#214]
### Overview

We have to create a LinkedIn profile template for the IS22 cohort so that they can create their individual checklist.

### Action Items 

- [x] Define what needs to go in the LinkedIn Profile Checklist below
- [x] Copy the items and paste into the template
- [x] Create a template
- [x] Update relevant WIKI page (See resources)

#### TWE: IS22 LinkedIn Profile Checklist Template
```
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items

- [ ] Signup for a LinkedIn account if you don't already have one
- [ ] Customize your URL
   - Make sure you get rid of the numbers.
   - A good format is: firstnamelastname, lastname-firstname firstnameMiddleInitialLastname
- [ ] Create your copy of the Resume Content Builder (linked in Resources at the bottom) which will help you fill out the Experience section on your LinkedIn Profile
-[ ] Work on the individual sections on your profile and check off as you make progress
 - [ ] Top
   - [ ] Name
   - [ ] Photo
   - [ ] Title
   - [ ] Organization
   - [ ] City
   - [ ] Email
 - [ ] About
   - [ ] Description
   - [ ] List of skills
 - [ ] Featured
   - [ ] Two articles or an article and a portfolio
- [ ] Activity
   - [ ] Comments 
   - [ ] Posts
- [ ] Experience
   - [ ] Hack for LA
      - [ ] Review your copy of the Resume Content Builder with Bonnie
      - [ ] Post to Linkedin
- [ ] Education
   - [ ] List of schools attended
- [ ] Skills and Endorsements
   - [ ] List your skills 
   - [ ] Give your team members endorsements when they help you with one of the skills
- [ ] Recommendations
   - [ ] Ask for recommendations
   - [ ] Review submitted recommendations
   - [ ] Accept recommendations 
- [ ]  Accomplishments
    - [ ] Items that don't fit anywhere else (old, or outside of experience you want to list)
- [ ] Interests
   - [ ] add three

### Resources
[Linkedin](https://www.linkedin.com)
[TWE: Linkedin Profile Workshop Deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Resume Content Builder](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=0)
```
### Resources/Instructions
- [IS21 LinkedIn profile checklist](https://github.com/hackforla/internship/issues/16)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
