### ISSUE TITLE
Create label and milestone schema

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#23]
### Overview
We need to create labels and milestones so that we can see where we are progress wise and prioritize according to the roadmap that we will build

### Action Items

- [ ] Identify all the unique areas for features
   - [x] specify feature labels
      - [x] get sign off
         - [ ] apply feature labels to issues
- [x] Determine what requires a milestone (delivery date) vs a label (ongoing)
- [x] add size labels (1,2,3,5,8,13+)
- [x] add missing labels 
   - [x] size: missing
   - [x] feature: missing
   - [x] role: missing
- [x] apply the missing labels to all issues that are missing them
   - [x] size: missing
   - [x] feature: missing
   - [x] role: missing
- [x] Add a link under Resources, Links for checking to make sure that all issues either have a ___ or a ____ missing label for feature
   - [x] size
   - [x] feature
   - [x] role
- [ ] Add all the milestones to the issues #73 

### Resources/Instructions
Label Tab ([Where we create/update/delete and read all the labels](https://github.com/hackforla/internship/labels))
#### Existing Labels (at start of issue)
feature: 
wiki
stats
linkedin profile
branding

#### Unique Areas
GitHub/Project Admin

#### Milestones needed

[roadmap ](https://docs.google.com/spreadsheets/d/1GijHiK_DRmlU8U0fZKsV9cjYhy9h3pZ5_OYQVx_mbgo/edit#gid=1055226176)

#### All issues with Missing labels
[Role](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+missing%22)
[size](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+label%3A%22size%3A+missing%22)
[feature](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+missing%22)
[milestone](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)

#### Links for checking to make sure that all issues either have a ___ or a ____ missing label
[Role](https://github.com/hackforla/internship/issues?q=is%3Aissue+-label%3A%22role%3A+UI%2FUX+research%22+-label%3A%22role%3A+UI%2FUX+design%22+-label%3A%22role%3A+Product%22+-label%3A%22role%3A+Org+Rep%22+-label%3A%22role%3A+missing%22+-label%3A%22role%3A+data+scientist%22+-label%3A%22role%3A+intern%22+is%3Aopen)
[size](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+missing%22+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+2pt%22+-label%3A%22size%3A+3pt%22+-label%3A%22size%3A+5pt%22+-label%3A%22size%3A+8pt%22+-label%3A%22size%3A+13%2Bpt%22)
[feature](https://github.com/hackforla/internship/issues?q=is%3Aissue+-label%3A%22feature%3A+agenda%22+-label%3A%22feature%3A+calendar%22+-label%3A%22feature%3A+branding%22+-label%3A%22feature%3A+board+cleanup%22+-label%3A%22feature%3A+compliance%22+-label%3A%22feature%3A+deck%22+-label%3A%22feature%3A+C%26C+Analysis%22+-label%3A%22feature%3A+evangelize%22+-label%3A%22feature%3A+guide%22+-label%3A%22feature%3A+general+FAQ%22+-label%3A%22feature%3A+HfLA+volunteer+interviews%22+-label%3A%22feature%3A+hypothesis%22+-label%3A%22feature%3A+IS21%3A+Cohort+Analysis%22+-label%3A%22feature%3A+logo%22+-label%3A%22feature%3A+marketing+communication%22+-label%3A%22feature%3A+IS21+Cohort+Interviews%22+-label%3A%22feature%3A+marketing+plan%22+-label%3A%22feature%3A+marketing%22+-label%3A%22feature%3A+metrics%22+-label%3A%22feature%3A+missing%22+-label%3A%22feature%3A+one+sheet%22+-label%3A%22feature%3A+overview%22+-label%3A%22feature%3A+partner+communication%22+-label%3A%22feature%3A+partner+tracking%22+-label%3A%22feature%3A+presentation+templates%22+-label%3A%22feature%3A+project+FAQ%22+-label%3A%22feature%3A+project+listing%22+-label%3A%22feature%3A+recruitment%22+-label%3A%22feature%3A+research+plan%22+-label%3A%22feature%3A+roadmap%22+-label%3A%22feature%3A+stats%22+-label%3A%22feature%3A+test%22+-label%3A%22feature%3A+website%22+-label%3A%22feature%3A+wiki%22+-label%3A%22p-feature%3A+credits+page%22+-label%3A%22p-feature%3A+Linkedin+profile%22+-label%3A%22p-feature%3A+privacy+policy%22+-label%3A%22feaure%3A+HfLA+volunteer+analysis%22+-label%3A%22feature%3A+arrange+for+speaking+opportunities%22+-label%3A%22feature%3A+board+%2F+google+drive+%2F+tools%22+-label%3A%22feature%3A+find+speaking+opportunities%22+-label%3A%22feature%3A+HfLA%3A+presentation%22+-label%3A%22feature%3A+HfLA%3A+research+plan%22+-label%3A%22feature%3A+HfLA%3A+research+training%22+-label%3A%22feature%3A+HfLA%3A+volunteer+analysis%22+-label%3A%22feature%3A+HfLA%3A+volunteer+interviews%22+-label%3A%22feature%3A+HfLA%3A+volunteer+personas%22+-label%3A%22feature%3A+hypothesis+test%22+-label%3A%22feature%3A+IS21%3A+cohort+analysis%22+-label%3A%22feature%3A+IS21%3A+cohort+interviews%22+-label%3A%22feature%3A+IS21%3A+intern+personas%22+-label%3A%22feature%3A+IS21%3A+presentation%22+-label%3A%22feature%3A+onboarding%22+-label%3A%22feature%3A+IS21%3A+research+plan%22+-label%3A%22feature%3A+project+deck%22+-label%3A%22p-feature%3A+mentorship+guide%22+-label%3A%22p-feature%3A+networking+guide%22)

#### Any issues that have not yet been added to project board
[project board](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)

**Comment by ExperimentsInHonesty** [comment]
Audit on 2021-11-08
Role: 10/2
size: 0/0
feature: 29/12

**Comment by ExperimentsInHonesty** [comment]
added a label called epic for issues that are too big and need to be broken down

**Comment by Rabia2219** [comment]
Finished creating all labels finalized thus far in the roadmap on Nov 11 21.

**Comment by Rabia2219** [comment]
Audit Nov 14 21

size, starting at 15/8
features, starting at 10/6
role, starting at 1/1
milestone, starting at 0/0
Project missing, starting at 0

size, ending at 15/5
features, ending at 9/5
role, ending at 1/0
milestone, ending at 0/0
Project missing, ending at 0

**Comment by Rabia2219** [comment]
Can we add feature: compliance or feature: epic to [this issue](https://github.com/hackforla/internship/issues/69) OR create a new label called **feature: audit** as we have another issue for audit and may do more audits in the future?
Can we rename [this issue](https://github.com/hackforla/internship/issues/65) to Audit of Intern Exit Process? then we can use the feature: audit label here as well...

**Comment by priyatalwar** [comment]
Can we assign the "feature: strategy" label to this issue[RACI](https://github.com/hackforla/internship/issues/55#issue-998377776)

**Comment by Rabia2219** [comment]
What is meant by Project Missing? What is project board here:

All issues with Missing labels
Role
size
feature
milestone
project board

we do not have any label called project board...

**Comment by ExperimentsInHonesty** [comment]
Answer to 

> What is meant by Project Missing? What is project board here:
> 
> All issues with Missing labels
> Role
> size
> feature
> milestone
> project board
> 
> we do not have any label called project board...

When you click on project board link the number should be zero because each issue should be on the project board.  Its a check to see if any projects have not been added. The filter is ```no:project```

**Comment by ExperimentsInHonesty** [comment]
2021-11-15
size, ending at 15/5
features, ending at 9/5
role, ending at 1/0
milestone, ending at 0/0
Project missing, ending at 0

**Comment by ExperimentsInHonesty** [comment]
2021-11-18
size, ending at 12/5
features, ending at 6/5
role, ending at 1/0
milestone, ending at 0/0
Project missing, ending at 0

**Comment by ExperimentsInHonesty** [comment]
2021-11-29
size, ending at 12/5
features, ending at 6/5
role, ending at 1/0
milestone, ending at 0/0
Project missing, ending at 0
