### ISSUE TITLE
TWE: IS22 LinkedIn Profile Checklist Brian

### ISSUE THREAD

**Issue by BCHEN222** [hackforla/internship#232]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items
- [x] Signup for a LinkedIn account if you don't already have one
- [x] Customize your URL
   - Make sure you get rid of the numbers.
   - A good format is: firstnamelastname, lastname-firstname firstnameMiddleInitialLastname
- [x] Create your copy of the Resume Content Builder (linked in Resources at the bottom) which will help you fill out the 
Experience section on your LinkedIn Profile
- [ ] Work on the individual sections on your profile and check off as you make progress
   - [ ] Top
      - [x] Name
      - [ ] Photo
      - [x] Title
      - [x] Organization
      - [x] City
      - [x] Email
   - [x] About
      - [x] Description
      - [ ] List of skills
   - [x] Featured
       - [x] Two articles or an article and a portfolio
   - [ ] Activity
      - [ ] Comments 
      - [ ] Posts
  - [ ] Experience
     - [x] Hack for LA
        - [x] Review your copy of the Resume Content Builder with Bonnie
        - [x] Post to Linkedin
  - [x] Education
     - [x] List of schools attended
  - [ ] Skills and Endorsements
     - [ ] List your skills 
     - [ ] Give your team members endorsements when they help you with one of the skills
  - [ ] Recommendations
     - [ ] Ask for recommendations
     - [ ] Review submitted recommendations
     - [ ] Accept recommendations 
  - [ ]  Accomplishments
     - [ ] Items that don't fit anywhere else (old, or outside of experience you want to list)
  - [ ] Interests
     - [ ] add three

### Resources
[Linkedin](https://www.linkedin.com/in/brianchenla/)
[TWE: Linkedin Profile Workshop Deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Resume Content Builder](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=0)
[Brian Chen Resume Content Builder](https://docs.google.com/spreadsheets/d/1pRrag7jyS3dvjxXkQj1jT5uhUg5GZRLYMgmFdpDEaDo/edit#gid=1869629152)
https://www.linkedin-makeover.com/linkedin-text-formatter/
https://fsymbols.com/signs/bullet-point/

**Comment by BCHEN222** [comment]
Semi-blocker 

- [ ] take photo and upload to profile

**Comment by BCHEN222** [comment]
**DRAFT** 

Project manager with background in entreprenuerial team settings, familiar with team work environments and leadership. My interests are geared towards business development in food and tech, but looking for holistic development in a plethora of industries. I am a hard worker as well as a team player; my leadership experience has taught me that success is built on all team members contributing their equally valuable efforts and professionalism.

**Comment by BCHEN222** [comment]
**BLOCKERS**
below are most likely items to be covered in following workshops, timeframe leniency as of 6/21/22

"**Featured**" Section 

- [ ] guidance from bonnie
- [ ] write articles to showcase critical thinking skills and communication
- [ ] link to portfolio?

"**Activities**" Section
This section and below delegated to later workshops*

**Comment by ExperimentsInHonesty** [comment]
remaining
- add HfLA info to the linkedin profile
- add skills
- getting endorsements
- Getting a letter of recommendation added to your profile (desired)
