### ISSUE TITLE
TWE: IS22 LinkedIn Profile Checklist Charity

### ISSUE THREAD

**Issue by CharityLai6** [hackforla/internship#233]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items
- [x] Signup for a LinkedIn account if you don't already have one
- [x] Customize your URL
   - Make sure you get rid of the numbers.
   - A good format is: firstnamelastname, lastname-firstname firstnameMiddleInitialLastname
- [x] Create your copy of the Resume Content Builder (linked in Resources at the bottom) which will help you fill out the 
Experience section on your LinkedIn Profile
- [ ] Work on the individual sections on your profile and check off as you make progress
   - [x] Top
      - [x] Name
      - [x] Photo
      - [x] Title
      - [x] Organization
      - [x] City
      - [x] Email
   - [x] About
      - [x] Description
      - [ ] List of skills
   - [ ] Featured
       - [ ] Two articles or an article and a portfolio
   - [ ] Activity
      - [ ] Comments 
      - [ ] Posts
  - [x] Experience
     - [x] Hack for LA
        - [x] Review your copy of the Resume Content Builder with Bonnie
        - [x] Post to Linkedin
  - [x] Education
     - [x] List of schools attended
  - [ ] Skills and Endorsements
     - [ ] List your skills 
     - [ ] Give your team members endorsements when they help you with one of the skills
  - [ ] Recommendations
     - [ ] Ask for recommendations
     - [ ] Review submitted recommendations
     - [ ] Accept recommendations 
  - [ ]  Accomplishments
     - [ ] Items that don't fit anywhere else (old, or outside of experience you want to list)
  - [ ] Interests
     - [ ] add three

### Resources

- [LinkedIn](https://www.linkedin.com)
- [TWE: Linkedin Profile Workshop Deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
- [Resume Content Builder](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=0)
- [LinkedIn text formatter](https://www.linkedin-makeover.com/linkedin-text-formatter/)
- [Bullet point symbols](https://fsymbols.com/signs/bullet-point/)

### Personal links

- [Charity's Linkedin Profile](https://www.linkedin.com/in/charitylai/)
- [Charity - Resume Content Builder](https://docs.google.com/spreadsheets/d/1rFpeVv5skj_Y0RGH5ttefeZgbqjTHSJnLhcBhCjwylU/edit#gid=1869629152)

**Comment by ExperimentsInHonesty** [comment]
remaining

- add remainder of HfLA info to the linkedin profile
- getting endorsements
- Adding something to the feature and/or activity section (optional) - a link to the video
- Getting a letter of recommendation added to your profile (desired)

**Comment by CharityLai6** [comment]
PM skills (check with Bonnie):
- communication
- time management
- collaboration/teamwork
- organization
- project planning
- 

Featured section:
- ["How to move files you have created" video](https://vimeo.com/734256976)

**Comment by ExperimentsInHonesty** [comment]
instructional design
testing
