### ISSUE TITLE
TWE: IS22 LinkedIn Profile Checklist Riya

### ISSUE THREAD

**Issue by raswani2023** [hackforla/internship#236]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items
- [x] Signup for a LinkedIn account if you don't already have one
- [x] Customize your URL
   - Make sure you get rid of the numbers.
   - A good format is: firstnamelastname, lastname-firstname firstnameMiddleInitialLastname
- [x] Create your copy of the Resume Content Builder (linked in Resources at the bottom) which will help you fill out the 
Experience section on your LinkedIn Profile
- [ ] Work on the individual sections on your profile and check off as you make progress
   - [x] Top
      - [x] Name
      - [x] Photo
      - [x] Title
      - [x] Organization
      - [x] City
      - [x] Email
   - [x] About
      - [x] Description
      - [x] List of skills
   - [ ] Featured
       - [ ] Two articles or an article and a portfolio
   - [ ] Activity
      - [ ] Comments 
      - [ ] Posts
  - [ ] Experience
     - [ ] Hack for LA
        - [x] Review your copy of the Resume Content Builder with Bonnie
        - [ ] Post to Linkedin
  - [x] Education
     - [x] List of schools attended
  - [ ] Skills and Endorsements
     - [x] List your skills 
     - [ ] Give your team members endorsements when they help you with one of the skills
  - [ ] Recommendations
     - [ ] Ask for recommendations
     - [ ] Review submitted recommendations
     - [ ] Accept recommendations 
  - [x]  Accomplishments
     - [x] Items that don't fit anywhere else (old, or outside of experience you want to list)
  - [x] Interests
     - [x] add three

### Resources
[Linkedin](https://www.linkedin.com)
[TWE: Linkedin Profile Workshop Deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Resume Content Builder](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=0)
[Riya: Resume content builder](https://docs.google.com/spreadsheets/d/1nMo3XiJnZm3HM3Pv_x5t3--soV96Xy1mNb54iJcY88w/edit#gid=1869629152)
[Riya LinkedIn Account](https://www.linkedin.com/in/riya-aswani/)
[LinkedIn Text Formatter](https://www.linkedin-makeover.com/linkedin-text-formatter/)
[Bullet points](https://fsymbols.com/signs/bullet-point/)

**Comment by raswani2023** [comment]
Here is my resume content builder: https://docs.google.com/spreadsheets/d/1OUshgI4g2KdQhULUWIT732VrhlqqYdX-PRt3S2GRRvI/edit?usp=sharing

**Comment by raswani2023** [comment]
Resume content building tool: https://docs.google.com/spreadsheets/d/1nMo3XiJnZm3HM3Pv_x5t3--soV96Xy1mNb54iJcY88w/edit#gid=1869629152

**Comment by ExperimentsInHonesty** [comment]
remaining
- add HfLA info to the linkedin profile
- getting endorsements
- Adding something to the feature and/or activity section (optional)
- Getting a letter of recommendation added to your profile (desired)
