### ISSUE TITLE
LinkedIn Setup Checklist: Jack

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#24]
# Schedule Interview with Jack

### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items
Check off each of the items as you complete it, adding the content of what you wrote under the item.

#### Top
- [x] Name
- [x] Photo
- [x] Title
- [x] Organization
- [x] City
- [x] Email

#### Customize your url
- [x] Make sure you get rid of the numbers, generally firstnamelastname, lastname-firstname firstnameMiddleInitialLastname, etc.

#### About
- [x] Description
- [x] List of skills

#### Featured
- [ ] Two articles or an article and a portfolio

#### Activity
- [ ] Comments 
- [ ] Posts

#### Experience
- [ ] Hack for LA
   - [ ] Fill out [spreadsheet](https://docs.google.com/spreadsheets/d/1VPdR7u110TVE--AjK2F8lKo115j7O59oeyEBYnq1ibM/edit?usp=sharing)
   - [ ] Meet with Bonnie and revise wording
   - [ ] Post to Linkedin

#### Education
- [ ] List of schools attended and any relevant classes or clubs or honors

#### Skills and Endorsements
- [ ] List your skills 
- [ ] Give your team members endorsements when they help you with one of the skills

#### Recommendations
- [ ] Ask for recommendations
- [ ] Review submitted recommendations
- [ ] Accept recommendations

#### Accomplishments
- [ ] Items that don't fit anywhere else (old, or outside of experience you want to list)

#### Interests
- [x] add three

### Resources/Instructions
[Linkedin](https://www.linkedin.com)
[Linkedin deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
https://www.linkedin.com/in/jack-richman/
[Resume content tool](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=1559833848)
[Jack Richman Linkedin Profile](https://www.linkedin.com/in/jack-richman/)
[Sakari's Activity Log example](https://docs.google.com/spreadsheets/d/1SMNhL34zfCsIWOnHZ2hXjXLL7ZfX54LXSglkGZb-Xms/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
I am curious coder who enjoys competitive problem solving (USACO) and taking on new challenges in computer science.  In my spare time, I am a volunteer as a teacher of Scratch and Python to elementary school students and am a  close up magician and junior member of the Academy of Magical Arts in Hollywood.

Skills: Java, Git, Github, Python, Scratch, Javascript, HTML, CSS, R

**Comment by ExperimentsInHonesty** [comment]
- [ ] make a copy of the [Resume content tool](https://docs.google.com/spreadsheets/d/164RGPJK3b5IdmWhici-d8Qss1_PvGPL5gwsEHujxTfQ/edit#gid=1559833848)
- [ ] add bonnie as an editor bonnie@hackforla.org
- [ ] add link from your copy to the issue comment above

**Comment by ExperimentsInHonesty** [comment]
@JackRichman

I recommend adding some more interests.  Think of three orgs that you might want to follow professionally, and let me know next time we meet, so that I can show you how to add them as interests to your linkedin if you have forgotten how.


 It looks like you are still missing some endorsements (at the least you should get one for github)
 I recommend the following additional steps
- [ ] Go into the Hack for LA team roster and connect with each person who did a pr review or issue completed for you
- [ ] Once they have accepted your linkedin request, go to their profile and endorse them for the skills that your issue required.  So if your issue was a Figma issue, then endorse them for that, etc.
- [ ] Then wait a few days, and write to them asking them if they would consider endorsing you for that skill and reminding them of the pr or issue (including putting a link to the item). 
#### Note: you only NEED one endorsement per skill to make it show up when recruiters are searching for you.  But you do need at least one.

Snapshot of current
![image](https://user-images.githubusercontent.com/37763229/131389724-5f314922-b4fa-469b-ad95-ed1d93f7fd5a.png)

**Comment by ExperimentsInHonesty** [comment]
Connected to the following people from the hack for LA team Blakely, Joseph, Matthew, Andrew, Christopher, Adam
Here is the [roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) so that you can connect to anyone who reviewed any of your pull requests or you otherwise had positive contact with.

Has not connected with Ava, Alyssa yet.  Ava's linkedin is not yet on the roster.

**Comment by ExperimentsInHonesty** [comment]
@JackRichman just a quick follow-up to suggest for final steps for you in your networking

Internship team assessment: Jack is connected to the following people from the hack for LA team Blakely, Joseph, Matthew, Andrew, Christopher, Adam.  Has not connected with Ava, Alyssa yet.

Here is the [roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0) so that you can connect to anyone who reviewed any of your pull requests or you otherwise had positive contact with.
