### ISSUE TITLE
LinkedIn Setup Checklist: Bennett

### ISSUE THREAD

**Issue by Zytko** [hackforla/internship#25]
### Overview
I want to have a professional presence and have a space to network and connect with others in order to achieve my career goals.

### Action Items
Check off each of the items as you complete it, adding the content of what you wrote under the item.

#### Top

- [ ] Name
- [ ] Photo
- [ ] Title
- [ ] Organization
- [ ] City
- [ ] Email

#### About

- [ ] Description
- [ ] List of skills

#### Featured

- [ ] Two articles or portfolios

#### Activity

- [ ] 

#### Experience

- [ ] 

#### Education

- [ ] List of schools attended

#### Skills and Endorsements

- [ ] 

#### Recommendations

- [ ] 

#### Accomplishments

- [ ] 

#### Interests

- [ ] 

### Resources/Instructions

[Linkedin](https://www.linkedin.com)
[Linkedin deck](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.ge117c703c6_0_35)
[Linkedin Page](https://www.linkedin.com/in/bennettzytko/)

**Comment by ExperimentsInHonesty** [comment]
Add these items under the bio in the about
Skills: 
Business Plan Development
Competitive Analysis
Market Research
Customer Acquisition and Growth Plan
Investor Pitching
Digital Product Mockup
Educational Tool Development

Skills
TinkerCAD

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty to write recommendation draft (dependency on #5 #40 )

**Comment by ExperimentsInHonesty** [comment]
@bennet I recommend  the following additional steps
- [ ] If  you have professional connections with people who could give you endorsements for the skills you are missing endorsements for connect with them.
- [ ] Once they have accepted your linkedin request, go to their profile and endorse them for the skill that you know they are competent in.
- [ ] Then wait a few days, and write to them asking them if they would consider endorsing you for that skill 
#### Note: you only NEED one endorsement per skill to make it show up when recruiters are searching for you.  But you do need at least one.

Snapshot of current
![image](https://user-images.githubusercontent.com/37763229/131390352-fea77fa5-5397-4b1d-8e70-4be6ed3b2bad.png)
