### ISSUE TITLE
IS22: Make Intern Exit Interviews Issues

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#263]
### Overview
We need to create an issue for each person we are interviewing to make sure we get all the steps uniform

### Action Items

- [ ] Create an issue for each interview
- [x] After interviews occur, confirm recordings are saved on Google Drive
- [x] Email interviewers to confirm recordings are deleted.
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
- [Intern Onboarding Interview Issue](https://github.com/hackforla/internship/issues/142)
- [Onboarding Interview Session Table](https://docs.google.com/spreadsheets/d/11agqyxXr-sD_nCbUQJoh49NACqr9GiThd25lGe6ajQw/edit#gid=0)
- [Interview Submission Form](https://docs.google.com/forms/d/e/1FAIpQLSfZ-SJAPQQECS_fH3AhDydAc06OpXu6JwjHfSuH6mpupiKb6A/viewform)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

#### Intern interview issues
- #274

**Comment by bradyse** [comment]
@christine-el I wasn't sure where to put the documentation that I emailed the interviewers to delete the recordings. So I put it in here. Perhaps when things settle down you can update this issue, as well as the issues that were created from this one.

**Comment by christine-el** [comment]
@bradyse I think this is the right place!  I never created these issues because I ran out of time (except for 1:  https://github.com/hackforla/internship/issues/274).  Is it worth it to recreate them now to have a record of each one?

**Comment by bradyse** [comment]
This issue is being closed because it was rewritten into: 
- #319
