### ISSUE TITLE
Schedule and Conduct Mentor Exit Interviews

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#265]
### Overview
We need to schedule and conduct mentor exit interviews in order to collect the final wave of data for this project.  

### Action Items
- [x] Contact mentors to figure out when their availability for a 30-60 minute interview to be conducted this week (between July 25-29, although we could probably do it next week, too, if that's easier for them).
- [x] Match each mentor to an interviewer, based on their responses to the Exit Interview UXR availability survey.
- [x] Using the Exit Interviews Instructions below as a template, create instructions for the researchers to use for these interviews and send the instructions and a copy of the questions to each interviewer.  
- [x] Send interview instructions and a copy of the google survey to researchers ahead of the interview.
- [x] #267
- [x] Assign issues to interviewers.  
- [x] Fill out the interview session form, including the pre-filled Google links.  
- [x] After interviews happen, confirm recordings are saved on Google Drive
- [x] Email interviewers to delete recordings
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [Summer 2022 UXR Interest Form Exit Interviews](https://docs.google.com/forms/d/1eUe5QbqNom2JxWPt5kLFOS8b7ZjmqVh7rXaRuHsuDMw/edit)
- [Interview Submission Form](https://docs.google.com/forms/d/e/1FAIpQLSfZ-SJAPQQECS_fH3AhDydAc06OpXu6JwjHfSuH6mpupiKb6A/viewform)
- [Onboarding Intake Interview Session Table](https://docs.google.com/spreadsheets/d/11agqyxXr-sD_nCbUQJoh49NACqr9GiThd25lGe6ajQw/edit#gid=0)
- [RP12: UXR Intern Exit Interviews Instructions](https://docs.google.com/document/d/1X1cAQt-7-EHeWpdNj4ZDT46d3hQ2OpOM6bSdP91R25w/edit#)
- [Copy of the Interview Guide](https://docs.google.com/document/d/14oTKedGpwAHo-UWFiaCkHY1i-BohQsbu1eoKo1qMHMA/edit)
- [Example of How to Create Issues for Each Mentor](https://github.com/hackforla/internship/issues/142)
- [Mentor Contact Info](https://docs.google.com/spreadsheets/d/11odk4Gti8TYPJbuSdpsQd0JvvYitSODMZBD-oOj9mHY/edit?usp=sharing)
- [Mentor Exit Interview Session and Roll Call](https://docs.google.com/spreadsheets/d/1CTAOQirQsoh5XWgAo0IN3Nd45TNXC-Ox3xqMWMX1j30/edit)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by bradyse** [comment]
**2022.07.23**
- Slacked messaged 4 mentors
- Created and edited epic issued modeled after #142

**Comment by bradyse** [comment]
Hi @epierotti3 can we close this issue? I'm not sure if it's labeled properly given the new milestones.
