### ISSUE TITLE
IS22 Mentor Exit Interviews: Make Issues

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#267]
### Dependency
 We need to schedule Mentor Exit Interviews first, see #265

### Overview
We need to create an issue for each person we are interviewing to make sure we get all the steps uniform

### Action Items
- [x] Create an issue for each interview
   - [x] #268
   - [x] #269
   - [x] #270
   - [x] #272
- [x] Add this info to interviewer spreadsheet

### Resources/Instructions
For **INTERN** example of this issue, see [IS22 Interviews: make issues #142](https://github.com/hackforla/internship/issues/142) 
```
### Overview
We need to track the interview for Mentor # [Number] so that we don't drop the ball or lose data about it.

### Action Items
- [ ] Go to 1Password
  - [ ] open zoom spreadsheet
    - [ ] add time of interview and find a zoom room account that is free (zoom1-4)
- [ ] Go to the Zoom Account that you found to be free
  - [ ] Create a non recurring 1 hour meeting for that time
- [ ] Add the zoom link (from the meeting you just created) to this issue
- [ ] Add date and time to resources
- [ ] Add people (Panel to the invite) 
- [ ] Recruit a UX researcher to attend the interview 
- [ ] Add them to the invite
- [ ] Create folder for interview recording

#### Interview checklist
- [ ] 5 min prior, login to 1password and get hostkey for Zoom [Zoom meeting room#]
- [ ] Join the meeting via the calendar link in your invite or here in this issue
- [ ] Claim host
- [ ] Turn on recording and then pause
- [ ] When they enter room, ask if we can record and transcribe
- [ ] Turn on transcript, unpause recording
- [ ] Use script in interview
- [ ] upload recording and transcript and a chat file if applicable to the mentor recording folder

### Resources/Instructions
#### Interview Recordings
  - General Folder for [mentor recordings](https://drive.google.com/drive/folders/1PyxK1lb6T3qZuU_mzYkRkhTb9Zqwr1os?usp=sharing)
  - [Mentor recording folder]()

#### Interview details
- Zoom link for interview
- Date and time for interview:

#### Other links
- [Mentor Roster](https://docs.google.com/spreadsheets/d/11odk4Gti8TYPJbuSdpsQd0JvvYitSODMZBD-oOj9mHY/edit#gid=627393811)
- #266

#### Text once you are ready to send invite update
We have added the zoom invite info and the panelist for your interview.  Looking forward to seeing you! 

```
- [Mentor Roster](https://docs.google.com/spreadsheets/d/11odk4Gti8TYPJbuSdpsQd0JvvYitSODMZBD-oOj9mHY/edit#gid=627393811)
- [Interviewer Spreadsheet](https://docs.google.com/spreadsheets/d/1CTAOQirQsoh5XWgAo0IN3Nd45TNXC-Ox3xqMWMX1j30/edit#gid=1585831764)

**Comment by bradyse** [comment]
@epierotti3, can we close this issue? I don't know if it's labeled properly.
