### ISSUE TITLE
Intern off-boarding status tracker

### ISSUE THREAD

**Issue by epierotti3** [hackforla/internship#275]
### Dependencies
- #261 

### Overview
For interns who are leaving HfLA, we need to keep track of their off-boarding activities to make sure nothing falls through the cracks.

### Action Items
- [x] Create off-boarding template (see comment below)
- [x] Make a copy of the template for each intern who is leaving after the internship, based on [off-boarding form responses](https://docs.google.com/spreadsheets/d/1-VC8lmBpYVjsl--ZK1YuHWIDIceFbwhuaxYPldM7DeI?resourcekey=&usp=forms_web_b#gid=958870979)
- [x] Actively update items from each intern's off-boarding as items are checked off
- [x] Update relevant WIKI page (See resources)

### Resources/Instructions
- [off-boarding form responses](https://docs.google.com/spreadsheets/d/1-VC8lmBpYVjsl--ZK1YuHWIDIceFbwhuaxYPldM7DeI?resourcekey=&usp=forms_web_b#gid=958870979)
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

```
### [INTERN NAME] Off-Boarding 

#### Status (from off-boarding form)
- 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

#### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

#### Issues
- [ ] Check that current issues are closed or annotated/unassigned
```

**Comment by epierotti3** [comment]
### Beckett Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

**Comment by epierotti3** [comment]
### Sakari Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

**Comment by epierotti3** [comment]
### Lily Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

**Comment by epierotti3** [comment]
### Charity Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

**Comment by epierotti3** [comment]
### Clayton Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

**Comment by epierotti3** [comment]
### Tung Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

**Comment by epierotti3** [comment]
### Asher Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)

**Comment by epierotti3** [comment]
### Mateo Off-Boarding 

#### Meetings
Remove calendar invites from:
- [ ] Standup (automatically)
- [ ] All Team Meetings (if applicable)
- [ ] LinkedIn Workshop (automatically)
- [ ] CoPs (if applicable)

#### Figma
- [ ] Change to view-only access

#### Exit Internview
- [ ] Scheduled
- [ ] Recording uploaded to this [folder](https://drive.google.com/drive/folders/1VQLpKVRhFpPYoTSvjMhtly8X9NkZp8mmrhmtDCnhFOR1CCRL-YmCB95xcH6bZ21HO_Nq7gcr)

### LinkedIn
- [ ] Calendar invite for 1-on-1 meeting with Bonnie set up (if applicable)
