### ISSUE TITLE
Organize Research Output Wiki Pages

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#276]
### Overview
We need to update all internship research documentation on the wiki so that future iterations of the internship can copy HfLA processes without disruption.

### Action Items

- [ ] Create Research Documents by overview pages
    - [ ] Create Intern Research Documents by overview page
    - [ ] Create Team Member Research Documents by overview page
    - [ ] Create HfLA Website Team Members Research Documents by overview page
- [ ] Update Research Plan Wiki Pages
    - [ ] Update RP6: Intern Intake Interviews wiki page
    - [ ] Update RP8: Mentor Intake Interviews wiki page
    - [ ] Update RP6: Intern Intake Interviews wiki page
    - [ ] Update RP8: Mentor Intake Interviews wiki page
    - [ ] Update RP9: Weekly Standup Surveys wiki page
    - [ ] Update RP10: Weekly Intern Survey Assessing Mentorship wiki page
    - [ ] Update RP11: Weekly LinkedIn Workshop Survey wiki page
    - [ ] Update RP12: Intern Exit Interviews wiki page
    - [ ] Update RP13: Mentor Intake Survey wiki page
    - [ ] Update RP14: Mentor Exit Interviews wiki page
    - [ ] Update RP15: Mentor Exit Surveys wiki page
    - [ ] Create Wiki Page for RP16: Intern Productivity Dashboard Survey
    - [ ] Create Wiki Page for RP17: Productivity Dashboard Interviews
    - [ ] Create Wiki Page for RP18: Weekly Feedback from Mentors
    - [ ] Create Wiki Page for RP19: Mentor Research Roadmap (there is a label for it)
- [ ] Review or Update Wiki Pages for Research Being Audited
     - [ ] Review or Update RP1: IS21 Interns
     - [ ] Review or Update RP2: Hack for LA volunteers transferrable skills
     - [ ] Review or Update RP3: LinkedIn Recommendation
     - [ ] Review or Update RP4: Hypothesis: HfLA Internship leads to stem retention
     - [ ] Review or Update RP5: Brand / website Audience Alignment
     - [ ] Review or Update RP7: Onboarding Team members
     - [ ] Review or Update LinkedIn Recommendations
- [ ] Create Wiki Pages for Research Not Yet Started
     - [ ] Create Wiki Research Page for IP: Personas
     - [ ] Create Wiki Research Page for TWI: Personas, targets, reasons
     - [ ] Create Wiki Research Page Page for Technical Skills of Incoming Interns
     - [ ] Create Wiki Research Page for Intern Interaction with HfLA teams
     - [ ] Create Wiki Research Page for TWE Team
- [ ] Review or Update Consent Process on Research Output Overview Page

### Resources/Instructions
[Main Research Wiki Page for Internship Volunteers](https://github.com/hackforla/internship/wiki/Research)
[Research Wiki Template](https://github.com/hackforla/internship/wiki/research-wiki-template)

- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by ExperimentsInHonesty** [comment]
Make an issue template for research not yet started
Template name: Research: Create
Template description: The start of a new research plan
Title: TWE: Research Plan for [name of research]

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a research plan to [describe what and why]

### Action Items
- [ ] Create a label for your research plan, using the next number available
- [ ] Create a wiki page for it, using the template
- [ ] Link it to Output overview page
   - [ ] Link it to the appropriate page under `Research Documents by overview type`
   - [ ] Link it under the list `Research Documents by each plan`
- [ ] Fill out the  wiki page
- [ ] Have review meeting with Research Lead
- [ ] Have alignment meeting with Product for sign-off
- [ ] Start creating issues (use list of potential issues templates to select which ones you need)

### Resources/Instructions
[Label page](https://github.com/hackforla/internship/labels?q=RP)
[WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
[Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
[]

**Comment by ExperimentsInHonesty** [comment]
Make an issue template for research not yet started
Template name: Research: Roadmap
Template description: The start of a new roadmap
Title: TWE: Research Plan for [name of roadmap]

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a research roadmap to [describe what and why]

### Action Items
- [ ] Create a new page on the wiki for the roadmap called: `[type name] Research Overview`
  - [ ] link it to the Research Output Overview wiki page
- [ ] Make a new document using the report template 
- [ ] Go to the Google Drive, Research Folder
  - [ ] Create a folder for your research plan starting with `RP`
  - [ ] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [ ] Name your document to match the research folder you just make (e.g., `RP5 - Brand/Website Audience Alignment` )
- [ ] Update the Table of contents (page 2) when you are finished with document

### Resources/Instructions
[TWE: Template: Report Template](https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/template/preview)
 [Google Drive, Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing)
[Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)

**Comment by Aparna1Gopal** [comment]
@bradyse @christine-el 

I have the following questions as I create the Mentor document kit and clean-up the documentation/issues:

**RP10:** Do we need to document RP10 under Mentor Research? Since it is a connected issue and is also documented under the Project Roadmap epic issue. 

**Consent Forms:** Since the type of Consent obtained was different for interns and mentors, do we need to document the Consent forms separately under the Mentor Research above? To keep the Mentor Research kit complete end-to-end? 

**RP15:** I can see the label for RP15 and its corresponding Google folder with the Research Plan. But do we have a separate issue for RP15? If yes, I can link it to the epic Roadmap Issue. 

Thanks!

**Comment by ExperimentsInHonesty** [comment]
@bradyse please ask UXRs to self-assign issues from this [link](https://github.com/hackforla/internship/projects/1?card_filter_query=label%3A%22role%3A+ui%2Fux+research%22) starting from the top of the column

**Comment by bradyse** [comment]
## 2022-10-03 Research Meeting: 1-1 

### Prework

- [ ] Review Aparna's open and closed [issues](https://github.com/hackforla/internship/issues/assigned/Aparna1Gopal)

### Agenda items


### Notes from meeting
- 

### Post Work
-

**Comment by pandanista** [comment]
Hi @ExperimentsInHonesty, @bradyse and I have some questions regarding whether RP018 should be tagged as part of intern research roadmap or mentor research roadmap at weekly UXR meeting on 10/18. I am working on issue [#286](https://github.com/hackforla/internship/issues/286), and would like to get some clarity on that. Thank you!
