### ISSUE TITLE
TWE: Research Roadmap [name of type]

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#285]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a research roadmap to [describe what and why]

### Action Items
- [ ] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [ ] link it to the Research Output Overview wiki page
- [ ] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [ ] Create a new folder in the drive called [number. name of type]
- [ ] Make a new document using the report template 
  - [ ] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [ ] Name your document to be called TWE: Research Roadmap: [name of type] 
- [ ] Update the Table of contents (page 2) when you are finished with document

### Resources/Instructions
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template for Research Roadmap](https://github.com/hackforla/internship/wiki/research-roadmap-wiki-template)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)
- [TWE: Template: Report Template](https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/template/preview)
