### ISSUE TITLE
TWE: Research Structure for RP18: Weekly Feedback from Mentors

### ISSUE THREAD

**Issue by Vyshiali** [hackforla/internship#286]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a wiki structure and task list to support our [name of research plan] so that we can stay organized across all team member and working times

### Action Items
- [ ] Add the milestone: 06.01.01 Research Plan Create Wiki Pages
- [ ] Link the roadmap and its issue for your research into the resources below
- [ ] Create a label for your research plan, using the next number available
  - [ ] Add label to this issue and to the roadmap issue
- [ ] Create a new wiki page for it
- [ ] use the template to copy the structure
- [ ] Link new wiki page to Output overview wiki page
   - [ ] Link it to the appropriate page under `Research Documents by overview type`
   - [ ] Link it under the list `Research Documents by each plan`
- [ ] Fill out the wiki page
- [ ] Have review meeting with Research Lead
- [ ] Have alignment meeting with Product for sign-off
- [ ] Customize issues that will need to be made  (by deleting unneeded) issues from this list
  - [ ] Research Plan (internal)
  - [ ] Timeline
  - [ ] Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] recruitment plan (if required)
  - [ ] identification of recruitment channels
  - [ ] messaging for each type of channel
  - [ ] interest forms
  - [ ] selection criteria
  - [ ] Consent Plan
  - [ ] Research Plan (external) - this is a subset of the internal
  - [ ] Consent Form
-  [ ] create issues using templates from the list of template issues

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)

**Comment by shimahoush** [comment]
A blocker for this is that there is no overall research roadmap on Google Drive for RP 18

**Comment by bradyse** [comment]
### Specific Items for this wiki page update
- [ ] Wiki page for RP018 reflects correct Mentor Roadmap wiki page and Google Doc
- [ ] RP018 reference is removed from Intern Research Roadmap Google Doc.
- [ ] A short link is created in the Google Drive `2. Intern` folder that links to the folder that "lives" (is actually located in) the Mentor Research Google folder (I checked and it seems to be located in the proper place).
- [ ] Add [this file](https://docs.google.com/forms/d/1mZ8ZMtRbfqBa2_x_YhtOxnJCvZpfMu3VQyynGURv2io/viewform?edit_requested=true) to the list of assets on the wiki page and make sure that the original file is located in the proper Google drive folder
- [ ] Continue with the issue that you were working from.

**Comment by cbutcher318** [comment]
@Dzotsen Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Dzotsen** [comment]
Audited RP 018 and updated RP 018 wiki page

**Comment by pandanista** [comment]
@Dzotsen Thank you for the update! After reviewing, I have identified that we need to create the update roadmap issue for RP018 next. I have updated the dependency and action items in this [comment](https://github.com/hackforla/internship/issues/286#issue-1340941104).

Next steps, please 
- [ ] create the update roadmap issue, see `Create Roadmap Details for RP018`
- [ ] replace current dependency with the number of the issue you just created
- [ ] move this issue to the icebox
- [ ] remove your assignment
Thank you!
