### ISSUE TITLE
TWE: Research Structure for RP16: Intern Productivity Dashboard Survey

### ISSUE THREAD

**Issue by adarosh** [hackforla/internship#287]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a wiki structure and task list to support our [name of research plan] so that we can stay organized across all team member and working times

### Action Items
- [ ] Add the milestone: 06.01.01 Research Plan Create Wiki Pages
- [ ] Link the roadmap and its issue for your research into the resources below
- [ ] Create a label for your research plan, using the next number available
  - [ ] Add label to this issue and to the roadmap issue
- [ ] Create a new wiki page for it
- [ ] use the template to copy the structure
- [ ] Link new wiki page to [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
   - [ ] Link it to the appropriate page under `Research Documents by overview type`
   - [ ] Link it under the list `Research Documents by each plan`
- [ ] Fill out the wiki page
- [ ] Have review meeting with Research Lead
- [ ] Have alignment meeting with Product for sign-off
- [ ] Customize issues that will need to be made (by deleting unneeded) issues from this list
  - [ ] Research Plan (internal)
  - [ ] Timeline
  - [ ] Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] recruitment plan (if required)
  - [ ] identification of recruitment channels
  - [ ] messaging for each type of channel
  - [ ] interest forms
  - [ ] selection criteria
  - [ ] Consent Plan
  - [ ] Research Plan (external) - this is a subset of the internal
  - [ ] Consent Form
-  [ ] create issues using templates from the list of template issues

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)

**Comment by adarosh** [comment]
@bradyse RP16 Wiki Page ready for review with Research Lead

**Comment by ExperimentsInHonesty** [comment]
@adarosh Sarah has a bit of a backlog. We are going to release you from this issue and put it in the prioritized backlog for her to review.

**Comment by ExperimentsInHonesty** [comment]
- @bradyse Angela was assigned to another issue https://github.com/hackforla/internship/issues/258 but it was closed because we did not conduct the research.  When you review the wiki.  Let's make sure that its complete enough that we could perform the research next cycle.

**Comment by adarosh** [comment]
@bradyse Added draft email to guardians to Wiki

**Comment by bradyse** [comment]
@ExperimentsInHonesty 

1. Progress: Completed all steps of this issue until Product sign-off
2. Blockers: Need to have product review wiki page and accompanying documentation
3. Availability: As needed
4. ETA: Whenever the research plan issue can be finalized
5. Pictures or links (if necessary): Wiki page for [RP16](https://github.com/hackforla/internship/wiki/Research-Plan-16:-Intern-Productivity-Dashboard-Survey)

_* remember to add links to the top of the issue if they are going to be needed again._

**Comment by sharongupta1** [comment]
This needs to be revised to get rid of the unnecessary steps (keep Finalizing the internal and external research plans)
> Outstanding task items
> Next steps include the following:
> Finalizing the internal and external research plans
> Creating weekly copies of the survey template
> Updating the [Intern Research Plans and Goals](https://github.com/hackforla/internship/wiki/Intern-Research-Plans-and-Goals) wiki page (public-facing)
> Administering the survey and analyzing the data

**Comment by bradyse** [comment]
@sharongupta1 Items above were completed. It's ready for product sign-off now.

**Comment by bradyse** [comment]
Action items need to be customized according to what needs to be done next. For example, we don't need to identify recruitment channels because we already know who our participants are. Answer the question: "What would be needed to support this research?" and then strikethrough whatever is unneeded (this needs to be changed in the template; add instructions for how to do strikethrough).

**Comment by dialectic51** [comment]
1. Progress: Updated wiki task items and completed all steps of this issue until review meeting with research lead. Under customize issues, I used strikethrough across the following items because they shouldn't be required (because we know who are participants are and should be in touch with them): ~recruitment plan, identification of recruitment channels, messaging for each type of channel, interest forms, selection criteria.~ (Will confirm with research lead that this is correct).
2. Blockers: Review meeting with research lead
3. Availability: As needed
4. ETA: When research lead is available.
5. Pictures or links (if necessary): Wiki page for [RP16](https://github.com/hackforla/internship/wiki/Research-Plan-16:-Intern-Productivity-Dashboard-Survey)

**Comment by ExperimentsInHonesty** [comment]
product has checked the issue and it seems fine.
