### ISSUE TITLE
TWE: Research Structure for Intern Interaction with HfLA teams

### ISSUE THREAD

**Issue by ale22arevalo** [hackforla/internship#288]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a wiki structure and task list to support our [name of research plan] so that we can stay organized across all team member and working times

### Action Items
- [ ] Add the milestone: 06.01.01 Research Plan Create Wiki Pages
- [ ] Link the roadmap and its issue for your research into the resources below
- [ ] Create a label for your research plan, using the next number available
  - [ ] Add label to this issue and to the roadmap issue
- [ ] Create a new wiki page for it
- [ ] use the template to copy the structure
- [ ] Link new wiki page to [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
   - [ ] Link it to the appropriate page under `Research Documents by overview type`
   - [ ] Link it under the list `Research Documents by each plan`
- [ ] Fill out the wiki page
- [ ] Have review meeting with Research Lead
- [ ] Have alignment meeting with Product for sign-off
- [ ] Customize issues that will need to be made (by deleting unneeded) issues from this list
  - [ ] Research Plan (internal)
  - [ ] Timeline
  - [ ] Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] recruitment plan (if required)
  - [ ] identification of recruitment channels
  - [ ] messaging for each type of channel
  - [ ] interest forms
  - [ ] selection criteria
  - [ ] Consent Plan
  - [ ] Research Plan (external) - this is a subset of the internal
  - [ ] Consent Form
-  [ ] create issues using templates from the list of template issues

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)

**Comment by bradyse** [comment]
## 2022.MM.DD Meeting Agenda

### Attendees
- [ ] Bonnie
- [ ] Sara

### New agenda items
- Discuss goals of RP20: Interaction with HfLA teams
     - What is the interview going to tell us that we don't already know from the interns and mentors?
     - Is the goal of this research to improve the internship for the interns, for everyone else, or both?
     - Possible answers:
          - What did the interns do on their assigned HfLA team?
          - Were there challenges that HfLA volunteers faced in working with the interns?

### FYIs
- [All issues for RP020](https://github.com/hackforla/internship/labels/Research%3A%20RP020)
- [Wiki page for RP20](https://github.com/hackforla/internship/wiki/Research-Plan-20:-Intern-Interaction-with-HfLA-Teams)

### Notes from meeting
- 

### Post Work
-

**Comment by ExperimentsInHonesty** [comment]
Place the interns on a scale from 1-5 with 5 significantly more effective than ordinary volunteers and 1 being significantly less
Did it impact the website team differently than having regular volunteers, if yes, how?
To what extent did ~the HfLA volunteers~ you interact with the interns? (frequency and engagement)
Who else should we talk to that had interaction, or was affected by the interns?

**Comment by bradyse** [comment]
@ExperimentsInHonesty , thanks so much for providing your thoughts. I think we should be good without a meeting. 

Just to clarify, our ultimate goal is to explore the HfLA volunteers' perspectives on how it was working with the interns. Once we ask them these preliminary questions, we'll get a better sense of how we should proceed with the internship. 

Since there were only a couple interns working with you on PM stuff, our primary target sample will be from the Website team, correct?

**Comment by ExperimentsInHonesty** [comment]
@bradyse you are are are done with this product, signoff at this point.  So I am going to mark this complete in the reach out to Bonnie form queue.  

I have removed the people assigned to this @lkawentel @shimahoush and put the issue in the icebox, until the issues I added to the dependency can be removed.  

Additionally, here is a list of all the issues that need to be made so that this issue will be able to be completed
  - [ ] TWE: Research Structure: Template: Research Plan Document (internal)
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: Create Research Plan (internal)
  - [ ] TWE: Research Structure: Template: Timeline
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: Create Timeline
  - [ ] TWE: Research Structure: Template: Forms/Survey/Script
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: Forms/Survey/Script
  - [ ] TWE: Research Structure: Template: emails text (if required)
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]:  emails text
  - [ ] TWE: Research Structure: Template: recruitment plan (if required)
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: recruitment plan
  - [ ] TWE: Research Structure: Template: identification of recruitment channels
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: identification of recruitment channels
  - [ ] TWE: Research Structure: Template: messaging for each type of channel
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: messaging for each type of channel
  - [ ] TWE: Research Structure: Template: interest forms
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: interest forms
  - [ ] TWE: Research Structure: Template: selection criteria
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]:  selection criteria
  - [ ] TWE: Research Structure: Template: Consent Plan
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: Consent Plan
  - [ ] TWE: Research Structure: Template: Research Plan (external) - this is a subset of the internal
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: Research Plan (external)
  - [ ] TWE: Research Structure: Template: Consent Form
    - [ ] TWE: Research Structure: Template Issue: TWE: RP[replace with number]: Consent Form

Linda and Shima should move on to the next item in the prioritized Backlog.
