### ISSUE TITLE
 TWE: Research: Technical Skills of Incoming Interns: Research Structure: Create

### ISSUE THREAD

**Issue by epierotti3** [hackforla/internship#289]
#### Dependency
- #375
- #781 will ensure the content in RP019 that belongs in RP027 gets moved inside the [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?tab=t.0#heading=h.4qi601o1qcet) document. And RP019 in that doc get re-written and approved.

### Overview
We need to create a wiki structure and task list to support the development of a new research plan on Technical Skills of Incoming Interns so that we can stay organized and consistent across all team members and working times.

**Resources/Instructions**: This section is at the bottom of this issue (scroll to the bottom to view it now). You will be asked to add links to this section while completing the issue. 

Tip: Use two windows side by side. One with the issue open and the other one with resource links displayed to avoid back and forth. To prevent loss of work, refresh both windows after each edit.

#### Customize the issue settings (located in right sidebar)
- [x] Under Assignees, assign yourself or another team member  
- [x] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Participant Type: Interns`
- [x] Remove the `Participant Type: missing` label
- [x] Under Projects, choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), choose `Repository`, and choose `TWE: Project Board`
- [x] Add the milestone: choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and choose `Research Plan Create Wiki Pages` 
- [x] Remove the label `milestone: missing`

#### Customize Resource Links
- Customize Resources for Roadmap Document and Issue
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Choose Interns in the "Research Documents by Participant Type" section 
    - [x] Open Research Roadmap document from the wiki page
    - [x] Choose Share > Copy link > Done
    - [x] Copy the link for the Research Roadmap on Interns
    - [x] Update Resource # 2.01 with the link you just copied. Place it into parentheses at the end of the line.
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
    - [x] Go to the top of the Github page, and open the Issues tab in a new tab
    - [x] Use "roadmap" as a filter to search for any existing research roadmap issues on Interns on Github. Check both open and closed issues. <img width="400" alt="Screenshot 2024-04-16 at 5 40 12 PM" src="https://github.com/hackforla/internship/assets/57029070/78e12f67-3f70-4eb9-b2c4-57dea20303a5">
    - [x] Once identified the roadmap issue, add the issue number to Resources 2.02
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">

#### Create a New Label with the New Research Plan Number
- Create a label dedicated to the new research plan number, using the next number available. 
    - Before creating a new label associated with the new research plan number, check Wiki, Google Drive and label page to make sure the next number available is consistent across all sources
        - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
        - [x] Choose the link in the "Research by Plan Number" section 
        - [x] Check the existing research plan numbers on wiki
        - [x] Go to the Google Drive Folder: Research by Plan # and name (Resources 1.02)
        - [x] Check the existing research plan numbers in Google Drive's research folder
        - [x] Go to the label page (Resources 1.03)
        - [x] Make sure the next available number is consistent
    - [x] Open the label page (Resources 1.03) if it is not open 
    - [x] Choose New Label
    - [x] Apply the same naming structure and color used in other research plan labels
    - [x] Choose Create label
- Update the new research plan number in this issue
    - [x] Use Find/Replace (**Mac:** ⌘+F or **PC**: Ctrl+F) to search for and replace the `019` (including text and the brackets) in this issue with the new research plan number (three digit format, ex: "001" for research plan "RP001") 
- Apply the new label to relevant issues   
    - [x] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Research: RP019` in this issue
    - [x] Remove the `Research 000: missing` label from this issue
    - [x] Open the roadmap issue in Resources 2.02, and apply the label `Research: RP019` 

#### Set Up A Wiki Page and Google Drive Folders
- Create a new wiki page for the new research plan
    - [x] Open the template in Resources 1.04 in a new tab to copy the wiki page structure
    - [x] Open the link in Resources 1.05 in another new tab to paste what you copied into the big text box
    - [x] Create a title for this research plan by following the naming structure of other research plans
        - Go to the link in Resources 1.01 
        - Choose the link in the Research by Plan Number section
        - Observe the naming structure of other existing research plans
        - Use the same structure to name this new research plan
    - [x] Choose Save Page
    - [x] Copy the URL of the new wiki page of the research plan
    - [x] Update Resource 2.03 with the link you just copied. Place it into parentheses at the end of the line. 
    
- Link the new wiki page to the following locations of Research Output Overview wiki page (link in Resources 1.01)
    - [x] Link it to the appropriate page under `Research Documents by Participant Type`
    - [x] Link it under `Research Plan By Status` based on whether it is current or future research. If the research plan has been created or the data has been collected, then choose `Current Research`. If no research plan nor data has been collected, then choose `Future Research`.
    - [x] Link it under `Research by Plan Number`

- Create a research plan folder and a shortcut to the folder on the shared Google Drive
    - [x] Go to the Shared Drives > Internship > Internships > Research > Research by Participant Type
    - [x] Open the appropriate participant type folder for this RP
    - [x] Check if there is a folder created for this research plan
        - [x] If yes, move onto the next section
        - [ ] If no, please create a new folder called `RP019 - Technical Skills of Incoming Interns` in the "Research by Participant Type" folder.  
    - [x] Right click the folder you just created and choose Organize > Add shortcut 
    - [x] Go to All Locations > Shared drives > Internship > Internships > Research > Research by Plan # and name
    - [x] Click the "Add" button and then "Ok" to the pop-up
    - [x] Right click the folder you just created and choose Share > Get link
    - [x] Choose Copy link and Done
    - [x] Update Resource 2.04 with the link you just copied. Place it into parentheses at the end of the line. 
 
#### Customize Wiki Page
- [x] Review all issues (open and closed) associated with the new research plan by checking on the label page (Resources 1.03)
- [x] Fill out each section of the wiki page with any information available. If there is no information available, please leave it blank.
- [x] Include any links or documents that have already been created 
    - Research Roadmap section
        - [x] Add link to the Intern Research's wiki page from Research Output Overview Page(Resources 1.01)
        - [x] Add link to the research roadmap document (Resources 2.01)
    - All Issues section
       - [x] Choose the label page (Resources 1.03)
       - [x] Choose the RP019 label
       - [x] Copy the URL of the issues associated with RP019
       - [x] Paste in the parenthesis at the end of the label line <img width="200" alt="Screenshot 2024-04-16 at 7 48 51 PM" src="https://github.com/hackforla/internship/assets/57029070/eaa0660f-4abf-44bc-8312-3dc16760d8d7">
    - Assets section
        - [x] Add the link to Interns folder on shared Google Drive
            - [x] Choose Research Output Overview wiki page (Resources 1.01) 
            - [x] Locate the appropriate participant type in the Research Documents by Participant Type section
            - [x] Copy the text and link from the Research Documents by Participant Type section of the wiki page
            - [x] Remove `[TYPE]()`  in the Assets section on the RP019's wiki page and paste what you just copied to the right of the "Type folder: "  
        - [x] Add the link to the new research plan folder (Resources 2.04)
- [x] Customize issues that will need to be made by striking through unneeded issues from this list (put ~ before and after text to make it strikethrough).
    - [x] ~Research Roadmap #375 is completed~
    - [ ] Research Plan (internal)
    - [ ] Timeline
    - [ ] Forms/Survey/Script
    - [ ] Emails text to parents if participants are minor (if required) 
    - [x] ~Recruitment plan for extra UXRs (if required)~
    - [x] ~Selection criteria for UXRs (if required)~
    - [x] ~Identification of recruitment channels for UXRs (required)~
    - [x] ~UXRs recruitment message draft for each type of channel (i.e. Slack, social) (required)~
    - [x] ~Recruitment plan for participants (if required)~
    - [x] ~Selection criteria participants (if required)~
    - [x] ~Identification of recruitment channels for participants (not required)~
    - [x] ~Participants recruitment message draft for each type of channel (i.e. Slack, social) (if required)~
    - [x] ~Interest forms for UXRs (if required)~
    - [ ] Consent Plan for participants
    - [ ] Research Plan (external) - this is a subset of the internal
    - [ ] Consent Form
- [x] Update Outstanding Task Items on wiki page to reflect the necessary issues from the list above
- [x] Have review meeting with Research Lead
- [ ] Have alignment meeting with Product for sign-off
- [ ] Create issues using templates from the list of template issues (Resources 1.06)

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Plan # and name](https://drive.google.com/drive/folders/1ZQnTEFbIQjxSDBmPTO0zuLroZVqd-nuZ?usp=share_link)
1.03 [Label page](https://github.com/hackforla/internship/labels?q=RP)
1.04 [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
1.05 [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
1.06 [Research template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)

#### Resources gathered during the completion of this issue
2.01 [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)
2.02 Roadmap issues related to RP019
- #309 
- #375
- #449 
- #448 

2.03 [RP019: Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns)
2.04 [RP019: Google Drive Folder](https://drive.google.com/drive/folders/1L76hXf2YYcl21N27oL65QRJpp8lCRnGi?usp=drive_link)

**Comment by shimahoush** [comment]
The blocker on this issue is that there is no research roadmap for RP19 in the Google Drive.

**Comment by bradyse** [comment]
@sophie-delsaux 

- I unassigned you to this issue because you were working on the transcription.
- I also removed any links that you put on the wiki page that referenced RP001's assets.
- RP019 does not have the roadmap details or any of the other assets needed to do the analysis at this point in time. So I updated the outstanding task items to reflect this.

**Comment by cbutcher318** [comment]
@AndrewSalvatore when you are ready to update, answer the following questions:
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by AndrewSalvatore** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"
Next steps are: review meeting with Research lead, sign-off by project lead, then issue creation for outstanding issues

Blockers: "Difficulties or errors encountered."
None

Availability: "How much time will you have this week to work on this issue?"
6 hours

ETA: "When do you expect this issue to be completed?"
I'm available to review with Research Lead at his/her earliest convenience

Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
None

**Comment by AndrewSalvatore** [comment]
> @AndrewSalvatore Thank you for the update! I reviewed the issue. Everything looks good. Just one minor request: Would you please provide one sentence under the Current Status section for [RP19 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns) to indicate whether and how much research has been done? Thank you, and good job!

Done!

**Comment by ExperimentsInHonesty** [comment]
@AndrewSalvatore Please 
- [ ] create the update roadmap issue
- [ ] replace current dependency with the number of the issue you just created
- [ ] move this issue to the icebox
- [ ] remove your assignment

**Comment by pandanista** [comment]
@apwirth This issue is a good first issue for you to get familiar with our workflow, GitHub, and Google Drive navigation. 

Some of the action items have been completed, but please still go through each step to 1). get more comfortable with the GitHub issue and 2) double check on the action item to see if they are done correctly. 

Let me know if you have any questions.

**Comment by ExperimentsInHonesty** [comment]
@apwirth Please provide update here in your issue.  @pandanista mentioned that you updated her on slack, but issue updates should be provided in the issue weekly.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by pandanista** [comment]
- There are checkboxes that haven't been checked off in this [comment.](https://github.com/hackforla/internship/issues/289#issue-1340954337) 
    - If it is done, please check it off.

- According to the wiki page, it says RP019 was conducted in 2022. Was RP019's research done in 2022 based on the research roadmap?
<img width="209" alt="Screenshot 2024-05-14 at 7 26 58 PM" src="https://github.com/hackforla/internship/assets/57029070/ac306a45-f19a-4bb1-a49b-5543a423e86e">

- The outstanding task items on the wiki page don't look complete. Please check with the list provided in this issue.
<img width="827" alt="Screenshot 2024-05-14 at 7 27 14 PM" src="https://github.com/hackforla/internship/assets/57029070/dcae6520-1a67-4b0c-82e7-8a7652b68fe4">

**Comment by pandanista** [comment]
@sunannie27: Please review [RP019: Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns), and we can close it if everything looks good.

**Comment by ExperimentsInHonesty** [comment]
@apwirth The checkboxes under this item `Customize issues that will need to be made by striking through unneeded issues from this list (put ~ before and after text to make it strikethrough).` on this issue #289 have all been checked instead of reviewed and strikethroughed as required.  So that means that items that won't need to be done, are listed on the wiki as outstanding next steps.

FYI: @pandanista

**Comment by pandanista** [comment]
Andrew is taking a leave from the team, I am reassigning this issue to @e-khlystova.

@e-khlystova: 
- Would you please review [RP019's wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns), [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing), and [RP019: Google Drive Folder](https://drive.google.com/drive/folders/1L76hXf2YYcl21N27oL65QRJpp8lCRnGi?usp=drive_link) to finish this issue? Thank you! Let me know if you have any questions.

- A few comments that were not addressed by Andrew, would you please take a look? 

    - According to [the wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns), it says RP019 was conducted in 2022. Was RP019's research done in 2022 based on the research roadmap?  <img width="200" alt="Screenshot 2024-05-14 at 7 26 58 PM" src="https://github.com/hackforla/internship/assets/57029070/ac306a45-f19a-4bb1-a49b-5543a423e86e">
        - If it wasn't conducted in 2022, please specify that on the wiki page. You can say something like "This research has not been conducted" or "this research will be conducted with the next cohort" under the research year section on [the RP019's wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns).

    - The checkboxes under this item `Customize issues that will need to be made by striking through unneeded issues from this list (put ~ before and after text to make it strikethrough).` on this issue #289 have all been checked instead of reviewed and strikethroughed as required.  However, these are items on the list that are not needed for this research plan. <img width="600" alt="Screenshot 2024-05-28 at 6 27 00 PM" src="https://github.com/hackforla/internship/assets/57029070/538543fc-88c2-4407-abfe-7d14195962d9">
        - For example, we don't foresee that we need any UXR for executing this research plan, so please unmark those checkmarks and put strikethroughs as required. <img width="600" alt="Screenshot 2024-05-28 at 6 28 19 PM" src="https://github.com/hackforla/internship/assets/57029070/ac626017-16e7-4c00-b540-3c9a5cc53e06">
        - Please update the outstanding task items on the [RP019's wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns).

**Comment by SalomeM-UXD** [comment]
Hi @pandanista , the check box indicated in the screenshot wants me to choose Program Management under the repository , but the option is not available
![image](https://github.com/hackforla/internship/assets/166466752/403fe16f-6b65-4f4f-a05d-eddfdf6fdcc2)

**Comment by pandanista** [comment]
@SalomeM-UXD Thank you for catching the mismatched project board and #375's wrong label. I edited the action item and added the checkbox.

**Comment by rlcampbe** [comment]
1. Progress: Working on setting up wiki page and Google Drive folders
2. Blockers: None
3. Availability: 4 hrs
4. ETA: By Aug. 22

**Comment by rlcampbe** [comment]
Progress: Completed
Blockers: None

**Comment by pandanista** [comment]
@rlcampbe: Thank you for working on this issue!
As a follow-up to the detailed review we did at the UXR meeting today, here are some tips that'll help you with your revision:
- Make sure what you have done are reflected by the checkmarks. 
    - If you have completed or review an action item in the issue, please mark it so we know that has been done. If you didn't work on it or review it, then do not check off the box.
- The issues/outstanding task items are based on each research plan's needs, so they often vary despite of a general list of issues we follow. 
    - Like I mentioned in today's meeting, if we are researching **interns** (RP019's participant type), then there is a possibility that they are minors, which means we need parental consent, emails to parents, etc.
    - Wiki page and/or Google drive should have information to help you decide what is needed. Please pay attention to details when gathering information.
    - Please leave a comment in this issue if you have any questions or anything you are not sure.
- Once the issue is completed, please put it in the "Questions/Review" column, and add the "ready for research lead" label. Please don't make it as done in project status. Please read through ["How we work" section](https://github.com/hackforla/internship/wiki/Joining-the-Team#how-we-work) on Joining the team Wiki page.

**Comment by rlcampbe** [comment]
Progress: ready for research lead

**Comment by rlcampbe** [comment]
@pandanista It's my understanding that the only thing that has been completed is the roadmap so I've left mostly everything unchecked. I do have a question about the selection criteria for participants. I noticed that the roadmap document includes information about who the participants are but I'm unsure if that counts as "criteria for participants" because it doesn't seem as  specific but maybe it is?

**Comment by erin-ryan-93** [comment]
@pandanista for section about customizing Wiki page, do you know who UXR is referring to? Is that recruiting researchers to help assess intern skills, or refer to recruiting interns themselves?

**Comment by pandanista** [comment]
> [@pandanista](https://github.com/pandanista) for section about customizing Wiki page, do you know who UXR is referring to? Is that recruiting researchers to help assess intern skills, or refer to recruiting interns themselves?

It refers to extra UXRs, which means UXRs from other teams at HfLA, that will help us conduct the research. 

@rlcampbe: I believe I mentioned at previous UXR meetings and an all-team meeting regarding this issue that:
- If we need to conduct interviews for a research plan, then we needed to recruit more UXRs because all the interviews might be happening over a span of a couple of days or the same week. 
- If we are distributing a survey, then we won't have the need to recruit extra UXRs. 

- Based on the wiki page and/or research roadmap doc, what is the research method proposed for RP019?
   - Based on that, you should be able to decide what to include or not. 
   - Given all the information, do you think we need to have the following items? 
      - Recruitment plan for extra UXRs (if required)
      - UXRs recruitment message draft for each type of channel (i.e. Slack, social) (required)

**Comment by rlcampbe** [comment]
Progress: updated outstanding task items on RP019 wiki
Blockers: none

**Comment by pandanista** [comment]
@rlcampbe Thank you for the update. Will review this issue shortly. Meanwhile, I will assign a new issue to you to test a template.

**Comment by rlcampbe** [comment]
1. Progress: working on updating the wiki
2. Blockers: none
3. Availability: 6
4. ETA: Oct. 10

**Comment by pandanista** [comment]
- Do we need the `create/update roadmap` and `research structure set up` issues for RP019 and a new research plan?

**Comment by ExperimentsInHonesty** [comment]
This issue is on hold until the content in RP019 that belongs in RP027 gets moved inside the [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?tab=t.0#heading=h.4qi601o1qcet) document.  And RP019 in that doc get re-written and approved.  An issue needs to get made for that.   Then that issue will be added as a dependency on this issue.

<details><summary>The rewrite requirements</summary>
Separate this into two research plans with the first plan being the skill assessment before the program starts, and the insights from that research being delivered so that last min adjustments can be made to any training planned, or any support plan for the interns. 
The second being administering and comparing their self assessment in the last week of the internship RP027
</details>
