### ISSUE TITLE
TWE: Research Structure for RP 17: Productivity Dashboard Interviews

### ISSUE THREAD

**Issue by shimahoush** [hackforla/internship#291]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a wiki structure and task list to support our [name of research plan] so that we can stay organized across all team member and working times

### Action Items
- [ ] Add the milestone: 06.01.01 Research Plan Create Wiki Pages
- [ ] Link the roadmap and its issue for your research into the resources below
- [ ] Create a label for your research plan, using the next number available
  - [ ] Add label to this issue and to the roadmap issue
- [ ] Create a new wiki page for it
- [ ] use the template to copy the structure
- [ ] Link new wiki page to [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
   - [ ] Link it to the appropriate page under `Research Documents by overview type`
   - [ ] Link it under the list `Research Documents by each plan`
- [ ] Fill out the wiki page
- [ ] Have review meeting with Research Lead
- [ ] Have alignment meeting with Product for sign-off
- [ ] Customize issues that will need to be made (by deleting unneeded) issues from this list
  - [ ] Research Plan (internal)
  - [ ] Timeline
  - [ ] Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] recruitment plan (if required)
  - [ ] identification of recruitment channels
  - [ ] messaging for each type of channel
  - [ ] interest forms
  - [ ] selection criteria
  - [ ] Consent Plan
  - [ ] Research Plan (external) - this is a subset of the internal
  - [ ] Consent Form
-  [ ] create issues using templates from the list of template issues

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)

**Comment by shimahoush** [comment]
The blocker on this issue is that there is no research plan in the Google Drive for this

**Comment by bradyse** [comment]
@christine-el please confirm that all RP17 documentation that exists is in the Google Drive, and add any knowledge about this RP to the research roadmap document for RP 17: [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)

**Comment by christine-el** [comment]
@bradyse I filled out the Wiki page for this research and the research roadmap.  There wasn't much to do, as we did not create a research plan or actually carry out the research.  There is no documentation for this project, except for the conversation about the productivity tracker that Bonnie recorded with an intern.  That could be uploaded to this Wiki, or it could also be put with the other exit interviews and analyzed as a part of that set (which I think would be more useful).

**Comment by christine-el** [comment]
@bradyse Yes, this all looks good!  I think the only person who could figure out the goal or metrics would be Bonnie at this point, so I'm not sure it would be worth it for another person to pick it up in terms of last year.  I don't think there is any documentation that could help someone delineate these metrics--they would need to talk to Bonnie.

**Comment by bradyse** [comment]
@sharongupta1 This wiki page is ready for product sign-off.

[RP17 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)

**Comment by dialectic51** [comment]
1. Progress: crossed out unnecessary issues and updated the wiki for Outstanding Task Items; moved issue to questions/review column.
1. Blockers: need review meeting with research lead.
1. Pictures or links (if necessary): Wiki page for [RP17](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)

**Comment by bradyse** [comment]
@pandanista I have reviewed this wiki page. The only concern I have is under [Current Status](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews#current-status). 

Do we need to locate the Informed Consent for the single interview? That was part of the work from last summer. I believe that we can move forward with developing the research plan using the single interview.

**Comment by ExperimentsInHonesty** [comment]
Consent: 
- intern interviewed was over 18.  I ask him in the interview if I could record, and he said yes.
- next time we will be more formal

**Comment by pandanista** [comment]
There was only one interview conducted on this topic during IS2022. See [Current Status](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews#current-status) for more info. 

Two options to move forward RP017's research process. 

-[ ] Option A: Group the single interview from 07-13-2022 as part of exit interviews (RP012) and analyzed the interview as part of that set.

-[ ] Option B: Treat the single interview from 07-13-2022 as a separate research plan. In that case, the next steps: 
    - Write a research plan (internal and external) based upon the single interview conducted in 2022
    - Review research plan alignment with intern research roadmap
    - Construct timeline for completion
    - Data de-identification
    - Data analysis
    - Data synthesis

For future cohorts, consent forms, interview prep, UXR recruitment, make issue for interviews will need to be created before conducting the research.

**Comment by bradyse** [comment]
@priyatalwar @pandanista I can create the issue for writing the research plan, thanks!

**Comment by priyatalwar** [comment]
@bradyse please go ahead with creating the research plan. Thanks.

**Comment by mayankt153** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
  - [ ] Have access, its located in ____
  - [x] public
-https://github.com/hackforla/internship/issues/442
  - [ ] Have access, its located in ____
  - [x] public
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
  - [ ] Have access, its located in ____
  - [ ] public
- [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)
  - [ ] Have access, its located in ____
  - [ ] public
- [RP17 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews)
  - [ ] Have access, its located in ____
  - [ ] public
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
  - [ ] Have access, its located in ____
  - [ ] public
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
  - [ ] Have access, its located in ____
  - [ ] public
- [Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)
  - [ ] Have access, its located in ____
  - [ ] public
