### ISSUE TITLE
TWE: Research Structure for IP: Personas 

### ISSUE THREAD

**Issue by lkawentel** [hackforla/internship#292]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a wiki structure and task list to support our [name of research plan] so that we can stay organized across all team member and working times

### Action Items
- [ ] Add the milestone: 06.01.01 Research Plan Create Wiki Pages
- [ ] Link the roadmap and its issue for your research into the resources below
- [ ] Create a label for your research plan, using the next number available
  - [ ] Add label to this issue and to the roadmap issue
- [ ] Create a new wiki page for it
- [ ] use the template to copy the structure
- [ ] Link new wiki page to [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
   - [ ] Link it to the appropriate page under `Research Documents by overview type`
   - [ ] Link it under the list `Research Documents by each plan`
- [ ] Fill out the wiki page
- [ ] Have review meeting with Research Lead
- [ ] Have alignment meeting with Product for sign-off
- [ ] Customize issues that will need to be made (by deleting unneeded) issues from this list
  - [ ] Research Plan (internal)
  - [ ] Timeline
  - [ ] Forms/Survey/Script
  - [ ] emails text (if required)
  - [ ] recruitment plan (if required)
  - [ ] identification of recruitment channels
  - [ ] messaging for each type of channel
  - [ ] interest forms
  - [ ] selection criteria
  - [ ] Consent Plan
  - [ ] Research Plan (external) - this is a subset of the internal
  - [ ] Consent Form
-  [ ] create issues using templates from the list of template issues

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)
