### ISSUE TITLE
TWE: Research Roadmap: TWE Volunteers

### ISSUE THREAD

**Issue by epierotti3** [hackforla/internship#304]
### Overview
We need to create a research roadmap for all research plans involving TWE Team Volunteers so that future team researchers can carry out the research.

### Action Items
- [x] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [x] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [x] link it to the Research Output Overview wiki page
- [x] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [x] Put back in Prioritized Backlog under new milestone
- [x] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [x] Create a new folder in the drive called [number. name of type]
- [x] Make a new document using the report template 
  - [x] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [x] Name your document to be called TWE: Research Roadmap: [name of type] 
- [x] Update the Table of contents (page 2) when you are finished with document
- [x] Remove label for UI/UX research role and add product role label
- [ ] Product reviews Research Roadmap

### Research Roadmap
- [TWE: Research Roadmap: TWE Team Volunteers](https://docs.google.com/document/d/1BLQSqhIB2cN8jGywxICT0hf6vEV1ltcAIhTTetsRQ_k/edit?usp=sharing)

### Resources/Instructions
- [Wiki roadmap overview for TWE Volunteers ](https://github.com/hackforla/internship/wiki/TWE-Volunteers-Research-Overview)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template for Research Roadmap](https://github.com/hackforla/internship/wiki/research-roadmap-wiki-template)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)

**Comment by bradyse** [comment]
@priyatalwar This issue is complete but the roadmap document itself is not yet finished.

**Comment by ExperimentsInHonesty** [comment]
A new issue will be made to create the content
