### ISSUE TITLE
Update Other HfLA Team Research Overview page

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#305]
### Dependencies
- [ ] #380 

### Overview
We need to create a research roadmap to plan out research on other HfLA team volunteers who worked with the interns. This should be prioritized before these volunteers leave the organization.

### Action Items
- [x] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [x] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [x] link it to the Research Output Overview wiki page
- [x] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [x] Put back in Prioritized Backlog under new milestone
- [x] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [x] Create a new folder in the drive called [number. name of type]
- [x] Make a new document using the report template 
  - [x] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [x] Name your document to be called TWE: Research Roadmap: [name of type] 
- [x] Update the Table of contents (page 2) when you are finished with document
- [ ] Product reviews overview page

### Resources/Instructions
- [Wiki Roadmap for for Other HfLA Research Overview](https://github.com/hackforla/internship/wiki/HfLA-Volunteers-Research-Overview)
- [WIKI template for Research Roadmap](https://github.com/hackforla/internship/wiki/research-roadmap-wiki-template)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)
- [TWE: Template: Report Template](https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/template/preview)

**Comment by bradyse** [comment]
@priyatalwar @ExperimentsInHonesty 

Creating the overview page is done, but the roadmap document needs to be revised as we fill in the research plans.  Should this issue be closed or is there a dependency on updating the Roadmap Google Doc?

**Comment by priyatalwar** [comment]
@bradyse @pandanista I think we should add a dependency label so I just added it.

**Comment by pandanista** [comment]
Hi @priyatalwar, the dependency and its label don't apply to this issue. To the contrary, this issue is a precedent issue of #380. 

Based on this issue's action item, it was to create a [wiki overview for HfLA volunteer research](https://github.com/hackforla/internship/wiki/HfLA-Volunteers-Research-Overview) and to create the research roadmap doc's structure, but not to fill in the detailed information in the research roadmap doc. We created #380 after the completion of this issue, so #380 serves the purpose of filling in the detailed information in the research roadmap doc.

Please review [wiki overview for HfLA volunteer research](https://github.com/hackforla/internship/wiki/HfLA-Volunteers-Research-Overview), and let us know if you have any questions. 

If the wiki overview looks good, please go ahead and sign off on the last action item and close the issue since it has been completed. Thank you!

**Comment by priyatalwar** [comment]
On second d thoughts makes sense and I see that the links under the consent process have been updated now so closing this issue. Thank you.
