### ISSUE TITLE
TWE: Create Roadmap: Intern Research

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#309]
### Overview
We need to create the Roadmap Google Doc for Intern Research so that we can keep track of basic details across all intern research plans.

### Action Items
- [x] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [x] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [x] link it to the Research Output Overview wiki page
- [x] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [x] Put back in Prioritized Backlog under new milestone
- [x] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [x] Create a new folder in the drive called [number. name of type]
- [x] Make a new document using the report template 
  - [x] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [x] Name your document to be called TWE: Research Roadmap: [name of type] 
- [ ] Brainstorm with the team what research the team should do for this type (Intern) and provide basic details for each research plan
   -  Goals
   - Requirements
   - Timelines
   - Delivery
   - Follow-up Options
   - Research Analysis  
- [x] Update the Table of contents (page 2) when you are finished with document
- [x] Research lead reviews roadmap
- [x] Product reviews roadmap

### Resources/Instructions
-[TWE: Research Roadmap: Interns Google Doc](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template for Research Roadmap](https://github.com/hackforla/internship/wiki/research-roadmap-wiki-template)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)
- [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1uNwQzgdBb1ieO-wRPjxi-Tx-2Xg31dCbv8KC_Xt30y8/template/preview)

**Comment by bradyse** [comment]
@shimahoush - I have almost everything done in this issue, but we just need to collect all the relevant info and put into the Google doc that I started here: [TWE: Research Roadmap: Interns Google Doc](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing).

I will go through it and add all the document headings first. Then we can copy and paste the relevant info that we need from the various sources on the wiki pages or from the Google drive.

**Comment by shimahoush** [comment]
I went through the various RPs and added in all the information that I could find. The main blocker is that many of the RPs are not written yet. I'll continue to mine the wiki for more info.

**Comment by bradyse** [comment]
@ExperimentsInHonesty please see this Research Roadmap template that we're using: https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
FYI @shimahoush  - @bradyse and I updated the template last night and here is the URL to easily make a copy: [Research Roadmap template](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)

**Comment by ExperimentsInHonesty** [comment]
@bradyse @shimahoush This issue is in the prioritized backlog, and it's assigned to both of you.   Please read the notes below and decide on next action

Please note:
1. items in the prioritized backlog column are not assigned yet
2. items that are assigned should be in the In progress column
3. only one person should be assigned to each issue (exception: multiple people can be assigned to an agenda)
4. only one issue should be assigned to a person (exception: you can be assigned also to agendas)
5. if there are questions needed (i.e., you have a blocker, then you can put the issue in the questions and review column with a note about what you need as the last comment).  Please do not assign the person you need help from to the issue.  _This is how Bonnie got assigned to 100 issues._

**Comment by bradyse** [comment]
@ExperimentsInHonesty thanks for the reminders and the link to the template. I have added this link to the wiki page overview of templates: [UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates)

**Comment by bradyse** [comment]
@shimahoush I updated the document according to the most recent version of our Google Doc Roadmap Template. If you have time, could you review the parts where there is a gap and you could fill it in? For example, you'll notice that instead of "Text" there are general instructions (e.g., "Provide the goals...."). 

Could you go through and see if there are any obvious holes that you could provide some information on? One subsection that was added to the template was "Research Analysis" for each research plan. So perhaps you could add that information on the ones that you've already completed.

When you're done with this and you're ready for the next task, you could go back to this issue: https://github.com/hackforla/internship/issues/276 and do the audit/review of the existing documentation. 

If you hit a blocker, perhaps you could update the Resources in the issue with the relevant information. For example, on https://github.com/hackforla/internship/issues/289 you could replace the resources listed in the issue with the actual wiki page for that Research Plan.

If you find that there is documentation that needs updated to the current branding, you could also do that for any old resources. For example on this issue: https://github.com/hackforla/internship/issues/297 there is an actual research plan, but the documentation has been added to the wiki or been updated with the current templates.

**Comment by shimahoush** [comment]
I went through the [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#) and updated everything that I could find. The blocker remains the same: lack of adequate information on RPs to actually fill out the roadmap.

Not sure what exactly what is needed for #276.

**Comment by bradyse** [comment]
@priyatalwar This issue is done and all the action items have been completed. The document is not completely finished, but has been created and updated.

**Comment by ExperimentsInHonesty** [comment]
The roadmap is not finished but we are going to close this issue so a proper audit can be created
