### ISSUE TITLE
TWE: Create Template Issue: Research: Create Roadmap Details

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#323]
### Overview
We need to create a template issue for `Research: Create Roadmap Details` so that we have consistent, transparent, defined and self-supporting structure for people creating them.

### Action Items
- [x] Add to the Project Board
- [x] Add the milestone: Project Management
- [x] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.
- [x] Any place you see `[replace...]` replace both the text and the brackets with what it is asking for
- [x] Create a draft of new template by copying the content block below to a comment on this issue, which will be known as our Draft
- [x] In your draft, Fill out the top part (called front matter) with the info it needs.  See the Resources section below for definition and example.
- [x] Define any Dependencies (or remove the dependency section)
- [x] Customize the Overview section
- [x] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [x] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [x] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [x] the links provided by the issue creator should be in the same order as the Action Items 
- ~[ ] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking the WIKI Templates by role pages.~ 
  - ~[ ] if there is a template~
     - ~[ ] Add a link to the template into the ` ### Resources`  section of your draft~
  - ~[ ] if there is no template yet~
    - ~[ ] put a placeholder into the` ### Resources`  section of the draft `[TWE: Template: Research Roadmap]`~
- [x] Get sign-off by product on the draft
- [x] Create the template issue on the repo
- [x] Add the link to related "Get started" button in the Resources section below.
- [x] Update the appropriate place in wiki for your template (see resources section)

### Resources/Instructions
Getting started button link for creating new issue using the ["Create Roadmap Details"](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research%2C+feature%3A+roadmap%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--create-roadmap-details.md&title=TWE%3A+Research%3A+Create+Roadmap+Details+for+RP%5B%23%23%23%5D) template on the "New issue" tab

#### WIKI Templates
- by role pages
  - [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
  - [Design]
  - [Product]
  - [Engineering]
- default document templates, in case you don't have one yet can found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Content to copy for draft
```
Draft of `Research: Create Roadmap Details` template issue
---
name: TWE: Create Template Issue: Research: Create Roadmap Details
about: 
title: TWE: Research: Create Roadmap Details
labels: 'feature: board / google drive / tools', 'feature: missing', 'size: missing', 'role: missing', 'milestone: missing'
assignees: 
---
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Find WIKI page for this issue by looking at role pages [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team) - then add the appropriate link to the resources section
- [ ] Find document template that should be used [Templates & Product Branding](https://github.com/hackforla/internship/wiki/Design-Process-Overview) - then add that specific template link into the resources section
- [ ] If no dependencies, delete dependency section
- [ ] any place you see `[replace...]` replace both the text and the brackets with what it is asking for (including in the front matter above but not where it says name, but not where it says title.
- [ ] add appropriate labels and remove the corresponding missing labels
- [ ] delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources

```
### Resources
- [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)

<details>
<summary>Front Matter Fields and Meaning</summary>

- name: (name that appear on the new issue tab)
- about: (is the description that appears next to the issue template on the new issue tab
- title: (the title that appears when the issue is created.  User then customizes this title for their issue)
- labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
- assignees: 
</details>

<details>
<summary>Front Matter Field example</summary>

- name: 'Research: Roadmap'
- about: The start of a new roadmap
- title: 'TWE: Research Roadmap [name of type]'
- labels: 'feature: research, feature: roadmap, milestone: missing, role: UI/UX research,
-   size: 0.50pt'
- assignees: ''
</details>

**Comment by bradyse** [comment]
Draft of `Research: Create Roadmap Details` template issue
---
name: TWE: Create Template Issue: Research: Create Roadmap Details
about: 
title: TWE: Research: Create Roadmap Details
labels: 'feature: board / google drive / tools', 'feature: missing', 'size: missing', 'role: missing', 'milestone: missing'
assignees: 
---
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Find WIKI page for this issue by looking at role pages [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team) - then add the appropriate link to the resources section
- [ ] Find document template that should be used [Templates & Product Branding](https://github.com/hackforla/internship/wiki/Design-Process-Overview) - then add that specific template link into the resources section
- [ ] If no dependencies, delete dependency section
- [ ] any place you see `[replace...]` replace both the text and the brackets with what it is asking for (including in the front matter above but not where it says name, but not where it says title.
- [ ] add appropriate labels and remove the corresponding missing labels
- [ ] delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
- [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)

**Comment by bradyse** [comment]
This draft of an [issue template](https://github.com/hackforla/internship/issues/323#issuecomment-1279883725) has been created. The plan is to use this template for ALL research plans across all roadmaps.

**Comment by ExperimentsInHonesty** [comment]
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Go to the [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
  - [ ] Find the relevant overview type wiki page. 
  - [ ] Change `[Wiki [TYPE] Research Overview Page]` in the Resources below with the correct wiki page of the research overview by type.
- [ ] Go to the Research Output Overview Page again
   - [ ] Find the relevant wiki page for this specific research plan. 
   - [ ] Change the `[RP__ Wiki Page]` in the Resources below with this RP's specific wiki page.
- [ ] From the RP Wiki page, find the Google Doc of the Research Roadmap - then add that specific link into the resources section
- [ ] Add the appropriate dependencies and check them off if or when they are finished
- [ ] Any place you see `[replace...]` replace both the text and the brackets with what it is asking for.
- [ ] Add label of the correct research plan number associated with this research plan (e.g., Research: RP001).
- [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part).

### Dependencies
- [ ] [REPLACE WITH ROADMAP ISSUE #]
- [ ] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created an approved [REPLACE WITH RESEARCH STRUCTURE ISSUE # IF AVAILABLE]

### Overview
We need to updated the details of the [TYPE] Roadmap for [NAME OF RESEARCH PLAN] so that [GENERAL RESEARCH GOAL].

### Action Items
- [ ] Briefly review all relevant wiki documentation related to this type of research.
- [ ] Review the roadmap document's front matter and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
     - [ ] Review the brief summary about the project/product.
     - [ ] Review the overall goals and/or objectives of the type of research.
     - [ ] Review the summary of the target participants.
     - [ ] Review research framework and methodologies.
- [ ] For this research plan, draft the following according to the template (be sure to include questions as comments for the UX Research Lead to review):
     - [ ] Goals
     - [ ] Requirements
     - [ ] Timelines
     - [ ] Delivery
     - [ ] Follow-up Options
     - [ ] Research Analysis 
- [ ] Review with UX Research Lead
- [ ] Product Sign-off

### Resources
- [Wiki [REPLACE WITH TYPE] Research Overview Page]
- [RP___ [REPLACE WITH ###] Wiki Page]
- [TWE: Research Roadmap [REPLACE WITH TYPE]]
- [Example Research Roadmap (Interns)](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)

**Comment by bradyse** [comment]
This issue is done and can be closed.

**Comment by bradyse** [comment]
Updated [Create a template issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+board+%2F+google+drive+%2F+tools%2C+feature%3A+missing%2C+milestone%3A+missing%2C+role%3A+missing%2C+size%3A+missing&template=create-a-template-issue.md&title=TWE%3A+Create+Template+Issue%3A+%5Bname+of+template%5D) by adding the "Get started" link to the action items.
