### ISSUE TITLE
[draft] TWE: Make Issues to Update Research Roadmap Details of Research Plans

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#326]
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Find WIKI page for this issue by looking at role pages [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team) - then add the appropriate link to the resources section
- [ ] Find document template that should be used [Templates & Product Branding](https://github.com/hackforla/internship/wiki/Design-Process-Overview) - then add that specific template link into the resources section
- [ ] If no dependencies, delete dependency section
- [ ] delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ExperimentsInHonesty** [comment]
- [ ] Background
    - [ ] [Type] Research Goals and Objectives
    - [ ] Participants
    - [ ] Research Framework and Methodologies

```
    - [ ] RP[Replace 000] is missing the following info
       - [ ] Goals
       - [ ]  Requirements
       - [ ] Timelines
       - [ ] Delivery
       - [ ] Follow-up Options
       - [ ]  Research Analysis 
       - Add notes about other problems or missing info: 
```

**Comment by ExperimentsInHonesty** [comment]
### Action Items
#### Find it
- [ ] Click on Resource # 1 to locate the Roadmap document.
    - [ ] Click in the folder `1. Research by Type`.
    - [ ] Click on the subfolder of the research type to find the roadmap Google Doc.
    - [ ] Add the Roadmap Google Doc to this issue under Resource # 4.

### Check & Fix
    - [ ] Confirm that the document uses the following naming convention: `TWE: Research Roadmap: [TYPE]`. If it does not follow that format, change the filename to match the project's naming convention.
- [ ] Click inside the roadmap document and scroll through the document to determine whether the document contains the same headings as the TWE: Template: Research Roadmap (Resource # 2). If the document does not have the correct headings, then adjust the headings according to the template.
    - [ ] Background
    - [ ] [Type] Research Goals and Objectives
    - [ ] Participants
    - [ ] Research Framework and Methodologies
    - [ ] Individual Research Plans 
        - [ ] Make sure that all the research plans section titles are named `RP0... : [NAME] and are formatted as Header 2
    - [ ] Resources
    - [ ] Notes
 
### Reporting 
- [ ] Compare document RP sections against the Overview by Type wiki page (Resource # 3) and note discrepancies in your issue.
 - [ ] Each individual research plan section has the following sections, with Header 3 formatting.  Identify and record which sections of the roadmap document have boilerplate text that needs to be replaced by copying the report template and creating a comment on this issue (resource X):
   - Goals
   - Requirements
   - Timelines
   - Delivery
   - Follow-up Options
   - Research Analysis 
- [ ] Read through any sections that are finished to see if they make sense. Check for typos, completeness, and general formatting and make a note in your report comment
- [ ] Bring to UXR Team meeting for UXR lead to review.
   - [ ] Lead will direct you to make new issues for each Research Plan that is not properly documented in the Roadmap
```

### Resources/Instructions
1. [Google Drive, Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing)
1. [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)
1. [[replace with TYPE] Research Overview Wiki Page]
1. [TWE: Research Roadmap: [replace with TYPE]]

#### Report Template (copy as many times as needed for each RP in the roadmap
```
    - [ ] RP[Replace 000] is missing the following info (has boilerplate)
       - [ ] Goals
       - [ ]  Requirements
       - [ ] Timelines
       - [ ] Delivery
       - [ ] Follow-up Options
       - [ ]  Research Analysis 
       - Add notes about other problems (typos, completeness, and general formatting) or missing info: 
```

**Comment by ExperimentsInHonesty** [comment]
@bradyse I removed the dependency since all the other issues got closed.  And I removed the ready for milestone because you are going to finish the draft and then I will look at it again.

**Comment by ExperimentsInHonesty** [comment]
Since Sara is only doing planning, this is ready for us to test and see if it needs revision before making a template

**Comment by bradyse** [comment]
@pandanista 
1. Progress: Made a lot of progress with this draft.
2. Blockers: I need to add the instructions about replacing the keywords and review dependencies
3. Availability: 2-3 hours this week
4. ETA: 1 week
5. Pictures or links (if necessary): [Comment with draft of template](https://github.com/hackforla/internship/issues/326#issuecomment-1333026468)

_* remember to add links to the top of the issue if they are going to be needed again._

**Comment by bradyse** [comment]
@pandanista @cbutcher318 
This draft template (in comment [here](https://github.com/hackforla/internship/issues/326#issuecomment-1333026468)) should be ready for testing. 

Once the draft template is approved, then we can move forward with the rest of the action steps in this issue.

**Comment by cbutcher318** [comment]
Ready to be tested
