### ISSUE TITLE
TWE: Create Research Roadmap: Other

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#327]
### Overview
We need to create a research roadmap document for all research plans that encompass "Other" research (i.e., research that is not directly tied to one audience or participant type). We need to do this so that future researchers on this project can easily pick up where former researchers left off.

### Action Items
- [x] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [x] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [x] link it to the Research Output Overview wiki page
- [x] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [x] Put back in Prioritized Backlog under new milestone
- [x] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [x] Create a new folder in the drive called [number. name of type] and put a link to it in the resources for yourself
- [x] Make a new document using the report template 
  - [x] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [x] Name your document to be called TWE: Research Roadmap: [name of type] 
- [x] Add the headings to the individual research plans that reflect the research plans located on the Roadmap wiki page
- [x] Update the Table of contents (page 2) when you are finished with document
- [x] UX Research Lead sign-off

#### Wiki Roadmap Page
- [Wiki Roadmap Page: Other Research Overview](https://github.com/hackforla/internship/wiki/Other-Research-Overview)

#### Resources to Complete Issue
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)
- [Google Drive, Research by Type, 5. Other folder](https://drive.google.com/drive/folders/1Vb9TVPskfealzK2skTk5R6uN_RqKsodO?usp=sharing)
- [TWE: Template: Research Roadmap: [TYPE]](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)
- [TWE: Research Roadmap: Other](https://docs.google.com/document/d/1j0FOrYd6eyoSb3u8Ek0QDZeFq9_9Qecz8JtUG021ZoA/edit)

**Comment by bradyse** [comment]
Add the document headings that reflect the research plans listed on the wiki roadmap page.

**Comment by dialectic51** [comment]
Provide Update
1. Progress: Just need to add document headings that reflect research plans and fix formatting
2. Blockers: It was unclear whether I needed to actually write the research roadmap, but this has been clarified
3. Availability: Plenty
4. ETA: Tomorrow

**Comment by dialectic51** [comment]
Finished. Now just need UX Research Lead sign off. @bradyse

**Comment by dialectic51** [comment]
Added link to research roadmap document on the Other Research Overview wiki page 	https://github.com/hackforla/internship/wiki/Other-Research-Overview 

Completed issue #327 (needs review from UX Researcher Lead)
