### ISSUE TITLE
TWE: Create Research Roadmap Other HfLA Team

### ISSUE THREAD

**Issue by bradyse** [hackforla/internship#328]
### Overview
We need to create a research roadmap document for all research plans that encompass Other HfLA Team research. We need to do this so that future researchers on this project can easily pick up where former researchers left off.

### Action Items
- [x] Under "Projects," add to the Project Management Board
- [x] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [x] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [x] link it to the Research Output Overview wiki page
- [x] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [x] Put back in Prioritized Backlog under new milestone
- [x] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [x] Create a new folder in the drive called [number. name of type]
- [x] Make a new document using the report template 
  - [x] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [x] Name your document to be called TWE: Research Roadmap: [name of type] 
- [x] Update the Table of contents (page 2) when you are finished with document
- [x] UX Research Lead sign-off
- [ ] Product-sign off

### Research Roadmap
- [TWE: Research Roadmap: Other HfLA Team Research](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit?usp=sharing)

### Resources/Instructions
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [Wiki for Roadmap of Other HfLA Team Research](https://github.com/hackforla/internship/wiki/Other-HfLA-Team-Research-Overview)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)
- [Google Drive, Research by Type, 4. Other HfLA Team](https://drive.google.com/drive/folders/10hqcOE54U71UZd_Vtu4WPsXSopXZnDdk?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
We are closing this issue.  The roadmap will get more filled out when the audit is done.

**Comment by pandanista** [comment]
@dialectic51 Assigning you back to this issue. FYI: Jiah is having a blocker regarding timeline. I am thinking to have a 30 min meeting together to map out the timeline for some milestones.

**Comment by pandanista** [comment]
@adarosh @dialectic51 The action items above was only for making the structure of a roadmap doc. We need to add more action items for adding details for the roadmap. Let me know if it makes more sense to create a new issue for adding details for the roadmap doc.

**Comment by pandanista** [comment]
Found the add details for roadmap issue #380, sorry for the back and forth communication.
