### ISSUE TITLE
Design Audit

### ISSUE THREAD

**Issue by cbutcher318** [hackforla/internship#358]
### Overview
We need to audit the existing design work, and notes left by prior project designers, to create plan for upcoming design work.

### Action Items
- [x] Review notes from prior designers in #126 
- [x] Review Design System Figma (see resource)
- [x] Review [Design Process Overview wiki page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)
- [ ] Add any elements or interactions that are missing in the below checklists
- [x] Identify and label status of design elements/interactions
- [x] Update relevant WIKI page (See resources)
- [ ] Create a list of not-done elements in the "Create issues for any elements above that are not done" section below
- [ ] Create a new github issue for each not-done element 
- [ ] Paste the links to the design issue in the list

#### Elements to create
- Check off items that are "done"
- [ ] Secondary Buttons
- [ ] Text input fields
- [ ] Text Area
- [ ] Cards, lists
- [ ] Selection Area
- [ ] Dropdowns
- [ ] Modals
- [ ] Shape Style

#### Define interactions states of interactive elements
- Check off items that are "done"
- [ ] Hover States
- [ ] Clicks
- [ ] Selection State
- [ ] Disabled/Activated
- [ ] Drag
- [ ] Pressed

#### Create a UX Writing language guide for website
(check documents about project's voice)
- [x] Text used for buttons, commands, error messages etc.
- [ ] Copywriting for cards, messages, text boxes

#### Create issues for any elements above that are not done
- [ ] Copy and paste items from above that are not done into the "list of item issues to complete"
- list of item issues to complete, and link the list item to the issue
   - [ ] (start copying items here)

### Resources/Instructions
- #126 
- [Design System page in Figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A11)
- [Hack for la website figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
- [design guidance figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A40&t=8Kxgo8sxf2hlIKH4-0)
- [2023 TWE One Sheet](https://docs.google.com/document/d/1eIHIq3zKZ4fB7fMYRuU1WgDYK5XTMFsSQmCvo5iuMz4/edit)
- [2023-02-27 Meeting Recording/Explanation of Work](https://us02web.zoom.us/rec/share/jr4SpWuE5ZmWiubAGKhnPbUQKQiePloc3F_Aeej5zRsuNIXB2p_ELJumiNwSeHgz.w4092ivCbWb9spNX?startTime=1677524763000
Passcode: =z4Q78j!)
- [Trello Board](https://trello.com/b/J0d8JSik/kanban-dev-board)
   - design team is using to organize design system elements

**Comment by cbutcher318** [comment]
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
3. Blockers: Directions to design guidelines for creating the components
4. Availability: Unknown, 1-2 hours
5. ETA: 1-2 weeks

**Comment by bryannalim** [comment]
went through first round of audit and categorized by done, review, or needs to be created
- complete: style guide (image standards, typography, color palette), layouts and grids system (navigation, content), UX language (labels)
- in progress: component library (Robin)
- incomplete/blocker: UX Writing Language Guide for Website (Copywriting), Component Library Interaction States

**Comment by bryannalim** [comment]
Audit is completed (status is known for each part). UX Writing Language Guide for Website (Copywriting), Component Library Buttons & Interaction States, and Website Layouts incomplete due to insufficient information. Waiting on more comprehensive understanding of our users, journeys, and program structure + features to move forward with intentional designs.

**Comment by cbutcher318** [comment]
Reopening issue. Need to add action item to create issue for any design elements that still need to be created.

**Comment by ExperimentsInHonesty** [comment]
- Replaced by the epic #397
