### ISSUE TITLE
Create template issues for all research plans

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#359]
### Overview
We need to create template issues for all the research plans so that it is easier to create those issues for each research plans as needed.

### Action Items
- [ ] Create draft template issues for the following and determine what needs to be in each template

#### Creating Research Ops
- [x] Create a template Issue for a new process
   - [x] Issue #: #311
   - [x] Issue Template: [Issue: Create a template issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+board+%2F+google+drive+%2F+tools%2C+feature%3A+missing%2C+milestone%3A+missing%2C+role%3A+missing%2C+size%3A+missing&template=create-a-template-issue.md&title=TWE%3A+Create+Template+Issue%3A+%5Bname+of+template%5D)

#### Research Templates (in order that they will be used)
This does not include any audit issue templates

#### Setup
1. Create a Research Roadmap  
    - [x] Issue #: #323, 
    - [x] Issue Template: [Issue: Research: Create Roadmap Details](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research%2C+feature%3A+roadmap%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--create-roadmap-details.md&title=TWE%3A+Research%3A+Create+Roadmap+Details+for+RP%5B%23%23%23%5D)  
1. Roadmap timeline
    - [ ] Issue #: #370
    - [ ] Issue Template: 
    - [ ] Example of a timeline issue: #120 - this is for the whole project, we need one for a research roadmap, and individual timelines of each research plan
1. Setup Wiki Structure for all the Research Plans in the roadmap
    - [ ] Issue #: 
    - [x] Issue Template: [Issue: Research: Setup Structure](https://github.com/hackforla/internship/issues/new?assignees=&labels=epic%2C+feature%3A+research%2C+milestone%3A+missing%2C+p-feature%3A+wiki%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--setup-structure.md&title=TWE%3A+Research+Structure+for+%5Bname+of+research%5D)
1. Create Research Plan
    - [x] Issue #: #313
    - [x] Issue Template: [Issue: Research: Research Plan](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+board+%2F+google+drive+%2F+tools%2C+feature%3A+missing%2C+feature%3A+research+plan%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--research-plan.md&title=TWE%3A+Create+Research+Plan+for+RP%5B%23%23%23%5D)
1. Update Research Plans and Goals chart on Wiki  
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Notes: Update Research plans and goals chart from a spreadsheet
    - [ ] Example: [Intern Research List](https://docs.google.com/spreadsheets/d/1Y2VeHEUhmx4UX6y8CtbCHy2ilH76lWO4_xAVoqnLyME/edit#gid=1271462147)
    - [ ] Testing out in issue #374 

1. Research Plan timeline
    - [ ] Issue #: #372
    - [ ] Issue Template: 
    - [ ] Example of a timeline issue: #120 - this is for the whole project, we need one for a research roadmap, and individual timelines of each research plan
    - [ ] Testing out in issue #371 

#### Under 18 start of program consent
1. Consent form
    - [ ] Issue #: #379
    - [ ] Issue Template: 
    - [ ] Example: see the consent in the Guardian section of the WIKI (The issue to create the template should ask what the lowest age of the participant type is and if it's under 18, guide them through creating a formal consent form.  If all over 18, then the survey form will contain the consent at the top of the form.)  
       - [x] For example, parent consent [Form](https://forms.gle/AywubvHN7FUuFiiC6)  
       - [ ] #240 
     - [ ] Notes: there needs to be a dependency on the Research Plans & Goals for participant type, being completed
1. Parent email collection and email addressed to parents
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Example: #240 

#### Consent documents for participants over 18
1. Consent documents
    - [ ] Issue #: #368
    - [ ] Issue Template: 
    - [ ] Example: see the consent in the Guardian section of the WIKI (The issue to create the template should ask what the lowest age of the participant type is and if it's under 18, guide them through creating a formal consent form.  If all over 18, then the survey form will contain the consent at the top of the form.)  
       - [x] For example, mentor consent [Script](https://docs.google.com/document/d/1c6SKPty8dP6J58x5n7FrcomH6ryc0iZW_ZrvrE58M0Q/edit) and [Form](https://docs.google.com/forms/d/13Hj9alj786A2a24upGr4CuC56TgjpIHnkbZR9thPoEU/edit)  
    - [ ] Testing out in issue #373  

#### Interview prep
1. Roll Call and Session Table
    - [x] Issue #: #343 
    - [x] Issue Template: [Issue: Research: Create Interview Roll Call and Session Table](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research%2C+feature%3A+roll+call+%2F+session+table%2C+milestone%3A+missing%2C+Participant+Type%3A+missing%2C+Research+000%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+0.25pt&template=research--create-interview-roll-call-and-session-table.md&title=TWE%3A+IS%5BReplace+YY%5D%3A+RP%5BReplace+000%5D%3A+%5BReplace+TYPE+OF+PARTICIPANT%5D+%5BReplace+TYPE+OF+INTERVIEW%5D+Interview+Roll+Call+and+Session+Table%3A+Create)
1. Interview Script/Form Template (this includes moderated usability testing)
    - [ ] Issue #: #367 create an issue to ask a team member to review interview script we have used so we can develop a template
    - [ ] Issue Template: 
    - [ ] Example:
    - [ ] Note: this template must contain instructions for creating a practice version after the sign off on the questions/form is done
1. Create an Interview Recording Upload Form
    - [ ] Issue #: #341
    - [ ] Issue Template: 
    - [ ] Example:
1. Interview Instructions Google Doc
    - [ ] Issue #: #366
    - [ ] Issue Template: 
    - [ ] Example: [TWE: Template: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF INTERVIEW] Interview Instructions](https://docs.google.com/document/d/1YKJZHejAAvX19NfPh1AKC4k3CuX0nrJQq9N3BXBAB2U/template/preview)
1. EasyRetro clean up
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Example: #362 
1. EasyRetro setup
    - [ ] Issue #: #361 (in the icebox now)
    - [ ] Issue Template: 
    - [ ] Dependency: #362 should be able to help us improve the template
1. Interview Training Slide Deck
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Example: [deck](https://docs.google.com/presentation/d/1kAo2QSam5rCAsffk14PQb-lqkVZykCNqsU_kHZQXmxY/edit?usp=share_link) | Issue where deck created #202

#### steps for the recruitment of UX researchers
1. Scheduling, Messaging & channels
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Example: #205, #206, #207, #252 
1. Training session
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Example: #252, #202
1. Assignment

#### If we are not interviewing a captive user type
1. Research Plan Recruitment Template (contains selection criteria, sampling, etc)
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Prework that creates a best practices guide, which will lead to creating a template for how to do it.#363
1. Research Plan Recruitment Outreach Template (messaging/email for recruitment)
    - [ ] Issue #: 
    - [ ] Issue Template: 
    - [ ] Prework that creates a best practices guide, which will lead to creating a template for how to do it.#363

### For all interviews
1. Make issues for each interview
    - [ ] Issue #: #321
    - [ ] Issue Template: 
    - [ ] Example: #142; #265 has step by step info for coordinating interview schedules
    - [ ] Note: the epic for this will have been made in the `steps for the recruitment of UX researchers` process

### Unmoderated surveys
1. Research Plan Survey questions and create google form
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example: [TWE: [name of survey] Template](https://docs.google.com/forms/d/1nkTq5hVeOOv7lYMkzSi0tngz3Xr3_y4T9wMW8xyAPwM/template/preview) (in Research > Template folder)
1. Unmoderated usability testing template
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example:
    - [ ] Note: e.g., usabilityhub

#### Data Collection and Preprocessing
1. Transcribe and de-identify interview transcripts
    - [ ] Issue #: #335
    - [ ] Issue Template: 
    - [ ] Example:
1. Data Cleaning
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example:

#### Data analysis and synthesis
1. Rapid Qualitative Analysis
    - [ ] Issue #: #338
    - [ ] Issue Template: 
    - [ ] Example:
1. Thematic Analysis
    - [ ] Issue #: #314
    - [ ] Issue Template: 
    - [ ] Example:
1. Survey Analysis and Synthesis Template
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example:
1. Usability Testing Synthesis    
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example:
1. Affinity Mapping Template
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example:
1. Persona/Target audience/Use cases 
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example:
1. Customer Journey Map
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example: 
1. Competitive Analysis Template
    - [ ] Issue #:
    - [ ] Issue Template: 
    - [ ] Example:
  
#### Reporting and dissemination 
1. Research Presentation Deck
    - [ ] Issue #: #329
    - [ ] Issue Template: 
    - [ ] Example:  
1. Update the wiki page for any research plan.  /*Is it under Product or Research? See this [column](https://github.com/hackforla/internship/projects/1#column-14736603)*/
    - [ ] Issue #: 
    - [ ] Issue Template: [Issue: Research: Update](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research+audits%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--update.md&title=Update+%5BReplace+with+RP+and+the+number+e.g.%2C+RP008%5D%3A+%5Bname+of+research%5D)
    - [ ] Example:  
- [ ] Review
- [ ] Create issue templates

### Resources/Instructions
- [Wiki Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- [Google Drive Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=share_link)
- [Google Drive Template Folder](https://drive.google.com/drive/folders/1T_Y25SFzCyUWk8a39JYKzH1rVBi1H1Qv?usp=share_link)
- [TWE: Research: Outstanding items for Research Plans](https://docs.google.com/spreadsheets/d/1EYACJCWPRNp-ybnBuiYwrxMLcW9Lh8BtdVup5h3e9EY/edit?usp=share_link)

**Comment by pandanista** [comment]
Please provide update:
1. Progress: Reviewed with Bonnie yesterday through # 7 in the Research Templates section
2. Blockers: None
3. Availability: 6 hours
4. ETA: Will take a few meetings to go through all of them. Will continue the review on next Monday.
5. Pictures or links* (if necessary):

**Comment by pandanista** [comment]
#206 might need to be added to the templates for future recruiting team members.

**Comment by ExperimentsInHonesty** [comment]
/*No draft issue template, but it is mentioned in interview instructions doc in #321. Is there a need for issue template? Or is it sufficient to just have a Google slide template and include in the interview instructions issue #366?*/



- https://github.com/hackforla/internship/issues/265

- How we recruited researchers: https://github.com/hackforla/internship/issues/252

- When making issue template for consent process, review this issue https://github.com/hackforla/internship/issues/240
- create a template issue for creating landing pages.  See example: https://github.com/hackforla/internship/issues/206

**Comment by ExperimentsInHonesty** [comment]
Setup
Interview prep
Interviews
Data Collection and Preprocessing
Data analysis and synthesis
Reporting and dissemination

**Comment by pandanista** [comment]
#265 has step by step info for coordinating interview schedules (Research Ops). The step by step info could be included in issue template #321's "Schedule Interview" section. 
#252 is included as examples for recruiting UXR issue templates that to be made.
#240 the steps listed are required for the recruitment process for participants under 18, and will be converted into a template.
#206 is included as an example for recruiting UXR issue templates that to be made. Would like more context on the issue.
#362 will be a repeated process, so it will be helpful to make it into a template.

**Comment by ExperimentsInHonesty** [comment]
Example of what the spreadsheet for the research plans and goals looks like
[Intern Research List](https://docs.google.com/spreadsheets/d/1Y2VeHEUhmx4UX6y8CtbCHy2ilH76lWO4_xAVoqnLyME/edit#gid=1271462147)

**Comment by ExperimentsInHonesty** [comment]
#### Research Templates (in order that they will be used)
This does not include any audit issue templates

#### Setup
1. Create a Research Roadmap  #323
1. Roadmap timeline #370
1. Setup Wiki Structure for all the Research Plans in the roadmap
1. Create Research Plan #313
1. Update Research Plans and Goals chart on Wiki  
1. Research Plan timeline #372

#### Under 18 start of program consent
1. Consent form
1. Parent email collection and email addressed to parents

#### Consent documents for participants over 18
1. Consent documents #368

#### Interview prep
1. Roll Call and Session Table #343
1. Interview Script/Form Template (this includes moderated usability testing) #367
1. Create an Interview Recording Upload Form #341
1. Interview Instructions Google Doc #366
1. EasyRetro clean up 
1. EasyRetro setup #361
1. Interview Training Slide Deck

#### steps for the recruitment of UX researchers
1. Scheduling, Messaging & channels
1. Training session
1. Assignment

#### If we are not interviewing a captive user type
1. Research Plan Recruitment Template (contains selection criteria, sampling, etc)
1. Research Plan Recruitment Outreach Template (messaging/email for recruitment)

### For all interviews
1. Make issues for each interview #321

### Unmoderated surveys
1. Research Plan Survey questions and create google form
1. Unmoderated usability testing template

#### Data Collection and Preprocessing
1. Transcribe and de-identify interview transcripts #335
1. Data Cleaning

#### Data analysis and synthesis
1. Rapid Qualitative Analysis #338
1. Thematic Analysis #314
1. Survey Analysis and Synthesis Template
1. Usability Testing Synthesis    
1. Affinity Mapping Template
1. Persona/Target audience/Use cases 
1. Customer Journey Map
1. Competitive Analysis Template
  
#### Reporting and dissemination 
1. Research Presentation Deck #329
1. Update the wiki page for any research plan.  [Issue: Research: Update](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research+audits%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--update.md&title=Update+%5BReplace+with+RP+and+the+number+e.g.%2C+RP008%5D%3A+%5Bname+of+research%5D)


-

**Comment by ExperimentsInHonesty** [comment]
Research Templates (in order that they will be used)
This does not include any audit issue templates

Setup
 Create a Research Roadmap
 Roadmap timeline
 Setup Wiki Structure for all the Research Plans in the roadmap
 Create Research Plan
 Update Research Plans and Goals chart on Wiki
 Research Plan timeline

Under 18 start of program consent
 Consent form
 Parent email collection and email addressed to parents

Consent documents for participants over 18
 Consent documents

Interview prep
 Roll Call and Session Table
 Interview Script/Form Template
 Create an Interview Recording Upload Form TWE: Create Template Issue: Create Upload form #341
 Interview Instructions Google Doc TWE: Create Template Issue: Create Interview Instructions #366
 EasyRetro clean up
 EasyRetro setup TWE: Create Template Issue: Create Q&A in Easy Retro for interviews #361
 Interview Training Slide Deck

Steps for the recruitment of UX researchers
 Scheduling, Messaging & channels
 Training session
 Assignment

If we are not interviewing a captive user type
 Research Plan Recruitment Template (contains selection criteria, sampling, etc)
 Research Plan Recruitment Outreach Template (messaging/email for recruitment)

For all interviews
 Make issues for each interview

Unmoderated surveys
 Research Plan Survey questions and create google form
 Unmoderated usability testing template

Data Collection and Preprocessing
 Transcribe and de-identify interview transcripts TWE: Template Issue: Research: Interview Recordings: Transcribe #335
 Data Cleaning

Data analysis and synthesis
 Rapid Qualitative Analysis TWE: Research: Checklist for Rapid Qualitative Analysis (RQA) #338
 Thematic Analysis TWE: Create Guide for Thematic Analysis #314
 Survey Analysis and Synthesis Template
 Usability Testing Synthesis
 Affinity Mapping Template
 Persona/Target audience/Use cases
 Customer Journey Map
 Competitive Analysis Template

Reporting and dissemination
 Research Presentation Deck TWE: Template Issue: Research: Presentation Slide Deck: Create #329
 Update the wiki page for any research plan

**Comment by doctorsandy** [comment]
Here are my comments for this issue: https://docs.google.com/document/d/1YUk6-t3tMQ3ZCjopG-wN1FJYyHeahlIlk8xXlNFrZyo/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
@doctorsandy Please move your document to the Google Drive

**Comment by doctorsandy** [comment]
@ExperimentsInHonesty Happy to do that. Just want to double check, where would be a good place to put feedback in the Google drive?

**Comment by ExperimentsInHonesty** [comment]
@pandanista @doctorsandy are you still waiting for an answer to sandy's question above?    I thought we talked about this at a meeting.  If we did not.  Here is my answer, this is for Ying to decide.

**Comment by pandanista** [comment]
@priyatalwar This issue was reviewed, and to better facilitate the tracking, we decided to conduct the research audits instead. See [TWE: Research: Outstanding items for Research Plans](https://docs.google.com/spreadsheets/d/1EYACJCWPRNp-ybnBuiYwrxMLcW9Lh8BtdVup5h3e9EY/edit?usp=share_link), which is included in the resources section. If we are using the sheet to track the progress, then this issue might not be needed anymore. Please let me know if we need to close this one and open a new issue or leave this one open for tracking templates making.

For more context: I created this issue to identify what issue templates are needed and also to track the issue templates once made. But since then, we started using the spreadsheet for research audits and template tracking.

**Comment by pandanista** [comment]
YO will include he spreadsheet onto the wiki for TWE research output. Then we can close this issue.

**Comment by pandanista** [comment]
Added the [TWE: Research: Outstanding items for Research Plans](https://docs.google.com/spreadsheets/d/1EYACJCWPRNp-ybnBuiYwrxMLcW9Lh8BtdVup5h3e9EY/edit?usp=share_link) to the Research output overview wiki page, see screenshot below:
<img width="700" alt="Screenshot 2023-06-01 at 10 49 14 AM" src="https://github.com/hackforla/internship/assets/57029070/08c42944-46c2-4fab-8f01-8a17556babe0">

We can close this issue as it is not needed anymore.
