### ISSUE TITLE
TWE: Research: Create Roadmap Details for RP019

### ISSUE THREAD

**Issue by AndrewSalvatore** [hackforla/internship#375]
### Dependencies
- [x] #309
- [x] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created and approved. See #289.  

### Overview
We need to update the details of the `Intern Roadmap` for `RP019` so that the high level overview captures why we are doing all the research plans with this user group.

### Action Items
- [x] Briefly review all relevant wiki documentation related to this type of research.
- [x] Review the following sections and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
     - [x] Review the brief summary about the project/product.
     - [x] Review the overall goals and/or objectives of the type of research.
     - [x] Review the summary of the target participants.
     - [x] Review research framework and methodologies.
- [x] Find your research plan's subsection. Review and revise as necessary. Include questions as comments for the UX Research Lead to review:
     - [x] Goals
     - [x] Requirements
     - [x] Timelines
     - [x] Delivery
     - [x] Follow-up Options
     - [x] Research Analysis 
- [x] Review with UX Research Lead
- [x] Product Sign-off

### Resources
- [Wiki Intern Research Overview Page](https://github.com/hackforla/internship/wiki/Intern-Research-Overview)
- [RP019 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-19:-Technical-Skills-of-Incoming-Interns)
- [TWE: Research Roadmap: Intern](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#heading=h.4qi601o1qcet)
- [Example Research Roadmap (Interns)](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)

**Comment by AndrewSalvatore** [comment]
Progress: Started but need context before filling out RP19 portion of Intern Roadmap

Blockers: "Summary of Research" on RP19 wiki is blank

Availability: 6hrs

ETA: contingent upon gaining info of this RP

Pictures or links (if necessary):

**Comment by AndrewSalvatore** [comment]
Progress: Updated the roadmap info for this RP

Blockers: What is the Timeline for this RP's execution? What Data Analysis method are we using for these surveys?

Availability: 6 hours

ETA: ready for review by Thursday if unblocked

Pictures or links (if necessary): none

**Comment by pandanista** [comment]
Thank you for the update, @AndrewSalvatore. 

Please see my comments in [RP019's research roadmap doc](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing).

Also, thank you for creating research structure issues for #429 and #428 .

**Comment by AndrewSalvatore** [comment]
Thank you for the comments Ying. I just updated this RP's subsection on the Roadmap.

**Comment by AndrewSalvatore** [comment]
Progress: Updated RP019's wiki page based off RP019's roadmap subsection

Blockers: Lead review

Availability: 6 hours

ETA: Today, waiting for Lead review

Pictures or links (if necessary):

**Comment by pandanista** [comment]
Good job, Andrew. I made a few minor edits in the doc. Otherwise, the roadmap details look good. Time for product to sign off on this issue.

**Comment by ExperimentsInHonesty** [comment]
The only addition, is for t-test to get added to glossary. #306
