### ISSUE TITLE
TWE: Research: Create Roadmap Details for RP[018]

### ISSUE THREAD

**Issue by Dzotsen** [hackforla/internship#377]
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Make sure the title of this issue gets updated from Research: Create Roadmap Details for RP 018 to have the number of the research plan you are working from.
- [ ] Go to the [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
  - [ ] Find the relevant overview type wiki page. 
  - [ ] Change `[Wiki [TYPE] Research Overview Page]` in the Resources below with the correct wiki page of the research overview by type.
- [ ] Go to the Research Output Overview Page again
   - [ ] Find the relevant wiki page for this specific research plan. 
   - [ ] Change the `[RP__ Wiki Page]` in the Resources below with this RP's specific wiki page.
- [ ] From the RP Wiki page, find the Google Doc of the Research Roadmap - then add that specific link into the resources section
- [ ] Add the appropriate dependencies and check them off if or when they are finished
- [ ] Any place you see `[replace...]` replace both the text and the brackets with what it is asking for.
- [ ] Add label of the correct research plan number associated with this research plan (e.g., Research: RP001).
- [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part).

### Dependencies
- [ ] [REPLACE WITH ROADMAP ISSUE #]
- [ ] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created an approved [REPLACE WITH RESEARCH STRUCTURE ISSUE # IF AVAILABLE].  Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Structure+for+RP) to search the issue tab for potential results

### Overview
We need to update the details of the `Mentor Roadmap` for `Research RP018` so that the high level overview captures why we are doing all the research plans with this user group.

### Action Items
- [ ] Briefly review all relevant wiki documentation related to this type of research.
- [ ] Review the following sections and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
     - [ ] Review the brief summary about the project/product.
     - [ ] Review the overall goals and/or objectives of the type of research.
     - [ ] Review the summary of the target participants.
     - [ ] Review research framework and methodologies.
- [ ] Find your research plan's subsection. Review and revise as necessary. Include questions as comments for the UX Research Lead to review:
     - [ ] Goals
     - [ ] Requirements
     - [ ] Timelines
     - [ ] Delivery
     - [ ] Follow-up Options
     - [ ] Research Analysis 
- [ ] Review with UX Research Lead
- [ ] Product Sign-off

### Resources
- [Wiki Mentor Research Overview Page] (https://github.com/hackforla/internship/wiki/Mentor-Research-Overview)
- [RP 018  Wiki Page] (https://github.com/hackforla/internship/wiki/Research-Plan-18:-Weekly-Feedback-from-Mentors)
- [TWE: Research Roadmap Mentor] (https://docs.google.com/document/d/1ywAYj0NMXQy53kVuEOmtVUdvGy51HqT67xak0EJrFXE/edit)
