### ISSUE TITLE
TWE: Research: Create Roadmap Details for RP020

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#380]
# Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- [ ] Make sure the title of this issue gets updated from Research: Create Roadmap Details for RP020 to have the number of the research plan you are working from.
- [ ] Go to the [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
  - [ ] Find the relevant overview type wiki page. 
  - [ ] Change `[Wiki [TYPE] Research Overview Page]` in the Resources below with the correct wiki page of the research overview by type.
- [ ] Go to the Research Output Overview Page again
   - [ ] Find the relevant wiki page for this specific research plan. 
   - [ ] Change the `[RP__ Wiki Page]` in the Resources below with this RP's specific wiki page.
- [ ] From the RP Wiki page, find the Google Doc of the Research Roadmap - then add that specific link into the resources section
- [ ] Add the appropriate dependencies and check them off if or when they are finished
- [ ] Any place you see `[replace...]` replace both the text and the brackets with what it is asking for.
- [ ] Add label of the correct research plan number associated with this research plan (e.g., Research: RP001).
- [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part).

### Dependencies
- [ ] [REPLACE WITH ROADMAP ISSUE #]
- [ ] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created an approved [REPLACE WITH RESEARCH STRUCTURE ISSUE # IF AVAILABLE].  Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Structure+for+RP) to search the issue tab for potential results

### Overview
We need to update the details of the `[TYPE] Roadmap` for `[NAME OF RESEARCH PLAN]` so that the high level overview captures why we are doing all the research plans with this user group.

### Action Items
- [ ] Briefly review all relevant wiki documentation related to this type of research.
- [ ] Review the following sections and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
     - [ ] Review the brief summary about the project/product.
     - [ ] Review the overall goals and/or objectives of the type of research.
     - [ ] Review the summary of the target participants.
     - [ ] Review research framework and methodologies.
- [ ] Find your research plan's subsection. Review and revise as necessary. Include questions as comments for the UX Research Lead to review:
     - [ ] Goals
     - [ ] Requirements
     - [ ] Timelines
     - [ ] Delivery
     - [ ] Follow-up Options
     - [ ] Research Analysis 
- [ ] Review with UX Research Lead
- [ ] Product Sign-off

### Resources
- [Wiki [REPLACE WITH TYPE] Research Overview Page]
- [RP___ [REPLACE WITH ###] Wiki Page]
- [TWE: Research Roadmap [REPLACE WITH TYPE]]
- [Example Research Roadmap (Interns)](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)

**Comment by pandanista** [comment]
Hi @dialectic51, removing you from this issue for now since we are focusing on research plan audits. Thank you for your contribution!

**Comment by pandanista** [comment]
@dialectic51 @adarosh Assigning you both to this issue. FYI: Jiah is having a blocker regarding timeline. I am thinking to have a 30 min meeting together to map out the timeline for some milestones, which should help the timeline for RP020.

**Comment by pandanista** [comment]
Hi @oij11 and @adarosh, let's finish revising this research roadmap doc this week since it is a dependency for RP020's research plan doc #320, which needs to be worked on next. Please review the current document and we can discuss it in more details at 4/18's UXR meeting as well. Thank you!

**Comment by pandanista** [comment]
As a summary of RP020's transition:

- Brian updated the team on the current statuses of [the research roadmap](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit?usp=sharing) and the [research plan](https://docs.google.com/document/d/1GK3jaUlJerLtUFZhIXXAM2oDZDeYBWyooPXH0Z3IFhw/edit?usp=sharing) documents

- Angela and Jiah will keep working on [the research roadmap document](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit?usp=sharing)
    - Angela will update the research roadmap document first, roadmap timeline included
    - Jiah will review after Angela is done
    - The team will ask Product/Bonnie for feedback and approval
    - Please keep in mind the purpose of the research roadmap document is to provide objectives for [the Product Goals and Metrics](https://docs.google.com/document/d/1GK3jaUlJerLtUFZhIXXAM2oDZDeYBWyooPXH0Z3IFhw/edit#bookmark=id.h9dezqf9zyu) in the research plan document, so make sure [the Goals section](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit#bookmark=id.w28zs0o0l9ii) in RP020's research roadmap can reflect the objectives and KPIs later in the research plan document.
    - If we can get feedback on this Thurday, 4/20, that would be the best
- Angela and Jiah will revise [the research plan document](https://docs.google.com/document/d/1GK3jaUlJerLtUFZhIXXAM2oDZDeYBWyooPXH0Z3IFhw/edit?usp=sharing) once the roadmap gets approved
    - Review the existing research plan document
    - Translate the goals into objectives and KPIs based on the roadmap document
    - Revise the research plan if needed (appendices included)
    - Estimate each research activity and finalize issue #371 
    - Incorporate the timeline generated in issue #371 into the doc
    - Peer review if needed
    - Product feedback and approval

**Comment by oij11** [comment]
Hi @adarosh and @pandanista, I reviewed it and made edits. However, although it says "the purpose of the research roadmap document is to provide objectives for [the Product Goals and Metrics](https://docs.google.com/document/d/1GK3jaUlJerLtUFZhIXXAM2oDZDeYBWyooPXH0Z3IFhw/edit#bookmark=id.h9dezqf9zyu) in the research plan document, I don't think KPIs should be the focus of this RP (see my comment in the plan document).  My understanding is that Brian thought the same way as well. Let me know what you think and if you want me to do anything on the roadmap before asking it for approval.

**Comment by priyatalwar** [comment]
@pandanista reviewed RP20 and left some comments on the doc. @ExperimentsInHonesty please review when you get a chance. Thanks!

**Comment by pandanista** [comment]
@adarosh Please fill out the background, goals/objectives, framework/methodologies in the roadmap detail doc. 
@jessieliu1219 Would you please review it once Angela is done?

Thank you both!

**Comment by adarosh** [comment]
Progress Update:

Progress: Completed background, goals/objectives, framework/methodologies in the roadmap using Mentor roadmap as an example. Looks like the Intern roadmap does not have these sections filled out.
Blockers: None
Availability: N/A
ETA: N/A
Pictures (if necessary): N/A

**Comment by pandanista** [comment]
Thank you for pointing out the missing part of the intern roadmap doc. @pandanista

**Comment by pandanista** [comment]
This issue needs a peer review
### Setup for a Peer Review
@pandanista to complete the steps below:
- [x] Confirm this document needs a peer review.
- [x] Check if the Issue Overview clearly defines why this document needs to be created or updated. If it is not clear, add that information to the overview in 1-2 sentences.
- [x] In the Resources, clearly identify the link to the document being created or updated that requires a peer review (use subheadings if needed).
- [x] Copy and paste the Action Items for Peer Review into a comment of the issue.
- [x] Customize the Action Items according (adding items that are more relevant to this issue and removing items that are less relevant).
     - [x] Replace the text in square brackets with the name of the document that requires a peer review (use the same name as it is called in the Resources).
     - [x] If you have a specific task that you want the Peer Reviewer to accomplish for their peer review that is nuanced to your issue, add that as a final action item to the list.
- [x] Determine who will do the peer review and unassign yourself to this issue and assign the peer reviewer to this issue.

### Action Items for Peer Review
 to complete the steps below:
- [ ] Review this issue
     - [ ] Read the issue overview to learn about why this document was created.
     - [ ] Locate draft of the document or spreadsheet in the Resources.
- [ ] Review draft
     - [ ] Preview the draft quickly to get a sense of how the draft is structured and the type of content.
     - [ ] Review the structure of the draft to ensure that the headings (in a Google Doc) or columns (Google Sheet) are clearly identified. 
     - [ ] Determine if the information is communicated in a way that is concise, precise, and free from jargon.
     - [ ] Identify whether the draft adheres to the basic branding guidelines for the project (see Branding or Design wiki link in Resources).
- [ ] Provide feedback
     - [ ] Add feedback in the form of (1) questions and/or (2) explicit instructions for how the content should be improved. **Feedback in a Google Doc should be given in the form of document comments**. Feedback in a Google Sheet should be given in the column labeled for Peer Review.
     - [ ] Determine the accuracy of the content for each section (Google doc) or row/column (Google sheet). If you find an inaccuracy, error, or mis-categorization, explain how the information presented could be improved.
     - [ ] For each suggested improvement, provide a link or reference within your comment to justify your suggestion (if available).
- [ ] Specific to this issue: 
     - [ ] Review open and closed issues related to [RP002](https://github.com/hackforla/internship/labels/Research%3A%20RP002) and [RP020](https://github.com/hackforla/internship/labels/Research%3A%20RP020) in GitHub to familiar yourself with what has been done and what needs to be done. 
     - [ ] Review documents linked in the open and closed issues and in the comments within the issues to gather more information
     - [ ] Review content and links on [HfLA volunteer research output wiki page](https://github.com/hackforla/internship/wiki/HfLA-Volunteers-Research-Overview) and RP002 and RP020's wiki pages
     - [ ] Please provide concrete feedback based on the reviews you have done above.
     - [ ] [Per Bonnie's comment](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit?disco=AAAAvYIs26c), we don't need specific questions in the research roadmap doc, just general questions to address the research goals. Move those specific questions she listed out from the research roadmap doc to the [WIP research plan](https://docs.google.com/document/d/1GK3jaUlJerLtUFZhIXXAM2oDZDeYBWyooPXH0Z3IFhw/edit?usp=sharing)'s interview protocol section to group them with other questions so we don't lost them. 
- [ ] Once all the steps have been completed, reach out to the original owner of this issue to determine if they can complete the next steps in the issue.

**Comment by pandanista** [comment]
@jessieliu1219 One more ask on this issue: While reviewing the doc, would you please fill out the "Goals and Metrics" section in the [TWE: Research Roadmap: HfLA Volunteers](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit?usp=sharing)? Feel free to edit the goals/objectives as you see fit.

Bonnie suggested including goals and metrics in the research roadmap doc, so it can provide guidance to each individual research plans. Let's test it out by including them in this TWE: Research Roadmap: HfLA Volunteers doc. Thank you.

**Comment by pandanista** [comment]
@jessieliu1219 Please prioritize this issue as this is more urgent than #398 at the moment. Thank you!

**Comment by jessieliu1219** [comment]
@pandanista Hi Ying, I've left comments and updates on the roadmap, thanks!

**Comment by pandanista** [comment]
I've reviewed the research roadmap doc with @adarosh and @AndrewSalvatore on 7/28. We have incorporated reviewer's comments and made edits. 

Next step is to get product's approval on the research roadmap so we can align product goals with research goals.
