### ISSUE TITLE
Design Team Meeting Agenda

### ISSUE THREAD

**Issue by cbutcher318** [hackforla/internship#391]
Copy and paste template below into a new comment for each meeting
Assign a member of the team to take meeting notes and record action items

```
[DATE] Agenda and Notes

### Prework
- [ ] 

### Roll Call
- [ ] Bryanna
- [ ] Minji
- [ ] Robin
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
 - [ ] 

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ] 
```

**Comment by priyatalwar** [comment]
[2023-03-20 Design Meeting Agenda & Notes ] 

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [ ] Bryanna
- [ ] Minji
- [ ] Robin
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Robin(https://github.com/hackforla/internship/issues/assigned/RobinElayn)
 - [ ] Brynna(https://github.com/hackforla/internship/issues/assigned/bryannalim)
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by karina-sato** [comment]
[DATE] Agenda and Notes

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [ ] Bryanna
- [ ] Minji
- [ ] Natalie
- [ ] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Robin(https://github.com/hackforla/internship/issues/assigned/RobinElayn)
 - [ ] Brynna(https://github.com/hackforla/internship/issues/assigned/bryannalim)
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- Update issue 408 - Design System - Footer and move card to Review

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by karina-sato** [comment]
[DATE] Agenda and Notes

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [ ] Natalie
- [ ] Minji
- [ ] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Robin(https://github.com/hackforla/internship/issues/assigned/RobinElayn)
 - [ ] Brynna(https://github.com/hackforla/internship/issues/assigned/bryannalim)
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- Karina to check with Design/Dev meeting requirements for Design System Microsite (Minji) (Navbar and Code) and Footer (Natalie) updates

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by karina-sato** [comment]
[09-05-2023] Agenda and Notes

### Roll Call
- [ ] Natalie
- [x] Minji
- [x] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

### Notes from meeting
- no updates on Footer
- Minji is working on the Accordion's Microsite for the Dev Team
- Karina updated on cards and will get feedback on the all team meetings on Thu

**Comment by ExperimentsInHonesty** [comment]
### Add to next agenda
- Please review these issues
   -  #413
   - #403

**Comment by karina-sato** [comment]
[DATE] Agenda and Notes

First Week of the Month: No meeting

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [ ] Natalie
- [ ] Minji
- [ ] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)
 - [ ] Karina(https://github.com/hackforla/internship/issues/assigned/karina-sato)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by karina-sato** [comment]
[2024-05-14] Agenda and Notes

First Week of the Month: No meeting

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [ ] Michael
- [ ] Minji
- [ ] Salome
- [ ] Kimberly
- [ ] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)
 - [ ] Karina(https://github.com/hackforla/internship/issues/assigned/karina-sato)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by SalomeM-UXD** [comment]
Hi Karina, I am currently moved to the UX research team.  I think I can be removed from this Meeting agenda for the time being

________________________________

**Comment by satokarina** [comment]
[2024-05-28] Agenda and Notes

First Week of the Month: No meeting

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [ ] Michael
- [ ] Minji
- [ ] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)
 - [ ] Karina(https://github.com/hackforla/internship/issues/assigned/karina-sato)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
-

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by karina-sato** [comment]
[2024-05-28] Agenda and Notes

First Week of the Month: No meeting

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [x] Michael
- [x] Minji
- [x] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)
 - [ ] Karina(https://github.com/hackforla/internship/issues/assigned/karina-sato)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- Discussed the differences between modals, pop-ups, dialogs, and notification cards considering material design guidelines. Defined that Michael will update modals according to material design guidelines and that modals will now call dialogs. The notification cards issue is not to be continued. 
- Minki is working on updating the header, creating the component layout, and microsite layout for the dev team. 
- Karina needs to create issue to add text button for the dev team

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by karina-sato** [comment]
[2024-06-18] Agenda and Notes

First Week of the Month: No meeting

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [ ] Michael
- [ ] Minji
- [ ] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)
 - [ ] Karina(https://github.com/hackforla/internship/issues/assigned/karina-sato)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by karina-sato** [comment]
[DATE] Agenda and Notes

First Week of the Month: No meeting

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
- [x] Michael
- [x] Minji
- [x] Karina
#### Optional
- [ ] Bonnie
- [ ] Priyanka
- [ ] Christian
- [ ] Kathleen

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] Minji(https://github.com/hackforla/internship/issues/assigned/meetminji)
 - [ ] Karina(https://github.com/hackforla/internship/issues/assigned/karina-sato)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- Discussed different modals/dialogs considering visual hierarchy and what we're trying to communicate to users

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]
