### ISSUE TITLE
Create Roadmap for Design

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#392]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
As a product manager, I need to create a roadmap every 6 months so that those managing the internship project can work more efficiently. Define milestones, goals and features for MVP and future product iterations. 

Action Items
- [x]  Define goal of project
- [x]  Define Objectives
- [x] order the objectives in terms of priority
- [x] Create high level milestones
- [x] Define in detail what goes into each milestone (for the ones that can be done now)
- [ ] Review milestone and make epics for making the issues that will deliver the milestone

[onesheet](https://docs.google.com/document/d/1vovX2o0qiw4z9BUrH1Wb5RL9AzaveguQ1KMZ27nj11w/edit#heading=h.9lflh9bmk0a)

### Resources/Instructions
[Guide roadmap](https://docs.google.com/document/d/1sZHHfqXoui4zsMQ2l_O3TRIJcXQnyOO-bF-KY9jl4qM/edit)
[Guides project Roadmap sheet as example](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
[Internship Roadmap](https://docs.google.com/spreadsheets/d/1GijHiK_DRmlU8U0fZKsV9cjYhy9h3pZ5_OYQVx_mbgo/edit#gid=1192591317)

**Comment by cbutcher318** [comment]
Looks like you included the old one sheet. [Here is the current draft](https://docs.google.com/document/d/1eIHIq3zKZ4fB7fMYRuU1WgDYK5XTMFsSQmCvo5iuMz4/edit).

**Comment by cbutcher318** [comment]
At the next product meeting, can we identify requirements for this roadmap?

**Comment by ExperimentsInHonesty** [comment]
currently moving this to the icebox because a general product roadmap has not been built.  

It could still be worked on by design, if you want to start gathering specific questions here in this issue.
