### ISSUE TITLE
Create user journeys

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#393]
### Dependencies
- [ ] Define user groups #107 
- [ ] Define use cases #97 
- [ ] Identify personas #109 

### Overview
We need to create the user flows for all the personas we've identified so we can identify how each persona will interact with our site

### Action Items
- [ ] Identify user groups
- [ ] Identify use cases
- [ ] Create personas
- [ ] Create user stories

- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
[TWI: Personas, targets, reasons spreadsheet](https://docs.google.com/spreadsheets/d/1ajLL4MMGVUOE0A3N6UEcLqYjKiT3QRinx9uHAUaDjsA/edit#gid=0)
[Figjam - see scenarios page](https://www.figma.com/file/VgxjTXP3PJhzZxMeMURf2f/Branding-Exercise?node-id=0%3A1)

**Comment by ExperimentsInHonesty** [comment]
the action items seem very similar to the dependencies.  Review the dependencies and rewrite the issue
