### ISSUE TITLE
TWE: Research Structure for RP024: LinkedIn of Incoming Interns

### ISSUE THREAD

**Issue by AndrewSalvatore** [hackforla/internship#428]
### Overview
We need to create a wiki structure and task list to support our LinkedIn of Incoming Interns so that we can stay organized across all team member and working times.

### Action Items
- [x] Add the milestone: 06.01.01 Research Plan Create Wiki Pages.
- [x] Link the roadmap and its issue for your research into the resources below.
- [x] Create a label for your research plan, using the next number available. Check Google drive and wiki on Github to make sure the number is correct.
  - [x] Add label to this issue and to the roadmap issue.
- [x] Create a new wiki page for it.
- [x] Use the template to copy the structure.
- [x] Link new wiki page to [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview).
   - [x] Link it to the appropriate page under `Research Documents by Participant Type`.
   - [x] Link it under `Research Plan By Status` based on whether it is current or future research. If the research plan has been created or the data has been collected, then choose `Current Research`. If no research plan nor data has been collected, then choose `Future Research`.
   - [x] Link it under `Research by Plan Number`.
- [x] Fill out the wiki page with any links or documents that have already been created.
- [x] Go to the Google Drive > Internships > Research > Research by Participant Type
   - [x] Open the appropriate participant type folder for this RP
   - [x] Create a folder called "RP### - name of research"
   - [x] Right click the folder you just created and choose "Add shortcut to Drive"
   - [x] Go to All Locations > Shared drives > Internships > Internships > Research > Research by Plan # and name
   - [x] Click the "Add" button and then "Ok" to the pop-up
- [x] Customize issues that will need to be made by striking through unneeded issues from this list (put ~ before and after text to make it strikethrough).
  - [x] Research Plan (internal)
  - [x] Timeline
  - [x] Forms/Survey/Script
  - [x] Emails text to parents if participants are minor (if required) 
  - [x] Recruitment plan for extra UXRs and participants(if required)
  - [x] Identification of recruitment channels for UXRs and participants (if required)
  - [x] Messaging for each type of channel (i.e. Slack, social)
  - [x] Interest forms for UXRs
  - [x] Selection criteria for UXRs and participants
  - [x] Consent Plan for participants
  - [x] Research Plan (external) - this is a subset of the internal
  - [x] Consent Form
- [x] Update Outstanding Task Items on wiki page to reflect the necessary issues from the list above.
- [x] Have review meeting with Research Lead.
- [ ] Have alignment meeting with Product for sign-off.
- [ ] Create issues using templates from the list of template issues.

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- [Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)
- [TWE: Research Roadmap: Intern](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#)
- [Issue: Create Roadmap: Intern Research](https://github.com/hackforla/internship/issues/309)
- [RP024 wiki structure](https://github.com/hackforla/internship/wiki/Research-Plan-24:-LinkedIn-of-Incoming-Interns)

**Comment by AndrewSalvatore** [comment]
Progress: Completed up to Research Review

Blockers: Research Review

Availability: 6 hours

ETA: ready for Research Review

Pictures or links (if necessary): none

**Comment by pandanista** [comment]
Hi Drew, thank you for all your work. There are a few things need some revision and updates:

- The title say RP023, but the label says RP024. Looks like it should be RP024, please update the title. 
- The milestone is already added, so please remove the `milestone: missing label`.
- Please fill out the Research Roadmap, summary of research, Current Status on [RP024's wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-24:-LinkedIn-of-Incoming-Interns).
    - [Here](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews) is RP017's wiki page as an example. 
- I checked the template for research structure, and the portion on creating a folder on the google drive didn't seem to have been updated on the template for research structure. Would you please double check? 

Thank you very much!

**Comment by pandanista** [comment]
This issue is now ready for product to sign off as I've reviewed the issue with Drew on 6/11. Thank you.

**Comment by priyatalwar** [comment]
hi @pandanista Thanks for working on this issue. Sounds like you'd like to meet to get alignment on this issue? If so, is there anything specific you like from product on this issue?  Please let us know. Thanks!

**Comment by pandanista** [comment]
@priyatalwar I assume the alignment meeting is for product to provide feedback on RP024's wiki structure and align the goals of this research plan, so we could carry on with research roadmap doc creation. Is that correct? Happy to cover that on Monday, 7/24.

As I mentioned in the previous comment that the deliverable for this issue was the creation of [RP024 wiki](https://github.com/hackforla/internship/wiki/Research-Plan-24:-LinkedIn-of-Incoming-Interns). Please take a look and let me know if you have any questions. Thanks.

**Comment by priyatalwar** [comment]
@pandanista Thanks for the clarification. Got it. The wiki structure seems fine. I am not seeing any goals for this research plan since nothing is stated under questions and purpose or would that be clear once the roadmap is completed?

**Comment by pandanista** [comment]
The latter one to your question. The goals were discussed previously and will be specified in the research roadmap document. Issue #449 has been set up to tackle that. 

I am closing this issue since Product has approved the wiki structure. :)
