### ISSUE TITLE
TWE: Research Structure for RP022: Soft Skills of Incoming Interns

### ISSUE THREAD

**Issue by AndrewSalvatore** [hackforla/internship#429]
### Overview
We need to create a wiki structure and task list to support the development of a new research plan on Soft Skills of Incoming Interns so that we can stay organized and consistent across all team members and working times.

### Action Items
- [x] Add the milestone: 06.01.01 Research Plan Create Wiki Pages.
- [x] Link the roadmap and its issue for your research into the resources below.
- [x] Create a label for your research plan, using the next number available. Check Google drive and wiki on Github to make sure the number is correct.
  - [x] Add label to this issue and to the roadmap issue.
- [x] Create a new wiki page for it.
- [x] Use the template to copy the structure.
- [x] Link new wiki page to [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview).
   - [x] Link it to the appropriate page under `Research Documents by Participant Type`.
   - [x] Link it under `Research Plan By Status` based on whether it is current or future research. If the research plan has been created or the data has been collected, then choose `Current Research`. If no research plan nor data has been collected, then choose `Future Research`.
   - [x] Link it under `Research by Plan Number`.
- [x] Fill out the wiki page with any links or documents that have already been created.
- [x] Go to the Google Drive > Internships > Research > Research by Type
   - [x] Open the appropriate participant type folder for this RP
   - [x] Create a folder called "RP### - name"
   - [x] Right click the folder you just created and click "Add shortcut to Drive"
   - [x] Go to All Locations > Shared drives > Internships > Internships > Research > Research by Plan # and name
   - [x] Click the "Add" button and then "Ok" to the pop-up
- [x] Customize issues that will need to be made by striking through unneeded issues from this list (put ~ before and after text to make it strikethrough).
  - [x] Research Plan (internal)
  - [x] Timeline
  - [x] Forms/Survey/Script
  - [x] Emails text to parents if participants are minor (if required) 
  - [x] Recruitment plan for extra UXRs and participants(if required)
  - [x] Identification of recruitment channels for UXRs and participants (if required)
  - [x] Messaging for each type of channel (i.e. Slack, social)
  - [x] Interest forms for UXRs
  - [x] Selection criteria for UXRs and participants
  - [x] Consent Plan for participants
  - [x] Research Plan (external) - this is a subset of the internal
  - [x] Consent Form
- [x] Update Outstanding Task Items on wiki page to reflect the necessary issues from the list above.
- [x] Have review meeting with Research Lead.
- [ ] Have alignment meeting with Product for sign-off.
- [ ] Create issues using templates from the list of template issues.

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Internship Google Drive](https://drive.google.com/drive/folders/0ACgRrPVkhnrvUk9PVA)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- [Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)
- [TWE: Research Roadmap: Intern](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#)
- [Issue: Create Roadmap: Intern Research](https://github.com/hackforla/internship/issues/309)

**Comment by pandanista** [comment]
Imagine you are going through each action item and see what else is missing and what the step by step is like. Then jot down your thoughts in the thread so we can edit the template.

**Comment by AndrewSalvatore** [comment]
Progress: I've begun working through this and adding comments about the template

Blockers: none

Availability: 6 hours

ETA: next Tuesday

Pictures or links (if necessary): none

**Comment by AndrewSalvatore** [comment]
Progress: 

Blockers: What do these issues refer to:
- Messaging for each type of channel
- Interest forms
- Selection criteria
- Consent Plan
- Research Plan (external) - this is a subset of the internal

Availability: 6 hours

ETA: ready for review after blockers are unblocked

Pictures or links (if necessary): none

**Comment by pandanista** [comment]
Thank you for following up on this, Drew. I've reviewed the issue, and edited the wiki page.
 @AndrewSalvatore, there are a few more asks:
1. Would you please add RP022's wiki page's URL to `Future Research` of [Research Output Overview page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)? I think we should put it under Wiki since we are setting up this research plan's wiki page right now.
2. Would you please edit the following sections on RP022's wiki page? Here is an example of [RP012's wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-12:-Intern-Exit-Interviews) as a reference
<img width="200" alt="Screenshot 2023-05-30 at 5 31 48 PM" src="https://github.com/hackforla/internship/assets/57029070/c1972fb5-7570-48f3-a6ae-540d798e90ba">
<img width="200" alt="Screenshot 2023-05-30 at 5 31 30 PM" src="https://github.com/hackforla/internship/assets/57029070/ccfe634c-e304-4c79-9165-52e45b5c9847">
<img width="300" alt="Screenshot 2023-05-30 at 5 31 18 PM" src="https://github.com/hackforla/internship/assets/57029070/2fde0aeb-5428-415b-849c-a021fa4a599e">
3. While completing each action item in this issue and creating a new wiki page, where/when do you see as the most appropriate step/timing to create a folder on Google drive for a new research plan? 

Thank you very much!

**Comment by AndrewSalvatore** [comment]
> Thank you for following up on this, Drew. I've reviewed the issue, and edited the wiki page. @AndrewSalvatore, there are a few more asks:
> 
> 1. Would you please add RP022's wiki page's URL to `Future Research` of [Research Output Overview page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)? I think we should put it under Wiki since we are setting up this research plan's wiki page right now.
> 2. Would you please edit the following 3 sections on RP022's wiki page? Here is an example of [RP012's wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-12:-Intern-Exit-Interviews) as a reference.
> 
> <img alt="Screenshot 2023-05-30 at 5 31 48 PM" width="400" src="https://user-images.githubusercontent.com/57029070/242130063-c1972fb5-7570-48f3-a6ae-540d798e90ba.png"> <img alt="Screenshot 2023-05-30 at 5 31 30 PM" width="600" src="https://user-images.githubusercontent.com/57029070/242130072-ccfe634c-e304-4c79-9165-52e45b5c9847.png"> <img alt="Screenshot 2023-05-30 at 5 31 18 PM" width="600" src="https://user-images.githubusercontent.com/57029070/242130074-2fde0aeb-5428-415b-849c-a021fa4a599e.png">
> 3. While completing each action item in this issue and creating a new wiki page, where/when do you see as the most appropriate step/timing to create a folder on Google drive for a new research plan?
> 
> Thank you very much!

Hi Ying,

Sounds good, and I've made those changes.

I would say the best place to put a "create folder on Google Drive" action item would be the first bullet under: "Customize issues that will need to be made by striking through unneeded issues from this list (put ~ before and after text to make it strikethrough)".

Cheers,
Drew

**Comment by pandanista** [comment]
Thank you for the update, Drew! I took another look, and realized I missed a couple of things on the wiki page.

- Would you please fill out the Research Roadmap, summary of research, Current Status on [RP024's wiki page](https://github.com/hackforla/internship/wiki/Research-Plan-24:-LinkedIn-of-Incoming-Interns).
    - [Here](https://github.com/hackforla/internship/wiki/Research-Plan-17:-Productivity-Dashboard-Interviews) is RP017's wiki page as an example. 
 
Thank you very much!

**Comment by pandanista** [comment]
This issue is now ready for product to sign off as I've reviewed the issue with Drew on 6/11. Thank you.

**Comment by ExperimentsInHonesty** [comment]
Thanks @AndrewSalvatore The work is completed.
