### ISSUE TITLE
TWE: Research: Create Roadmap Details for RP002

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#441]
### Dependencies
- [ ] #328 
- [ ] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created an approved #288 .  Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Structure+for+RP) to search the issue tab for potential results

### Overview
We need to update the details of the `HfLA Volunteers Roadmap` for `INTERN INTERACTION WITH HFLA WEBSITE TEAM
Research Plan 20` so that the high level overview captures why we are doing all the research plans with this user group.

### Action Items
- [ ] Briefly review all relevant wiki documentation related to this type of research.
- [ ] Review the following sections and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
     - [ ] Review the brief summary about the project/product.
     - [ ] Review the overall goals and/or objectives of the type of research.
     - [ ] Review the summary of the target participants.
     - [ ] Review research framework and methodologies.
- [ ] Find your research plan's subsection. Review and revise as necessary. Include questions as comments for the UX Research Lead to review:
     - [ ] Goals
     - [ ] Requirements
     - [ ] Timelines
     - [ ] Delivery
     - [ ] Follow-up Options
     - [ ] Research Analysis 
- [ ] Review with UX Research Lead
- [ ] Product Sign-off

### Resources
- [Wiki HfLA Volunteers Research Overview Page](https://github.com/hackforla/internship/wiki/HfLA-Volunteers-Research-Overview)
- [RP020 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-20:-Intern-Interaction-with-HfLA-Website-Team)
- [TWE: Research Roadmap: HfLA Volunteers](https://docs.google.com/document/d/1fVOsbi4yZqxMMguIsC3dOFxRkpoBImNbDCG53wxLn7Q/edit?usp=sharing)
