### ISSUE TITLE
Design Component Process Research & Planning

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#444]
### Overview
Plan systems and software so that the design system Figma and Website are replicable easy to understand and efficient for other teams to customize.

### Action Items
- [x] Check MkDocs Material Jekyll Theme licensing to see if we can use it as a starter point
- [x] How should we present the Figma, what elements need to be on the design system cards?
- [x] #483
- [x] Create Wireframe for components within the microsite
- [x] #462
- [x] What other tools or processes can we use to get predictable results every time

### Resources/Instructions
[Connect Figma to Github](https://bootcamp.uxdesign.cc/figma-design-tokens-with-github-repositories-cb0554156137)
[Connect Figma to VS Code](https://help.figma.com/hc/en-us/articles/15023121296151)
[Jekyll Template Instructions](https://www.siteleaf.com/blog/making-your-first-jekyll-theme-part-2/)
[Figma Prototype with Variable](https://www.youtube.com/watch?v=VEuwKJAz7Jg)
[Figma Prototype with Variable 2](https://youtu.be/1ONxxlJnvdM)
[Figma Prototype with Variables 3](https://youtu.be/__ABPkb0aF8)
[Figma Dev Mode](https://www.figma.com/dev-mode/)
[Figma Dev Mode video](https://www.youtube.com/watch?v=__ABPkb0aF8)

### Related Issues
- #397

**Comment by priyatalwar** [comment]
@ericvennemeyer Can you please provide an update that you provided via slack here in the issue itself so it doesn't get lost? Thanks!

**Comment by ericvennemeyer** [comment]
@priyatalwar Sure thing:

If I'm reading it correctly, MK Docs itself is under a BSD license, and themes created with MK Docs are under an MIT license. Both are very permissive about modifying and using freely, so long as copyright notice and some other boilerplate text are retained. See [here](https://www.mkdocs.org/about/license/).

**Comment by ExperimentsInHonesty** [comment]
```
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
```

**Comment by ExperimentsInHonesty** [comment]
Josh will break down this issue into smaller issues

**Comment by joshfishman** [comment]
Planning work done, closing and spinning languishing tasks into their own issues.
