### ISSUE TITLE
TWE Design System: Design Microsite

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#446]
### Dependencies
- #474 

### Overview
We need to design a template for our Jekyll based Website. 
This website is meant to be an easily themed Design Systems team resource.

### Action Items

- [x] Review MkDocs Material Theme
- [x] Create a wireframe of Microsite
- [x] Design Microsite 
   - [x] Structure
   - [x] Header
   - [ ] Footer #408 
   - [x] Subnav
- [x] Design Preliminary Microsite Component Cards (the rest will be addressed on #402)
- [ ] Identify and create separate layouts needed for various components #474 

### Resources/Instructions
- #397  
- #444 
- [MkDocs Material Theme](https://squidfunk.github.io/mkdocs-material/getting-started/) 
#### Remaining issues that have to be finished for final microsite templates to be chosen
- https://github.com/hackforla/internship/issues/408
- https://github.com/hackforla/internship/issues/411

**Comment by meetminji** [comment]
1st draft
<img width="618" alt="Microsite 1st draft" src="https://github.com/hackforla/internship/assets/98001179/7905dc0e-028d-4062-b6b7-02338a39210f">

**Comment by George48U** [comment]
hi there

would love to contribute

**Comment by meetminji** [comment]
Draft 2

<img width="930" alt="microsite second draft" src="https://github.com/hackforla/internship/assets/98001179/0e78d765-c201-4da5-8678-fd8c9a4de599">

**Comment by joshfishman** [comment]
@meetminji this is looking great! Can you please remove the logo underlay in the background of the body?

**Comment by George48U** [comment]
> @meetminji this is looking great! Can you please remove the logo underlay in the background of the body?

I'm a UI/UX designer that recently joined github to help with ongoing projects. I stumbled found yours and I really like what you're doing with  microsite.I'd like to contribute but am having difficulty understanding github and how it works. Could you please tell me about your work and how I may help?

**Comment by meetminji** [comment]
@joshfishman 
Removed the background and added a sub header nav. for the component

<img width="908" alt="microsite draft 3" src="https://github.com/hackforla/internship/assets/98001179/ad041493-adb7-4502-aef6-de0ac4074fc7">

**Comment by meetminji** [comment]
@George48U 

Hey! Github can get confusing to get around! I am currently building wireframes for a microsite for TWE's Design components. There are many issues for the designers and there's one assignee per design issue. It would be great to get your feedbacks on my work and maybe we could discuss in a design team meeting an issue you could work on! Thank you!

**Comment by George48U** [comment]
That would be fantastic. Could you please provide a link to your work so that I may look at it?

**Comment by meetminji** [comment]
> That would be fantastic. Could you please provide a link to your work so that I may look at it?

https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2-45&mode=design&t=pmDvb1X5dr7fbEWd-0

it is under MVP Design System and it's all the way at the bottom right.

**Comment by George48U** [comment]
> Hey! Github can get confusing to get around! I am currently building wireframes for a microsite for TWE's Design components. There are many issues for the designers and there's one assignee per design issue. It would be great to get your feedbacks on my work and maybe we could discuss in a design team meeting an issue you could work on! Thank you!

i just went through the MVP design system nice work,   thoughtful layout, clear information hierarchy, 
I'd be interested in participating in a design team meeting to explore possible issues I could contribute to. Just let me know when the meeting is scheduled

**Comment by meetminji** [comment]
> > Hey! Github can get confusing to get around! I am currently building wireframes for a microsite for TWE's Design components. There are many issues for the designers and there's one assignee per design issue. It would be great to get your feedbacks on my work and maybe we could discuss in a design team meeting an issue you could work on! Thank you!
> 
> i just went through the MVP design system nice work, thoughtful layout, clear information hierarchy, I'd be interested in participating in a design team meeting to explore possible issues I could contribute to. Just let me know when the meeting is scheduled

thank you! Have you been to one of the team meetings before to onboard? I am not sure we have met. We also communicate through Slack under #internships if you haven't joined yet.
We have all team meetings on Thursdays at 10 am and Design team meetings are on Tuesdays at 12:30 pm. Today's meeting was canceled.

**Comment by George48U** [comment]
> > > Hey! Github can get confusing to get around! I am currently building wireframes for a microsite for TWE's Design components. There are many issues for the designers and there's one assignee per design issue. It would be great to get your feedbacks on my work and maybe we could discuss in a design team meeting an issue you could work on! Thank you!
> > 
> > 
> > i just went through the MVP design system nice work, thoughtful layout, clear information hierarchy, I'd be interested in participating in a design team meeting to explore possible issues I could contribute to. Just let me know when the meeting is scheduled
> 
> thank you! Have you been to one of the team meetings before to onboard? I am not sure we have met. We also communicate through Slack under #internships if you haven't joined yet. We have all team meetings on Thursdays at 10 am and Design team meetings are on Tuesdays at 12:30 pm. Today's meeting was canceled.

You are welcome. I have not attended any of the past meetings, and you are correct that we have not met. My email address is odegeorge3@gmail.com. You can add me to the Slack channel. thank you

**Comment by meetminji** [comment]
1. moved navigation to the left side
2. categorized components to avoid long list
3. sub navigation on the right for components in category
4. created tabs for class, states, and code


<img width="632" alt="microsite draft 4" src="https://github.com/hackforla/internship/assets/98001179/ad6b20ed-e5b4-4b45-a70c-ab4f4b4052ae">

**Comment by ExperimentsInHonesty** [comment]
@meetminji Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by meetminji** [comment]
1. updated accordion design. created a microsite wireframe for dropdown and accordion. 
2. need to review updated designs.
3. will have around 5 hours to work on this issue for the next week
4. hope to be done with this issue in a couple weeks
5. 
<img width="938" alt="microsite - accordion" src="https://github.com/hackforla/internship/assets/98001179/5e83724a-fe7e-4ea1-968f-ae7862af5ab0">
<img width="933" alt="microsite - dropdown" src="https://github.com/hackforla/internship/assets/98001179/cfde8ce1-efea-4ecd-801a-d5e5a04c7ebf">

**Comment by meetminji** [comment]
Update for next week:

- Instead of two separate tabs for the file component, it should be open and closed state.
- For state, change to hover and selected state for closed and open.
- Leave example blank for now and later add screenshot of the component from website (when created).

**Comment by meetminji** [comment]
- Included an open and closed state
- changed accordion item color to full saturation with white text

<img width="1123" alt="microsite - dropdown draft 2" src="https://github.com/hackforla/internship/assets/98001179/60a54e3d-3422-4492-b191-6a80a7610ca9">
<img width="1130" alt="microsite - accordion draft 2" src="https://github.com/hackforla/internship/assets/98001179/7b51a2c4-4357-4d07-b55d-2c5ed0cf9b80">

**Comment by meetminji** [comment]
Update for next week:
- for accordion item, change color to mid-green. Same color as hover/select state as accordion parent
- accordion item hover/select state color is green.

**Comment by sunannie27** [comment]
@meetminji The design is accepted once the first section is renamed to "Class" in Figma.

**Comment by meetminji** [comment]
Renamed first section to "Class"

<img width="467" alt="Microsite - Final Draft" src="https://github.com/hackforla/internship/assets/98001179/cd97d297-0e70-4c97-a0c9-b7d11f0c2725">

**Comment by joshfishman** [comment]
@karina-sato @mklmrgn Great quick catch up today -- just a reminder about what I flagged today about the microsite design to website process.

I am concerned that information created in the design process is not being translated to the microsite template. I

 believe we should edit both the way you present components in design and the way we present them on the microsite so that all info is more easily translated / included (maybe they should be the same exactly?) 

Looking forward to your thoughts.

**Comment by karina-sato** [comment]
Thanks for the input @joshfishman 

We'll need to further understand what type of information is not being translated to the microsite so we can think of ways to improve. 
Can you tell me what information is/isn't useful for the dev team on the Master Layout? 
What information is missing from the microsite template? 

Cause combining both the microsite and the master layout would require a lot of effort and time for the design team, since we have different component variants and states for a single component.

The master layout I'm talking about is this: 
<img width="795" alt="image" src="https://github.com/hackforla/internship/assets/140572674/05bdfe25-2857-47f4-9991-402059da71c9">

**Comment by joshfishman** [comment]
@mklmrgn Can you include the footer in this design so it is complete

**Comment by KC-skc** [comment]
@mklmrgn 
Please provide update

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by mklmrgn** [comment]
Progress: "Designed new version with link to component library"
Blockers: "Issues with long titles"
Availability: 1 hour
ETA: 1 week

https://www.figma.com/design/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=6911-14268&t=TGD8u6b4JAHsYNkw-1

![Screen Shot 2024-10-31 at 10 03 20 AM](https://github.com/user-attachments/assets/709e33f9-f4e5-4647-9edb-98c4e8028794)

![Screen Shot 2024-10-31 at 10 03 02 AM](https://github.com/user-attachments/assets/7d0ec110-6cde-4373-b45d-522da324c557)

**Comment by ExperimentsInHonesty** [comment]
Lets change it to say "See in Figma"

**Comment by mklmrgn** [comment]
Design update is complete:

- Created a new icon based on M3 styling and added to microsite design:
![Screen Shot 2024-11-14 at 8 39 27 AM](https://github.com/user-attachments/assets/de6bbab8-17f2-4d07-85dc-af0a39990c92)


- added links on all Microsite layouts as well as Figma components sections.



![Screen Shot 2024-11-14 at 8 35 01 AM](https://github.com/user-attachments/assets/4cc0fd34-2e54-4525-989c-c9beaa35981a)

**Comment by ExperimentsInHonesty** [comment]
### Outstanding tasks for @joshfishman 

- [ ] The above comment requires that a new issue be created to add the figma link to the component page

- [ ] We also need a new issue to add a toggle to the top right of the microsite that lets the user turn on dark mode.
   - the issue will get a dependency of https://github.com/hackforla/internship/issues/558

**Comment by joshfishman** [comment]
this issue is complete.
