### ISSUE TITLE
TWE: IS24: RP022: Research Roadmap: Update/Create

### ISSUE THREAD

**Issue by AndrewSalvatore** [hackforla/internship#448]
### Dependencies
- [x] [309](https://github.com/hackforla/internship/issues/309)
- [x] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created and approved. See #429.

### Overview
We need to update the details of the `Intern Research Roadmap` for `RP022` so that the high level overview captures why we are doing all the research plans with this user group.

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Open relevant wiki page for Intern
    - [x] Copy the link for the Intern wiki page in your browser
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
    - [x] Go to Intern Research Overview wiki page (Resources # 2.01)
    - [x] Open relevant wiki page for RP022
    - [x] Copy the link for the RP022 wiki page in your browser
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
- Customize Resource for Intern's Research Roadmap doc
    - [x] Choose the "Research by Participant Type" folder on the shared Google Drive (Resources  # 1.02)
    - [x] Choose `Intern` folder
    - [x] Locate `TWE: Research Roadmap: Intern` Google doc in the folder
    - [x] Right-click on the `TWE: Research Roadmap: Intern` Google doc
    - [x] Choose "Get Link"
    - [x] Choose "Copy link" and "Done"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Update and/or create research roadmap details for RP022
    - [x] Briefly review all relevant wiki documentation related to Intern research and RP022.
    - [x] Review the following sections of the Intern Research Roadmap Google doc and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
        - [x] Review the background about the project/product.
        - [x] Review the research goals and/or objectives of the type of research.
        - [x] Review the summary of the target participants.
        - [x] Review research framework and methodologies.
    - [x] If the research roadmap for RP022 has been created, please review and revise each subsection under the RP022's research roadmap as necessary. Include questions as comments for the UX Research Lead to review in the RP022 Research Roadmap Google doc.
         - [x] Review goals
         - [x] Review requirements
         - [x] Review timelines
         - [x] Review delivery
         - [x] Review follow-up options
         - [x] Review research analysis
    - [x] If the research roadmap for RP022 has not been created, please draft the research roadmap for RP022
        - [x] Open the Research Roadmap for Intern if it is not open in your browser
        - [x] Identify the placement of RP022's research roadmap in the ascending sequence in the Google doc
        - [x] Make sure to copy the structure and format of a research plan's research roadmap to keep the documentation consistent
        - [x] Rename the research plan title `RP???: Research Plan Name` with `RP022: Soft skills of incoming interns`
        - [x] Draft goals
        - [x] Draft requirements
        - [x] Draft timelines
        - [x] Draft delivery
        - [x] Draft follow-up options
        - [x] Draft research analysis
        - [x] Go to the Table of Contents of Intern Research Roadmap
        - [x] Update the Table of Contents by clicking on the circle icon <img width="132" alt="Screenshot 2023-07-13 at 4 01 49 PM" src="https://github.com/hackforla/internship/assets/57029070/94ac0437-995c-4734-9780-27e6c55ce230">
- [x] Review with UX Research Lead
- [ ] Product Sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Participant Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link) 

#### Resources gathered during the completion of this issue
2.01 [Wiki Intern Research Overview Page](https://github.com/hackforla/internship/wiki/Intern-Research-Overview)
2.02 [RP022 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-22:-Soft-Skills-of-Incoming-Interns)
2.03 [TWE: Research Roadmap: Intern](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)

**Comment by AndrewSalvatore** [comment]
[ ] Review the following sections and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.

@pandanista Does this action item and its subitems refer to the "Summary of Research" section on this RP's wiki?

**Comment by pandanista** [comment]
@AndrewSalvatore Thank you for the feedback and creating this issue. 

The action item and its subitems were referring to the content in [TWE: Research Roadmap: [Intern]](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit).

This was a template that was made much earlier, so it didn't specify a lot of things very well. I edited and updated the template and this issue, so hopefully it is easier to follow the step by step instructions to complete this issue now.

Let me know if you have any questions.

**Comment by AndrewSalvatore** [comment]
Progress: completed, waiting for review

Blockers: none

Availability: 6 hour

ETA: complete after review and sign-off

Pictures or links (if necessary): none

**Comment by pandanista** [comment]
@AndrewSalvatore Thank you for the quick turnaround. I just made some minor edits, but overall the research roadmap for RP022 looks good to me.

We can go over this issue at the UXR meeting today before asking product for feedback and sign-off.

**Comment by pandanista** [comment]
@priyatalwar This issue has been reviewed and please take a look at RP022's roadmap details in [TWE: Research Roadmap: Intern](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing).

Let us know if there is any feedback from product. Otherwise, please close the issue as it is completed.

**Comment by priyatalwar** [comment]
Hi @pandanista Thanks for taking care of this issue. I just added a minor comment on the google doc. Please add that in and feel free to close the issue. Thank you.
