### ISSUE TITLE
TWE: Create Template Issue: Create or update research roadmap details 

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#450]
### Dependencies
- #560 

### Overview
We need to create a template issue for creating `TWE: Research: Research Roadmap: Create or update` (named in the format as `TWE: Role: Direct Object: Action Verb`) so that we have a consistent, transparent, defined, and self-supporting structure for people creating them.

**Resources/Instructions**: This section is at the bottom of this issue (scroll to the bottom to view it now). You will be asked to add links to this section while completing the issue. 

#### Customize this issue
 - Customize this issue by adding the Name of Issue Template. 
    - _Note: An issue template's name is different from the issue title created from the template._
    - [x] Search for `TWE: Research: Research Roadmap: Create or update` by using the browser search (**Mac**: ⌘+F; **PC**: Ctrl+F)
    - [x] Replace the keyword string (including text and the brackets) below with the name of your issue template according to the template naming convention: `TWE: Role: Direct object: Action verb`
        - The role is the primary owner of the issue template (e.g., Research, Design, Product)
        - Direct object should be the item that we're updating or working on (e.g., Wiki, Interviews, Roadmap)
        - Action verb should be the main descriptor of the action items (e.g., Update, Create, Transcribe)

#### Customize the issue settings (located in right sidebar)
Change the issue settings to ensure the issue is properly categorized and easy to manage.
- [x] Under Assignees, assign yourself.
- [x] Under Projects, choose gear, choose Repository, and choose TWE Project Management.
- [x] Add the milestone: Project Management
- [x] Add a feature label specific to what the template is related to, if available.  If not clear what you should use, ask product.

#### Customize template draft
Create a draft of new template, which will be known as our "draft".
- [x] Copy resource 1.01 Content to copy for draft to a new comment on this issue.
- [x] In your draft, fill out the top part (called front matter) with the following information.  See resource 1.02 Front Matter Resources section below for definitions and examples.
    - [x] Name
    - [x] About
    - [x] Title
    - [x] Labels
- [x] Define any Dependencies (or remove the dependency section if there is no dependency)
- [x] Customize the Overview section
- [x] Fill out the Action Items section (in your draft) by defining the steps that are required to be done, keeping the following in mind:
   - [x] The person working on this issue might be new to the org, so the issue should be able to be worked on without any prior knowledge
   - [x] If the person needs to add links, or put documents in specific locations, the place where they can do that action must be linked in the resources section
      - [x] The links in the resources section provided by the issue creator should be in the same order as the Action Items 
      - [x] Refer to resource 1.03 Example Action Items for Finding Wiki Page and Template for an example of how to write clear instructions that avoid compound steps (steps within a step).
   - [x] Number each resource in the order each resource appears in the Action Items
       - [x] Group resources into numbers and decimals (e.g., Resource 1.01, Resource 2.01)
       - [x] Group the resources based on whether they are available when making the issues or they need to be created from this issue
           - If the resource is available, then group it under the Resources for creating this issue section (e.g., Resource 1.01, Resource 1.02, Resource 1.03)
           - If the resource will be delivered or created from this issue, then group it under the Resource links gathered during the making of this issue (e.g., Resource 2.01, Resource 2.02, Resource 2.03)
- [x] If documents or folders (sheets, docs, presentations, dashboard, etc.) will be created, find the document template that should be used by checking resource 1.04 WIKI Templates by role pages.  
  - [x] If there is a template
     - [x] Add a link to the template into the ` #### Resources for creating this issue`  section of your draft
  - [ ] If there is no template yet
    - [ ] Put a placeholder into the` #### Resources for creating this issue`  section of the draft `[TWE: Template Issue: Research: [Replace ACTION VERB][Replace DIRECT OBJECT]`
- [x] Get sign-off by Product on the draft
- [x] Create the template issue on the repo
- [x] Add the link to the new issue template once created to resource 2.01.  Find by clicking on the Getting started button to the right of the new template listed on [new issue page](https://github.com/hackforla/internship/issues/new/choose)
- [x] Update the appropriate place in the wiki for your template (see resources section)

#### Resources for creating this issue
1.01 Content to copy for draft
```
Draft of template issue for `TWE: Role: Consent Documents for Participants Over 18: Create`
---
**name:** TWE: Template Issue: Research: [Replace ACTION VERB][Replace DIRECT OBJECT]
**about:** We are creating a template to complete `TWE: Role: Consent Documents for Participants Over 18: Create` issue so we can stay consistent in our process
**title:** TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: [Replace DIRECT OBJECT]: [Replace ACTION VERB]
**labels:** 'feature: research', 'feature: missing', 'size: missing', 'Participant Type: missing', 'Research 000: missing', 'role:  UI/UX research', 'milestone: missing', 'complexity: missing'
**assignees:** 

---
#### Instructions for creating this issue
The person who creates this issue should use these links to add links to the resources section and customize this issue
- Customize the issue
    - [ ] Replace the keyword strings (including text and the brackets) below with the appropriate values by using the browser search (Mac: Command+F PC: Ctrl+F)
    - [ ] Search for `[Replace`
    - [ ] Replace with whatever the keyword or information is asking for.
- Customize the issue settings (located in right sidebar)
    - [ ] Under Labels, add labels for any labels identified as missing
    - [ ] Remove the corresponding missing labels
    - [ ] Under Projects, choose gear, choose "Repository," and choose TWE Project Management.
    - [ ] Add the milestone: [Replace MILESTONE]
    - [ ] Add a feature label specific to what the template is related to, if available. If not clear what you should use, ask product.
- Customize dependencies 
    - [ ] If no dependencies, delete dependency section
    - [ ] If dependencies, add the dependencies (any issue or reason that would prevent the action items from being completed)
- Remove this section.
    - [ ] Delete this section when all the checkboxes above are complete (i.e., the issue assignee will never see this part)

### Dependencies

### Overview
We need to [Replace ACTION VERB] [Replace DIRECT OBJECT] for [Replace REASON].

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources
#### Resources for creating this issue
1.01
1.02

#### Resources gathered during the completion of this issue
2.01
2.02
```

1.02 Front Matter Resources
<details>
<summary>1.02.01 Front Matter Fields and Meaning</summary>

- name: (name that appear on the new issue tab)
- about: (is the description that appears next to the issue template on the new issue tab)
- title: (the title that appears when the issue is created.  User then customizes this title for their issue)
    - Use the naming convention: TWE: Role: Direct object: Action verb
    - If more than one word should go into the direct object spot, use multiple square brackets with the keyword (see example)
- labels: (choose the labels that will be the same each time, and choose missing labels for the ones that depend on content)
- assignees: 
</details>

<details>
<summary>1.02.02 Front Matter Field example</summary>

- name: 'TWE: Template Issue: Research: Create Roadmap'
- about: We are creating a template to complete `TWE: Role: Consent Documents for Participants Over 18: Create` issue so we can stay consistent in our process 
- title: 'TWE: Research: IS[Replace YY]: RP[Replace 000]: [Replace TYPE OF PARTICIPANT] [Replace TYPE OF RESEARCH METHOD]: Roadmap : Create'
- labels: 'feature: research', 'feature: roadmap', 'milestone: missing', 'role: UI/UX research', 'Participant Type: missing', 'Research 000: missing', 'complexity: missing'
- 'size: 0.50pt'
- assignees: ''
</details>

1.03 Example Action Items for Finding Wiki Page and Template
<details>
<summary>1.03.01 Example Action Items</summary>

```
### Action Items
- Customize wiki page
     - [ ] Go to link 1.01 Internship Wiki, Join the team page
     - [ ] Find wiki page for this issue by looking at role pages.
     - [ ] Copy the link for the wiki page.
     - [ ] Add the link to Resource 2.01
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
- Customize document template.
    - [ ] Go to link 1.02 Design Process Overview
    - [ ] Find document template that should be used in this issue.
    - [ ] Copy the link for the template.
    - [ ] Add the link to Resource 2.02
        - [ ] Add the name of the link in square brackets
        - [ ] Add the URL in parenthesis without a space between the square bracket and parenthesis
```

</details>

<details>
<summary>1.03.02 Example Resource Lists</summary>

```
### Resources for creating this issue
1.01. [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)
1.02. [Design Process Overview](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

### Resource links gathered during the making of this issue
2.01. [Wiki page for [Replace TYPE OF ROLE]]
2.02. [TWE: Template: [Replace NAME OF TEMPLATE]]
```

</details>

- 1.04 WIKI Templates by role pages
   - [TWE: WIKI: UX Research Guides Templates](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates) 
   - [Design](https://github.com/hackforla/internship/wiki/Design-Process-Overview)
   - [Product](https://github.com/hackforla/internship/wiki/Product)
   - [Business Analyst / Data Science]
   - [Software Engineer]
   - [Marketing]
   - default document templates, in case you don't have one yet, can be found on the [Design Process Overview page](https://github.com/hackforla/internship/wiki/Design-Process-Overview)

#### Resources gathered during the completion of this issue
- 2.01 [TWE: Template: Research Roadmap: Create or Update](https://github.com/hackforla/internship/issues/new?assignees=&labels=complexity%3A+medium%2C+feature%3A+research%2C+feature%3A+roadmap%2C+milestone%3A+missing%2C+Participant+Type%3A+missing%2C+Research+000%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&projects=&template=research--create-or-update-research-roadmap-details.md&title=TWE%3A+Research%3A+RP%5BReplace+000%5D%3A+%5BReplace+TYPE+OF+PARTICIPANT%5D+Research+Roadmap%3A+Create%2FUpdate)

**Comment by pandanista** [comment]
#### Instructions for creating this issue
The person who creates this issue should use links in the section "Resources for creating this issue" (i.e., 1.01, 1.02, etc.) to customize this issue.
- Customize the issue
    - [ ] Open the "Research Overview" wiki page (Resource 1.01)
    - [ ] Choose the appropriate research roadmap or research plan folder (ie., RP###) on the wiki page 
    - Use the information on the wiki page and in research roadmaps or research plans to customize this issue
    - [ ] Copy and paste entire template text in this issue into text editor (ie., "TextEdit" on _Mac_, "Wordpad" on _PC_)
    - Use Find/Replace (**Mac:** ⌘+F or **PC**: Ctrl+F) to search for and replace the keyword strings (including text and the brackets) below with the appropriate values 
        - Year 
            - [ ] Find/Replace `[Replace YY]` with research year (Two digit format, ex: "22" for year "2022"; if the research hasn't been conducted, use the next cohort's enrollment year) 
        - Research Plan Number
            - [ ] Find/Replace `[Replace RP000]` with the research plan number (Three digit format, ex: "001" for research plan "RP001") 
        - Type of Participant
            - [ ] Find/Replace `[Replace TYPE OF PARTICIPANT]` with the participant type (ex: "Intern" or "Mentor")  
        - Research Plan Name
            - [ ] Find/Replace `[Replace TITLE OF RESEARCH]` with the research plan name on the wiki page or the research plan folder (ex: “Intern Intake Interview” or “Mentor Exit Interview”) 
    - [ ] Copy and paste the edited template from text editor back into this Github Issue, replacing the original text
    - [ ] Re-check all the checkboxes above after copying and pasting the edited template
    - [ ] Close the text editor
    - Update the issue title
        - [ ] Copy 
        ```
        TWE: IS[Replace YY]: [Replace RP000]: Research Roadmap: Update/Create
        ```
        - [ ] Choose "Edit" in the title section
        - [ ] Paste what you copied into the issue title
        - [ ] Choose "Save"
- Customize the issue settings (located in right sidebar)
    - [ ] Under Assignees, assign a Researcher if it has been determined. Otherwise, leave it blank.
    - [ ] Under Labels,  choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Research: [Replace RP000]`
    - [ ] Under Labels, choose gear  ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and apply the label `Participant Type: [Replace TYPE OF PARTICIPANT]`
    - [ ] Remove the `Research 000: missing` and `Participant Type: missing` labels
    - [ ] Under Projects, choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), choose `Repository`, and choose `Program Management`
    - [ ] Add the milestone: choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), and choose `Research Roadmap Document Creation`
    - [ ] Remove the label `milestone: missing`
- Remove this section
    - [ ] After all the checkboxes above are complete and the issue is ready to be worked on, delete all text below the "Instructions for Creating this Issue" (top heading) and above "Overview" (heading below) -- i.e., the issue assignee will never see this part 

### Dependencies
- [ ] [REPLACE WITH ROADMAP ISSUE #]
- [ ] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created and approved [REPLACE WITH RESEARCH STRUCTURE ISSUE # IF AVAILABLE].  Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Structure+for+RP) to search the issue tab for potential results

### Overview
We need to update the details of the `[Replace TYPE OF PARTICIPANT] Research Roadmap` for `[Replace RP000]` so that the high level overview captures why we are doing all the research plans with this user group.

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

### Action Items
#### Customize Resource Links
- Customize Resource for Wiki Page Link
    - [ ] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [ ] Open relevant wiki page for [Replace TYPE OF PARTICIPANT]
    - [ ] Copy the link for the [Replace TYPE OF PARTICIPANT] wiki page in your browser
    - [ ] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
    - [ ] Go to [Replace TYPE OF PARTICIPANT] Research Overview wiki page (Resources # 2.01)
    - [ ] Open relevant wiki page for [Replace RP000]
    - [ ] Copy the link for the [Replace RP000] wiki page in your browser
    - [ ] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
- Customize Resource for [Replace TYPE OF PARTICIPANT]'s Research Roadmap doc
    - [ ] Choose the "Research by Participant Type" folder on the shared Google Drive (Resources  # 1.02)
    - [ ] Choose `[Replace TYPE OF PARTICIPANT]` folder
    - [ ] Locate `TWE: Research Roadmap: [Replace TYPE OF PARTICIPANT]` Google doc in the folder
    - [ ] Right-click on the `TWE: Research Roadmap: [Replace TYPE OF PARTICIPANT]` Google doc
    - [ ] Choose "Get Link"
    - [ ] Choose "Copy link" and "Done"
    - [ ] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [ ] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Update and/or create research roadmap details for [Replace RP000]
    - [ ] Briefly review all relevant wiki documentation related to [Replace TYPE OF PARTICIPANT] research and [Replace RP000].
    - [ ] Review the following sections of the [Replace TYPE OF PARTICIPANT] Research Roadmap Google doc and write questions into comments for UX Research Lead as you go through each section. If you think the content should be revised, include that in your comments.
        - [ ] Review the background about the project/product.
        - [ ] Review the research goals and/or objectives of the type of research.
        - [ ] Review the summary of the target participants.
        - [ ] Review research framework and methodologies.
    - [ ] If the research roadmap for [Replace RP000] has been created, please review and revise each subsection under the [Replace RP000]'s research roadmap as necessary. Include questions as comments for the UX Research Lead to review in the [Replace RP000] Research Roadmap Google doc.
         - [ ] Review goals
         - [ ] Review requirements
         - [ ] Review timelines
         - [ ] Review delivery
         - [ ] Review follow-up options
         - [ ] Review research analysis
    - [ ] If the research roadmap for [Replace RP000] has not been created, please draft the research roadmap for [Replace RP000]
        - [ ] Open the Research Roadmap for [Replace TYPE OF PARTICIPANT] if it is not open in your browser
        - [ ] Identify the placement of [Replace RP000]'s research roadmap in the ascending sequence in the Google doc
        - [ ] Make sure to copy the structure and format of a research plan's research roadmap to keep the documentation consistent
        - [ ] Rename the research plan title `RP???: Research Plan Name` with `[Replace RP000]: [Replace TITLE OF RESEARCH]`
        - [ ] Draft goals
        - [ ] Draft requirements
        - [ ] Draft timelines
        - [ ] Draft delivery
        - [ ] Draft follow-up options
        - [ ] Draft research analysis
        - [ ] Go to the Table of Contents of [Replace TYPE OF PARTICIPANT] Research Roadmap once you finish the draft
        - [ ] Update the Table of Contents by clicking on the circle icon <img width="132" alt="Screenshot 2023-07-13 at 4 01 49 PM" src="https://github.com/hackforla/internship/assets/57029070/94ac0437-995c-4734-9780-27e6c55ce230">
- [ ] Review with UX Research Lead
- [ ] Product Sign-off

### Resources/ Instructions
#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Participant Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link) 

#### Resources gathered during the completion of this issue
2.01 [Wiki [Replace TYPE OF PARTICIPANT] Research Overview Page]
2.02 [[Replace RP000] Wiki Page]
2.03 [TWE: Research Roadmap: [Replace TYPE OF PARTICIPANT]]

**Comment by pandanista** [comment]
This template has been tested by internal TWE team member on issue #448. 

Not this template is ready to be tested by product team.

**Comment by priyatalwar** [comment]
This template needs to be tested by product so it can be signed off.

**Comment by sunannie27** [comment]
Added to PM agenda

**Comment by pandanista** [comment]
PM has finished the testing using issue #470 and provided feedback in the thread. I've implemented all the changes in the template. This template is ready for project lead to review.

**Comment by pandanista** [comment]
Need to revise the first comment for all template issues.

**Comment by pandanista** [comment]
The issue template for the template issue has been created in #508. #508 needs some final edits.

**Comment by pandanista** [comment]
@sunannie27 
- This template issue is now released because the create issue template has been deployed (#508)
- This template issue has been tested in #470 and #448 
- This template issue is ready for product to do final review and sign off

**Comment by ExperimentsInHonesty** [comment]
Adding to agenda to find out if Ying thinks this template has been sufficiently tested.  If not, create a template testing issue out of the new template.

The reason we are asking is that in [this comment](https://github.com/hackforla/internship/issues/448#issuecomment-1635103373) on the testing issue, Ying indicates its an old template and she has modified it, but at that point  in Andrews test, he was 1/2 way through it.

**Comment by ExperimentsInHonesty** [comment]
When @sunannie27 finishes the template testing and we publish that template, then @pandanista should use the testing template to make an issue for Sandy to the Creating of Roadmap details template on RP025.

**Comment by pandanista** [comment]
#560 the testing template has been approved and deployed. We are releasing this one from the icebox.

**Comment by pandanista** [comment]
This template is ready for another round of testing. After creating the testing issue, will add the template 2(b) label.

**Comment by ExperimentsInHonesty** [comment]
@jinyan0425 Use this [testing template ](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+missing%2C+feature%3A+research%2C+feature%3A+test+a+template+%28step+2a%29%2C+good+first+issue%2C+milestone%3A+missing%2C+Participant+Type%3A+TWE+Team+Member%2C+role%3A+UI%2FUX+research%2C+size%3A+3pt%2C+time+sensitive&projects=&template=research--test--issue-template.md&title=Research%3A+Test%3A+Issue+Template%3A+%5BReplace+with+TEMPLATE+NAME%5D) to test the [issue comment with the Update Research Roadmap template above](https://github.com/hackforla/internship/issues/450#issuecomment-1641000299), which will end up making as your test issue, an issue to Create roadmap details for RP0025.  When you have completed the test, the issue will be ready for sandy to be assigned and she will create the roadmap details in this document [TWE: Research Roadmap: Other](https://docs.google.com/document/d/1j0FOrYd6eyoSb3u8Ek0QDZeFq9_9Qecz8JtUG021ZoA/edit#bookmark=id.k8iqhgse577h)

**Comment by pandanista** [comment]
- This template can replace issue #529

**Comment by pandanista** [comment]
@sunannie27 and @KC-skc: 
- Please give us a thumbs up if you will be review this issue, #605, and #606.
    - #450 is step 1 and 2b, the template draft.
    - #605 is step 2a, the testing template that set up the template test.
    - #606 is step 3, the template test.

- The research roadmap:update/Create template has finished the testing using RP025.
- [RP025's research roadmap document](https://docs.google.com/document/d/1j0FOrYd6eyoSb3u8Ek0QDZeFq9_9Qecz8JtUG021ZoA/edit#bookmark=id.k8iqhgse577h) has been reviewed and approved by Bonnie and Tim.
- Let me know what you think. Once approved, we can deploy the template in the repo.

**Comment by ExperimentsInHonesty** [comment]
@pandanista Yes, go ahead and update/deploy the template

**Comment by pandanista** [comment]
YO will use this template to show @jinyan0425 how to deploy a template on GitHub next week.

**Comment by pandanista** [comment]
Closing this issue as it is completed.
