### ISSUE TITLE
TWE: Design Lead/Dev Meeting Agenda

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#454]
- Copy and paste template below into a new comment for each meeting
- Assign a member of the team to take meeting notes and record action items

```
[DATE] Agenda and Notes

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
 - [ ] Karina
 - [ ] Jason
 - [ ] Joshua


#### Optional
- [ ] Bonnie
- [ ] Priyanka

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
- [ ] Accountability and Support Check.
   - [ ] [Karina](https://github.com/hackforla/internship/issues/assigned/karina-sato)
   - [ ] [Jason](https://github.com/hackforla/internship/issues/assigned/jnomad21)
   - [ ] [Joshua](https://github.com/hackforla/internship/issues/assigned/joshfishman)

### Items Carried Forward
- [ ] 

### New Items
- [ ] 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ] 
```

### Resources
-

**Comment by ExperimentsInHonesty** [comment]
2023-08-08 Agenda and Notes

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
 - [ ] Karina
 - [ ] Jason
 - [ ] Joshua


#### Optional
- [ ] Bonnie
- [ ] Priyanka

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
 - [ ] Accountability and Support Check.
 - [ ] [Karina](https://github.com/hackforla/internship/issues/assigned/karina-sato)
 - [ ] [Jason](https://github.com/hackforla/internship/issues/assigned/jnomad21)
 - [ ] [Joshua](https://github.com/hackforla/internship/issues/assigned/joshfishman)

### Items Carried Forward
- [ ] 

### New Items
- [ ] Who attends this meeting
- [ ] Why do we attend this meeting
- [ ] Status of Micro site design
- [ ] Review 
- [ ] Carry forward the "New Items" that we did not get to look at today
  
### FYIs

### Notes from meeting
- 

### Task Items carried forward from last meeting

### New Task Items
If they are issues to be made, add them here  #128 otherwise add them below this line as checkboxes
- [ ] 

#### Items for next week's agenda
- [ ]

**Comment by joshfishman** [comment]
8/15/23 Agenda and Notes

### Prework
- [ ] If you have questions, add them to a comment in this issue: https://github.com/hackforla/internship/issues/59
- [ ] Review your issues and update issues with the [update template](https://github.com/hackforla/internship/wiki/How-to-give-updates-on-your-issues).
- [ ] If you want to discuss something specific to our team, add items to this agenda under "New agenda items"

### Roll Call
 - [ ] Karina
 - [ ] Jason
 - [ ] Joshua


#### Optional
- [ ] Bonnie
- [ ] Priyanka

#### Recurring items: 
- [ ] [Reminder to use "Get your Team Questions Answered here" issue](https://github.com/hackforla/internship/issues/59)
- [ ] Accountability and Support Check.
   - [ ] [Karina](https://github.com/hackforla/internship/issues/assigned/karina-sato)
   - [ ] [Jason](https://github.com/hackforla/internship/issues/assigned/jnomad21)
   - [ ] [Joshua](https://github.com/hackforla/internship/issues/assigned/joshfishman)

**Comment by joshfishman** [comment]
This meeting has been cancelled
