### ISSUE TITLE
[TEST] TWE: IS22: RP008: Research Roadmap: Update/Create

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#470]
### Dependencies
- [x] #208 
- [x] ~~A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created and approved [REPLACE WITH RESEARCH STRUCTURE ISSUE # IF AVAILABLE].  Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Structure+for+RP) to search the issue tab for potential results~~ [Wiki page for RP008](https://github.com/hackforla/internship/wiki/Research-Plan-8-:-Mentor-Intake-Interviews)

### Overview
We need to update the details of the `Mentor Research Roadmap` for `RP008` so that the high level overview captures why we are doing all the research plans with this user group.

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

#### Customize Resource Links
- Customize Resource for Wiki Page Links
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Open relevant wiki page for Mentor
    - [x] Copy the link for the Mentor wiki page in your browser
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
    - [x] Go to Mentor Research Overview wiki page (Resources # 2.01)
    - [x] Open relevant wiki page for RP008
    - [x] Copy the link for the RP008 wiki page in your browser
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
- Customize Resource for Google Drive Folder by Participant Type
    - [x] Choose the "Research by Participant Type" folder on the shared Google Drive (Resources  # 1.02)
    - [x] Choose `Mentor` folder
    - [x] Copy the link of the `Mentor` folder
        1. Choose the three vertical dots on the right side of the `Mentor` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for Mentor's Research Roadmap doc
    - [x] Open the `Mentor` folder (linked in Resources # 2.03)
    - [x] Locate `TWE: Research Roadmap: Mentor` Google doc in the folder
    - [x] Copy the link of the `TWE: Research Roadmap: Mentor` Google doc
        1. Choose the three vertical dots on the top right side of the `TWE: Research Roadmap: Mentor` Google doc  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link"
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

#### Check & Fix Research Roadmap Document Formatting
- Review File Name
    - [x] Open the roadmap document (linked in Resources # 2.04)
    - [x] Confirm that the document uses the following naming convention: `TWE: Research Roadmap: Mentor`. If it does not follow that format, change the filename to match the project's naming convention.
- Compare Document Headings
    - [x] With the roadmap document open in one tab (linked in Resources # 2.04), open in another tab the `TWE: Template: Research Roadmap` (linked in Resources # 1.03)
    - [x] Click inside the roadmap document (linked in Resources # 2.04) and scroll through the document to determine whether the document contains the same headings as the research roadmap template (linked in Resources # 1.03).
- Adjust Incorrect Document Headings
    - [x] If the document does not have the correct headings, then adjust the headings according to the template.
        - [x] Check that each major heading is formatted as Header 1.
        - [x] To check formatting, place your cursor inside the heading text and look at the Styles dropdown menu next to the Font dropdown menu. If it needs adjusted, select the entire heading text and choose "Header 1" in the Styles dropdown menu.
    - [x] Check off the items below as you review their formatting (a check mark indicates that you've reviewed the item regardless of whether you fixed it or not).
        - [x] Background
        - [x] Mentor Research Goals and Objectives
        - [x] Participants
        - [x] Research Framework and Methodologies
        - [x] Individual Research Plans
            - [x] Research Plan Section Titles (see specific instructions in the next section)
        - [x] Resources
        - [x] Notes
- Review Research Plan Names and Formatting
     - [x] Confirm that all the research plans section titles are named in `RP000: [TITLE OF RESEARCH]` format. 
     - [x] Confirm each research plan name in the research roadmap document is correct by checking Mentor Research Output Overview page (linked in Resources # 2.01). If they need to be adjusted, fix them according to how they are named in the Research Output Overview page (linked in Resources # 2.01) or ask the UXR lead if there is no corresponding wiki page.
     - [x] Confirm that the research plan names are formatted as Header 2 in the document heading options.
        - [x] To check, place your cursor inside the heading text and look at the Styles dropdown menu next to the Font dropdown menu. If it needs adjusted, select the entire heading text and choose "Header 2" in the Styles dropdown menu.
    - [x] Confirm research plan's subsection has the following sections
        - Goals
        - Requirements
        - Timelines
        - Delivery
        - Follow-up Options
        - Research Analysis
    - [x] Confirm research plan's subsection are formatted as Header 3.  
        - [x] To check, place your cursor inside the heading text and look at the Styles dropdown menu next to the Font dropdown menu. If it needs adjusted, select the entire heading text and choose "Header 3" in the Styles dropdown menu.

#### Update and/or create research roadmap details for Mentor and RP008
- Update Overview Sections
    - [x] If the Mentor research roadmap overview sections have been drafted, please review and revise the general overview of research roadmap as necessary. 
        - [x] Compare the Mentor Research Roadmap against the Mentor Research Overview Wiki Page (linked in Resources # 2.01). If you notice any discrepancy, please inform the team about the discrepancy in the Mentor Research Roadmap by inserting a comment in the Google doc.
        - [x] Read through the following sections to see if they make sense. Check for typos, completeness, and general formatting as you read through each section. If you think the content should be revised, please use "Suggesting Mode" to suggest revisions. <img width="300" alt="Screenshot 2023-07-20 at 5 17 12 PM" src="https://github.com/hackforla/internship/assets/57029070/d7a45458-afd1-4bb1-b526-befa3dd34188"> If you have questions or concerns, please insert comments in the Mentor Research Roadmap Google doc for the UX Research Lead to review.
            - [x] Background about the project/product.
            - [x] Research goals and/or objectives of the type of research.
            - [x] Summary of the target participants.
            - [x] Research framework and methodologies.
    - [ ] If the Mentor research roadmap has not been drafted, please draft the overview sections of the research roadmap by following the steps
        - [ ] Open the Research Roadmap for Mentor if it is not open in your browser (Resources # 2.04)
        - [ ] Make sure the structure and format of a research roadmap stays consistent. Check `Research Roadmap Template` (linked in Resources # 1.03) or `Report Template - Roadmap Overview` below Resources for the structure of the roadmap overview sections if needed.        
        - [ ] If you are unfamiliar with Mentor Research Roadmap, please reach out to UX Research Lead for clarification, and/or bring this issue to the next UXR meeting for further discussion
        - [ ] Draft the overview sections of Mentor research roadmap 
            - [ ] Background
            - [ ] Mentor Research Goals and Objectives
            - [ ] Participants
            - [ ] Research Framework and Methodologies       
- Update Research Plan Section
    - [x] If the research roadmap for RP008 has been created, please review and revise each subsection under the RP008's research roadmap as necessary. 
        - [x] Compare the RP008's research roadmap subsections against the RP008's wiki page (linked in Resources # 2.02). If you notice any discrepancy, please inform the team about the discrepancy in the RP008's research roadmap by inserting a comment in the Google doc.
        - [x] Read through each section to see if they make sense. Check for typos, completeness, and general formatting as you read through each section. If you think the content should be revised, please use "Suggesting Mode" to suggest revisions. <img width="300" alt="Screenshot 2023-07-20 at 5 17 12 PM" src="https://github.com/hackforla/internship/assets/57029070/d7a45458-afd1-4bb1-b526-befa3dd34188"> If you have questions or concerns, please insert comments in the RP008 Research Roadmap Google doc for the UX Research Lead to review. 
            - [x] Goals
            - [x] Requirements
            - [x] Timelines
            - [x] Delivery
            - [x] Follow-up Options
            - [x] Research Analysis
    - [ ] If the research roadmap for RP008 has not been created, please draft the research roadmap for RP008 by following the steps
        - [ ] Open the Research Roadmap for Mentor if it is not open in your browser (Resources # 2.04)
        - [ ] Identify the placement of RP008's research roadmap in the ascending sequence in the Google doc
        - [ ] Make sure to copy the structure and format of a research plan's research roadmap to keep the documentation consistent. Copy `Report Template - Research Plan` below Resources to the research roadmap Google Doc if needed. 
            - [ ] Rename the research plan title `RP???: Research Plan Name` with `RP008: Mentor Intake Interviews`
            - [ ] Apply formatting to `RP008: Mentor Intake Interviews` 
                - [ ] Apply "Header 2" in section title `RP008: Mentor Intake Interviews`
                - [ ] Apply "Header 3" to all the subsections: Goals, Requirements, Timelines, Delivery, Follow-up Options, and Research Analysis        
        - [ ] If you are unfamiliar with RP008, please reach out to UX Research Lead for clarification, and/or bring this issue to the next UXR meeting for further discussion
        - [ ] Draft the research roadmap for RP008
            - [ ] Goals
            - [ ] Requirements
            - [ ] Timelines
            - [ ] Delivery
            - [ ] Follow-up Options
            - [ ] Research Analysis
- Update Resource Section (at the end of research roadmap doc)
    - [x] Check the final sections (Resources and Notes) to see if they are updated, have functional links, and do not include redundant information.
        - [x] In the Resources section, double check that links to the individual research plans are accurate and complete according to the Overview wiki page (Resources # 2.01).
- [x] Go to the Table of Contents of Mentor Research Roadmap document once you finish revising or updating the draft
- [x] Update the Table of Contents by clicking on the circle icon <img width="132" alt="Screenshot 2023-07-13 at 4 01 49 PM" src="https://github.com/hackforla/internship/assets/57029070/94ac0437-995c-4734-9780-27e6c55ce230">

#### Next steps
- [x] Review with UX Research Lead
    - [ ] Lead will direct you to make new issues for each Research Plan that is not properly documented in the Research Roadmap as needed
- [x] Product Sign-off

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Participant Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link)
1.03 [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)

#### Resources gathered during the completion of this issue
2.01 [Wiki Mentor Research Overview Page](https://github.com/hackforla/internship/wiki/Mentor-Research-Overview)
2.02 [RP008 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-8-:-Mentor-Intake-Interviews)
2.03 [Mentor Google Drive Folder](https://drive.google.com/drive/u/0/folders/19I3g9sDrITthv0z4xV6ORuH1vhq80RQI)
2.04 [TWE: Research Roadmap: Mentor](https://docs.google.com/document/d/1ywAYj0NMXQy53kVuEOmtVUdvGy51HqT67xak0EJrFXE/edit?usp=sharing)

#### Report Template - Roadmap Overview
```
- [ ] Background
- [ ] Mentor Research Goals and Objectives
- [ ] Participants
- [ ] Research Framework and Methodologies
- [ ] Resources
- [ ] Notes
```

#### Report Template - Research Plan (each RP in the roadmap should be in the same structure and format)
```
- [ ] RP008: Mentor Intake Interviews
   - [ ] Goals
   - [ ] Requirements
   - [ ] Timelines
   - [ ] Delivery
   - [ ] Follow-up Options
   - [ ] Research Analysis 
```

**Comment by sunannie27** [comment]
For Research Output Overview bulletpoint, it is in TWE team members under resources for volunteers in the research section.

**Comment by sunannie27** [comment]
For the second bullet point, it's right click, then share then copy link. There's no get link.

**Comment by pandanista** [comment]
@sunannie27 Thank you for testing the template. I've incorporated the changes based on the feedback. The template #450 is ready to be reviewed by the project lead.
