### ISSUE TITLE
Epic: Pick SDGs for this project 

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#502]
### Overview
We need to pick SDGs for the Tech Work Experience project, so that our SDG can appear on the hackforla.org website, and we can align our goals and measurements to globally recognized societal and economic targets.

### Action Items
- [x] Create the following issues
   - [x] #515
   - [x] #518
   - [x] #519
   - [x] #520
   - [x] #506
   - [x] #521
   - [x] #516
   - [x] #505
   - [x] #517
   - [x] #504
   - [x] #522
   - [x] #523
   - [x] #524
   - [x] #525
   - [x] #526
   - [x] #503
   - [x] #527
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions

- [SDG Target and Indicator Spreadsheet](https://docs.google.com/spreadsheets/d/1mzlUg2l9-OfTlvI59wwpz9LzN1pAWUfXIYXDmSO_vq8/edit#gid=0)
- https://sdgs.un.org/
- https://github.com/hackforla/internship/wiki/SDGs

#### Body
```
### Overview
We need to determine if this SDG is relevant to the TWE project, so that we can align research, planing and marketing to that goal.

### Action Items
- [ ] Go to Resource 1, choose the SDG indicated in the title of this issue
   - [ ] Add link to that page into Resource 2
- [ ] Review both targets and indicators to determine which SGS are applicable to the project.
- [ ] Copy all Targets and Indicators to a comment below
   - [ ] Add notes to identify approporate Targets/Indicators and describe how you propose to use the indicator to measure the programs progress
   - [ ] Add notes to the Targets/Indicators that you think are not a good fit and why.
- [ ] Review with product team
- [ ] Update spreadsheet in resource 3 with details product team agrees on
### Resources/Instructions
1. https://sdgs.un.org/goals
2. WIKI: https://github.com/hackforla/internship/wiki/SDGs
3. https://docs.google.com/spreadsheets/d/1mzlUg2l9-OfTlvI59wwpz9LzN1pAWUfXIYXDmSO_vq8/edit#gid=0
```

**Comment by priyatalwar** [comment]
Wiki suggestion:
We should have it on the [overview](https://github.com/hackforla/internship/wiki/Volunteer-Overview)

**Comment by ExperimentsInHonesty** [comment]
Remaining task items are 
- [ ] reviewing any of the SDGs in the sheet that don't have done checkmarks
- [ ] Adding info to the Overview section of the wiki

**Comment by sunannie27** [comment]
Annie is doing the first 3, Sonalika is doing the other 3

**Comment by Sonalika982** [comment]
> Annie is doing the first 3, Sonalika is doing the other 3 for targets that are near

Done with the other 3. Need to go over it with Bonnie.

**Comment by sunannie27** [comment]
Looked over Sonalika's proposed questions. Confused about what basic services entail for indicator 1.4.1.

**Comment by sunannie27** [comment]
During PM meeting: we talked about asking a question about how interns thought about finances or jobs

**Comment by ExperimentsInHonesty** [comment]
Left off on the [far sheet ](https://docs.google.com/spreadsheets/d/1mzlUg2l9-OfTlvI59wwpz9LzN1pAWUfXIYXDmSO_vq8/edit?gid=0#gid=0&fvid=284143240)

If we pay interns for 5 weeks of 40 hours a week, at minimum wage ($16.50 in 2025) that will be $3300.  Will this push some households out of their benefits status.

**Comment by Sonalika982** [comment]
> Left off on the [far sheet ](https://docs.google.com/spreadsheets/d/1mzlUg2l9-OfTlvI59wwpz9LzN1pAWUfXIYXDmSO_vq8/edit?gid=0#gid=0&fvid=284143240)
> 
> If we pay interns for 5 weeks of 40 hours a week, at minimum wage ($16.50 in 2025) that will be $3300. Will this push some households out of their benefits status.

3 more left from the 'Far' column
Next steps include reviewing the SDGs that could be met.

**Comment by sunannie27** [comment]
Next time will discuss criteria for ranking SDGs

**Comment by sunannie27** [comment]
We are identifying relevant information from the spreadsheet to put on the wiki, currently numbering the action items, and sorting the questions based on whether they are asked before/after the internship

**Comment by sunannie27** [comment]
Cleaning up the spreadsheet with template given here: (https://chatgpt.com/share/6744c8a8-91fc-8008-9792-0d230c798023), paste in L of the column

**Comment by sunannie27** [comment]
Make an issue to create slidedeck for the chatgpt template

**Comment by sunannie27** [comment]
# Prompt for ChatGPT: 

```
apply this template to examples i will give you: Target: [Copy the exact text of the SDG target]
Indicator: [Copy the exact text of the SDG indicator]

TWE Program Approach: [Briefly describe the program’s relevant actions or initiatives]

Key Actions:

[Describe a specific action or question for measuring progress related to the indicator]
[Describe another action or question, if applicable]
[Continue with additional actions as needed]
Measurement Plan: [Explain how data will be collected, tracked, and analyzed to measure impact against the indicator]

example: 
```

**Comment by sunannie27** [comment]
On Thursday (2025-02-27), Research and research ethics leads agreed to look at the SDGs and give notes.

**Comment by sunannie27** [comment]
@tgitzen I addressed the comments you make on the SDG spreadsheet by providing an answer beneath them. Please review them when you get a chance and let me know if you have any more concerns.

**Comment by sunannie27** [comment]
@pandanista @jinyan0425 Please review Column L the Ask ChatGPT column in the SDG spreadsheet and leave any comments and concerns you may have in the column N.

**Comment by pandanista** [comment]
@sunannie27 After reviewing column L, @jinyan0425 and I feel that the “measurement plans” may be impractical or insufficient for real data collection and analysis.

**Comment by sunannie27** [comment]
ChatGPT KPI prompt: 

Give project KPIs using this structure: 

A Measure: Every KPI must have a measure. The best ones have more specific or expressive measures.
A Target: Every KPI needs to have a target that matches your measure and the period of your goal. These are generally a numeric values you’re seeking to achieve.
A Data Source: Each of these needs to have a clearly defined data source so there is no gray area in measuring and tracking each.
Reporting Frequency: Different measures may have different reporting needs, but a good rule to follow is to report on them at least monthly.
Owner: While this isn’t a mandatory aspect of your KPI statement, setting expectations of who will take care of tracking, reporting, and refining specific KPIs is helpful to your overall organizational plan.

Here is the following target:
"**Target**: By 2020, substantially reduce the proportion of youth not in employment, education, or training.

**Indicator**: Proportion of youth (aged 15-24 years) not in education, employment, or training.

**TWE Program Approach**: Ask the students who are applying if they are applying to any other internships/training programs and count the ones where our internship is the only training they would do.

**Key Actions**:  
1. Before the internship:  
   - Ask applicants if they are applying to any other internships or training programs and document their responses.  
   - Identify applicants who are only applying for the TWE internship as their sole opportunity for training or skill development.

2. Internship Process:  
   - Provide additional support and resources to applicants who are not participating in other training or educational programs to ensure they gain the necessary skills during the internship.

3. Post-internship:  
   - Track the employment, education, or training status of interns after completing the program.  
   - Identify whether the internship helped reduce the number of interns not engaged in employment, education, or training.

**Measurement Plan**:  
Data will be collected through surveys before and after the internship to track changes in the employment, education, or training status of participants.

- Pre-Internship:  
   - Collect baseline data on whether applicants are engaged in employment, education, or other training programs.

- Post-Internship:  
   - Follow up with interns to track their employment, education, or training status after completing the internship.  
   - Assess whether the internship has helped reduce the number of participants not in education, employment, or training.
"

**Comment by sunannie27** [comment]
Next step is to review research feedback and put ones to review in a new column to be discussed in PM/UX meeting. The reporting frequency is off for the KPIs so I need to reprompt it and will give it information about RACI.

**Comment by sunannie27** [comment]
Changed KPIs to include RACI information, need to go over new feedback given by research team on measurement plan

**Comment by pandanista** [comment]
@sunannie27: Just an update from Research,
- Jinyan won't have time or bandwidth to provide more feedback for the SDG goals. I have provided mine. 
- I also have synced up with @erin-ryan-93 this week, and she will follow up on the SDG goals discussion and revision on behalf of the research team with Bonnie.

**Comment by sunannie27** [comment]
Please provide update
1. Progress: Still reviewing Erin's comments, adding information to a column about proposed new content for internship, determining whether things are not applicable and why
2. Blockers: none
3. Availability: 5 hours 
4. ETA: end of the week
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.
