### ISSUE TITLE
TWE: Update issue template: Research Roadmap

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#529]
### Overview
We need to update the research roadmap issue template so it has the same formatting as the most recent templates we have made.

### Action Items
We need to create a template issue for a Research Roadmap, so that we can create a Research Roadmap, when we are ready and maintain consistency with the org (across projects) and the guides project.

### Action Items
- [x] Copy the example from Resource 1.01
  - [x] Paste into a comment below using details to make it collapsible
  - [x] Use the following text for the summary
```
## Current draft of Research Roadmap Issue Template
```
- [x] Copy the example from Resource 1.02
- [x] Paste into a comment below
  - [x] Use the following text for the summary
```
## Example draft of Research Roadmap Issue Template from the Guides Team
```
- [x] Paste the content from resource 1.01 into a new comment
   - [x] Add the title to the top of the paste
```
## New draft of Research Roadmap Issue Template
```
- Use the example to edit the last comment to fix our research roadmap template.
  - [ ] Add bullet headers and divide work in to sections
     - example: 
        - The current template has
        > - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder
        >    - [ ] Create a new folder in the drive called [number. name of type]
        - The example has this text and formatting
        > - Create new Google Drive Folder
        >    - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder (Resource # 1.04)
        >    - [ ] Create a new folder in the drive called [number. name of type] (e.g., 1. Mentor, 2. Intern) 
        >    - [ ] update the link in the resources below (Resource # 2.02)
  - [ ] Separate the resources into two sections
     - ```
        #### Resources for creating this issue
        ```
     - ```
        #### Resources gathered during the completion of this issue
        ```
  - [ ] Make sure each resource is in order of how it appears in the instructions
  - [ ] Number the resources
     - [ ] Add the numbers to the action items
- [ ] re-review the whole thing, to make sure 
   - [ ] all the instructions make sense
   - [ ] all the links resolve
   - [ ] the work is listed in the most logical order
- [ ] review with UX lead and get sign-off
- [ ] ask UX lead or product to update issue template Resource 1.03

### Resources/Instructions
1.01 [TWE Research Roadmap Issue Template](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research%2C+feature%3A+roadmap%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+0.50pt&projects=&template=research--roadmap.md&title=TWE%3A+Create+Research+Roadmap+%5Bname+of+type%5D)
1.02 [GUIDES Research Roadmap Issue Template](https://github.com/hackforla/guides/issues/142#issuecomment-1776004021)
1.03 [TWE Research Roadmap Issue Template file](https://github.com/hackforla/internship/blob/main/.github/ISSUE_TEMPLATE/research--roadmap.md)

**Comment by ExperimentsInHonesty** [comment]
## Current draft of Research Roadmap Issue Template

Title: TWE: Create Research Roadmap [name of type]

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a research roadmap to [describe what and why]

### Action Items
- [ ] Under "Projects," add to the Project Management Board
- [ ] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [ ] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [ ] link it to the Research Output Overview wiki page
- [ ] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [ ] Put back in Prioritized Backlog under new milestone
- [ ] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [ ] Create a new folder in the drive called [number. name of type]
- [ ] Make a new document using the report template 
  - [ ] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [ ] Name your document to be called TWE: Research Roadmap: [name of type] 
- [ ] Update the Table of contents (page 2) when you are finished with document
- [ ] UX Research Lead sign-off
- [ ] Product-sign off

### Resources/Instructions
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template for Research Roadmap](https://github.com/hackforla/internship/wiki/research-roadmap-wiki-template)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)
- [TWE: Template: Research Roadmap: [TYPE]](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)

**Comment by ExperimentsInHonesty** [comment]
<details><summary>Example draft of Research Roadmap Issue Template from the Guides Team</summary>
 
## New draft for guides project

Title: Guides: Research Roadmap [name of type]

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a research roadmap to [describe what and why]

### Action Items
- Add to Project Board and set up milestone
  - [ ] Under "Projects," add to the Project Management Board
  - [ ] Add milestone: 04.01 Prep for User Research of Gather examples guides
- [ ] Create a new page on the wiki for the roadmap
    - [ ] Copy the template for Research Roadmap (Resource # 1.01)
    - [ ] Click on the link for creating a new wiki page (Resource # 1.02)
      - [ ] Paste in the copied template 
      - [ ] Name it `[type name] Research Overview`
    - [ ] update the link in the resources below (Resource # 2.01)
    - [ ] link it to the Research Output Overview wiki page (Resource # 1.03)
- Create new Google Drive Folder
   - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder (Resource # 1.04)
     - [ ] Create a new folder in the drive called [number. name of type] (e.g., 1. Mentor, 2. Intern) (Resource # 1.03)
     - [ ] update the link in the resources below (Resource # 2.02)
- [ ] Make a new document using the report template 
  - [ ] Copy the research roadmap template (Resource # 1.05)
  - [ ] Move the document from "My Drive" to the shared drive guides folder that you just created.
  - [ ] Name the document to be called Guides: Research Roadmap: [name of type] 
  - [ ] update the link in the resources below (Resource # 2.03)
- Create the research roadmap content
   - [ ] Fill out the research roadmap
   - [ ] Update the Table of contents (page 2) when you are finished with the document
- Get Approvals/Make Edits
   - [ ] UX Research Lead sign-off
   - [ ] Product-sign off

### Resources/Instructions 

#### Resources for creating this issue
1.01 [WIKI template for Research Roadmap](https://github.com/hackforla/guides/wiki/research-roadmap-wiki-template)
1.02 [Click to create new page on wiki](https://github.com/hackforla/guides/wiki/_new)
1.03 [Research Output Overview](https://github.com/hackforla/guides/wiki/Research-Output-Overview)
1.04 [Google Drive, Research, 1. Research by Participant Type Folder](https://drive.google.com/drive/folders/1rFyhdgGs7wzGSujEzXXDDo02govPtyKV)
1.05 [Guides: Template: Research Roadmap]

#### Resources gathered during the completion of this issue
2.01 [RP000: Wiki Page]
2.02 [Google Drive, Research, 1. Research by Type, [Number. Name of Type]]
2.03 [Guides: Template: Research Roadmap: [TYPE]]

</p>
</details>

**Comment by ExperimentsInHonesty** [comment]
## new draft of Research Roadmap Issue Template

Title: TWE: Create Research Roadmap [name of type]

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to create a research roadmap to [describe what and why]

### Action Items
- [ ] Under "Projects," add to the Project Management Board
- [ ] Add milestone: 06.01.00 Research Roadmap Create Wiki Page
- [ ] Create a new page on the wiki for the roadmap called: `[type name] Research Overview` using the template for Research Roadmap
  - [ ] link it to the Research Output Overview wiki page
- [ ] Change milestone: 06.01.04 Research Roadmap Document Creation
  - [ ] Put back in Prioritized Backlog under new milestone
- [ ] Go to the Google Drive, Research, 1. Research by Type, Folder
   - [ ] Create a new folder in the drive called [number. name of type]
- [ ] Make a new document using the report template 
  - [ ] Move your document from "My Drive" to the shared drive internship folder that you just created.
- [ ] Name your document to be called TWE: Research Roadmap: [name of type] 
- [ ] Update the Table of contents (page 2) when you are finished with document
- [ ] UX Research Lead sign-off
- [ ] Product-sign off

### Resources/Instructions
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template for Research Roadmap](https://github.com/hackforla/internship/wiki/research-roadmap-wiki-template)
- [Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
-  [Google Drive, Research, 1. Research by Type Folder](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5)
- [TWE: Template: Research Roadmap: [TYPE]](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)

**Comment by pandanista** [comment]
- This issue can be replaced by issue #450.
- We can close this issue due to redundancy.
