### ISSUE TITLE
TWE: Revise Research: Create Roadmap Details Template

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#532]
### Overview
We need to update the Create Roadmap Details issue template so it has the same formatting as the most recent templates we have made.

### Action Items
We need to create a template issue for a Create Roadmap Details, so that we can create a Create Roadmap Details Template, when we are ready and maintain consistency with the org (across projects) and the guides project.

### Action Items
- [ ] Copy the example from Resource 1.01
  - [ ] Paste into a comment below using details to make it collapsible
  - [ ] Use the following text for the summary
```
## Current draft of Create Roadmap Details Issue Template
```
- [ ] Copy the example from Resource 1.01
  - [ ] Use the following text for the summary
```
## Revised Create Roadmap Details Issue Template from the Guides Team
```
  - [ ] Add bullet headers and divide work into sections
     - example: 
        - If the current template has
        > - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder
        >    - [ ] Create a new folder in the drive called [number. name of type]
        - The revised template should have this text and formatting
        > - Create new Google Drive Folder
        >    - [ ] Go to the Google Drive, Research, 1. Research by Type, Folder (Resource # 1.04)
        >    - [ ] Create a new folder in the drive called [number. name of type] (e.g., 1. Mentor, 2. Intern) 
        >    - [ ] update the link in the resources below (Resource # 2.02)
  - [ ] Separate the resources into two sections
     - ```
        #### Resources for creating this issue
        ```
     - ```
        #### Resources gathered during the completion of this issue
        ```
  - [ ] Make sure each resource is in order of how it appears in the instructions
  - [ ] Number the resources
     - [ ] Add the numbers to the action items
- [ ] re-review the whole thing, to make sure 
   - [ ] all the instructions make sense
   - [ ] all the links resolve
   - [ ] the work is listed in the most logical order
- [ ] review with UX lead and get sign-off
- [ ] ask UX lead or product to update issue template Resource 1.03

### Resources/Instructions
1.01 [TWE Research: Create Roadmap Details Issue Template, new issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research%2C+feature%3A+roadmap%2C+milestone%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--create-roadmap-details.md&title=TWE%3A+Research%3A+Create+Roadmap+Details+for+RP%5B%23%23%23%5D)
1.02 [Issue templates in the code](https://github.com/hackforla/internship/tree/main/.github/ISSUE_TEMPLATE)
1.03 [TWE Research: Create Roadmap Details Issue Template, file](https://github.com/hackforla/internship/blob/main/.github/ISSUE_TEMPLATE/research--create-roadmap-details.md)

**Comment by pandanista** [comment]
- This issue can be closed because it serves the same purpose as #450.
