### ISSUE TITLE
TWE: Research: Speaking Opportunity: EPIC 2024 

### ISSUE THREAD

**Issue by tgitzen** [hackforla/internship#536]
### Dependencies
- #514 

### Overview
Brainstorm topic ideas for EPIC 2024 conference

### Action Items
- [ ] Gather ideas for topic
- [ ] Put ideas in Google Doc
- [ ] Write abstract 
- [ ] Submit abstract by February 16

### Resources/Instructions
- #514 
- https://2023.epicpeople.org/
- [EPIC People Proposal](https://docs.google.com/document/d/14_8983yR4DLxlI2V8RNV4weANRl9wljwbvo6WHQalBM/edit)

**Comment by tgitzen** [comment]
[EPIC 2024 Pricing](https://2024.epicpeople.org/registration/):

Membership: $150
Main Program (before May 1): $750 or $1100
Main Program (after May 1): $850 or $1300

**Comment by ExperimentsInHonesty** [comment]
We decided against doing this because you have to pay to be an attendee and its quite pricey
