### ISSUE TITLE
TWE Design System Components: Update components according to M3

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#539]
### Dependency
- [x] #541
- [x] #540 
- [x] #542
- [x]  #543
- [x] #544

### Overview
We need to update the components to match M3 Material Design guidelines style

### Action Items
- [ ] Assign yourself to one of the dependency issues above
- [ ] Use M3 Material Design guidelines to assess the style differences
- [ ] Update the component design
- [ ] Communicate changes in the issue's comments and with the design team + all hands meeting
- [ ] Close the dependency issue
- [ ] Once all the dependencies are closed, close this issue

### Resources/Instructions
- Use Material Design (https://m3.material.io/) as guideline

**Comment by karina-sato** [comment]
Tysm @emwoodward. Dropdown should be a single component with different variants for the dropdown list. We need to know how far @mklmrgn already designed the Dropdown with checkbox to be able to combine both of these components. Let's define this in our Design Meeting.

**Comment by mklmrgn** [comment]
Created Elevation shadow styles according to Material 3's style guide. Created a brief overview of how to use perceived elevation for UI. Defined different drop shadows for each elevation (i.e. level 1, level 2, etc) in order to have standardized way to create elevation effect using shadows. 

Links to [Style in Design System ](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4764%3A3549&mode=design&t=Zh68ukr4pT6pyPcb-1) and [Microsite](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4785%3A805&mode=design&t=Zh68ukr4pT6pyPcb-1)

Microsite Image
<img width="657" alt="Screen Shot 2024-03-14 at 9 53 37 AM" src="https://github.com/hackforla/internship/assets/81997978/2f6398e1-b191-44bc-9fec-73b1021c4794">

**Comment by karina-sato** [comment]
Hi, @mklmrgn 
Can you add your comment in the right issue (https://github.com/hackforla/internship/issues/541), please?
Also, add the tag "Ready for dev" and move it to the Question/Review column. 

Thanks.

**Comment by karina-sato** [comment]
Closing this issue since all the dependencies were completed
