### ISSUE TITLE
TWE: Research Structure for Negative Research Experience Survey: Set up

### ISSUE THREAD

**Issue by doctorsandy** [hackforla/internship#548]
### Overview
We need to create a wiki structure and task list to support the development of a new research plan on Negative Research Experience Survey so that we can stay organized and consistent across all team members and working times.

### Action Items
- [x] Add the milestone: 06.01.01 Research Plan Create Wiki Pages.
- [x] Link the roadmap and its issue for your research into the resources below.
- [x] Create a label for your research plan, using the next number available. Check research plan number in Google drive's research folder and on wiki research output overview page on Github to make sure the number is correct.
    - [x] Add label to this issue and to the roadmap issue.
- [x] Create a new wiki page for it.
- [x] Use the template to copy the structure.
- [x] Link new wiki page to [Output overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview).
    - [x] Link it to the appropriate page under `Research Documents by Participant Type`.
    - [x] Link it under `Research Plan By Status` based on whether it is current or future research. If the research plan has been created or the data has been collected, then choose `Current Research`. If no research plan nor data has been collected, then choose `Future Research`.
    - [x] Link it under `Research by Plan Number`.
- [x] Fill out the wiki page with any information available, and include any links or documents that have already been created.
- [x] Go to the Shared Drives > Internships > Internships > Research > Research by Participant Type
    - [x] Open the appropriate participant type folder for this RP
    - [x] Check if there is a folder created for this research plan
    - [x] If yes, move onto the next section
    - [x] If no, please create a new folder called `RP### - [Replace TITLE OF RESEARCH]` in the "Research by Participant Type" folder
        - [x] Right click the folder you just created and click "Add shortcut to Drive"
        - [x] Go to All Locations > Shared drives > Internships > Internships > Research > Research by Plan # and name
        - [x] Click the "Add" button and then "Ok" to the pop-up
- [x] Customize issues that will need to be made by striking through unneeded issues from this list (put ~ before and after text to make it strikethrough).
    - [ ] Research Plan (internal)
    - [ ] Timeline
    - [ ] Forms/Survey/Script
    - [ ] ~Emails text to parents if participants are minor (if required)~ 
    - [ ] Recruitment plan for extra UXRs and participants(if required)
    - [ ] Identification of recruitment channels for UXRs and participants (if required)
    - [ ] Messaging for each type of channel (i.e. Slack, social)
    - [ ] Interest forms for UXRs
    - [ ] Selection criteria for UXRs and participants
    - [ ] Consent Plan for participants
    - [ ] Research Plan (external) - this is a subset of the internal
    - [ ] Consent Form
- [x] Update Outstanding Task Items on wiki page to reflect the necessary issues from the list above.
- [x] Have review meeting with Research Lead.
- [x] Have alignment meeting with Product for sign-off.
- [ ] Create issues using templates from the list of template issues.
- [ ] Release dependency on #547 

### Resources/Instructions
- [Label page](https://github.com/hackforla/internship/labels?q=RP)
- [Click to create new page on wiki](https://github.com/hackforla/internship/wiki/_new)
- [WIKI template](https://github.com/hackforla/internship/wiki/research-wiki-template)
- [Internship Google Drive](https://drive.google.com/drive/folders/0ACgRrPVkhnrvUk9PVA)
- [Output Overview wiki page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- [Research list of template issues](https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates#template-issues)
- [TWE: Research Roadmap: Other](https://docs.google.com/document/d/1j0FOrYd6eyoSb3u8Ek0QDZeFq9_9Qecz8JtUG021ZoA/edit#)
- Wiki [Research Plan 25: Negative Research Experiences Survey](https://github.com/hackforla/internship/wiki/Research-Plan-25:-Negative-Research-Experiences-Survey)
- #https://github.com/hackforla/internship/issues/327

**Comment by pandanista** [comment]
Here are some feedback that need to be incorporated for this template.

We need to mention wiki page and which section (assets) that the headers need to be included. See screenshot below.
<img width="949" alt="Screenshot 2024-03-13 at 4 45 39 PM" src="https://github.com/hackforla/internship/assets/57029070/6341af1d-eaad-4d30-b067-d7efd5eed15c">

The shortcut section needs to be at the same level of the template, not a level down. Also, we need to be clear by adding "Create a shorcut of the research plan folder in the "Research by Plan # and name" folder. See screenshot below:
<img width="949" alt="Screenshot 2024-03-13 at 5 02 29 PM" src="https://github.com/hackforla/internship/assets/57029070/7d88d0d4-6bfb-4258-8bc5-e96059caf2e7">

**Comment by ExperimentsInHonesty** [comment]
@pandanista 
- [ ] we should make a new issue to make the changes to the template you have specified above.  
- [ ] do you want sandy to make the issues for this research plan?  And if so, how does she know where the templates are and which ones we have templates for?

**Comment by pandanista** [comment]
The changes to the research structure has been incorporated. Please see [this comment](https://github.com/hackforla/internship/issues/531#issuecomment-1984639954) in #531.

Sure. We can create an issue using the existing template, and update it when the new one gets implemented. The existing templates can be found in the repo when selecting the new issue. Those are the templates we have used and/or approved so far. However, we don't have a new template for research plans yet, and the revision of the research plan template is one of issues in the priorotized backlog (#533).

I noticed the last action item is to release the roadmap issue #547, which has been created. If I recall correctly, roadmap needs to be created before the research plan, so we can also work on #547 before creating a research plan.

**Comment by ExperimentsInHonesty** [comment]
We have accepted this issue as complete
