### ISSUE TITLE
Research: Test: Issue Template: Research Roadmap Update/Creation

### ISSUE THREAD

**Issue by jinyan0425** [hackforla/internship#605]
### Dependencies
- https://github.com/hackforla/internship/issues/450

### Overview
We need to test the Research Roadmap Update/Creation Issue Template so that researchers can start making Research Roadmap Update/Creation issues on/for the various research plans/tasks

#### Details
We expect that the template you are testing will need some improvement and the fact that you don't know much about the project is a benefit here, because it's likely that the person making the template can overlook something that they already know how to do, but should be fully explained in the template so that people can do the work independently.

### Action Items
- [x] Go to the draft issue template in a comment on the issue where the draft you are testing is being created in Resource 1.01
- Copy the draft
   - [x] Clicking on three dots
   - [x] Choose edit 
   - [x] Select the contents (Use Select All **Mac:** ⌘+A or **PC**: Ctrl+A) 
   - [x] Copy the contents (Use Copy **Mac:** ⌘+C or **PC**: Ctrl+C) 
- Create the new issue
   - [x] Open a new blank issue template (Resource 1.02)
- Use the template to customize the issue
   - [x] Paste the draft into the new issue body
   - [x] Replace the title with the following text
      ```
      [TEST]
      ```
   - [x] Add the title from Resource 1.03 after the text: `[TEST]`.  This part is the title that would have been provided if the issue was made from a template instead of this testing process. 
   - [x] Submit the new issue
- Add Labels to the new issue
   - [x] Locate the labels associated with the template to be tested
      <details><summary>Example: See the highlighted section</summary>
      <p>
      <img width="400" alt="Screenshot 2024-05-28 at 11 35 24 AM" src="https://github.com/hackforla/internship/assets/57029070/4146ecaa-a893-41e7-9c65-3c0704eb1686">
      <p>
      </details>               
   - Add all the labels associated with the template to be tested in the new issue you just created
      - [x] Under Labels, choose gear <img src="https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png" width=25px>
      - [x] Select each label you located in the template to be tested 
   - [x] Add `status: template testing (step 2a)` label
- Add new issue to Project Board
   - [x] Under Projects, choose gear <img src="https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png" width=25px>, choose "Repository," and choose "TWE: Project Board"
   - [x] Under "TWE: Project Board", choose the down arrow and change the status to "In progress"
- Assign yourself the issue
   - [x] Under Assignees, Choose No one - assign yourself
- Use the new issue to test the template
   - [x] Follow the instructions in the new issue.  Your goal is to test that the template is sufficient for creating the issue and working on it, so for the purposes of this test, you are the creator of the issue and the assignee.
   - [x] If you have any questions about the instructions in this issue, leave a comment below and move this issue to the Questions column add `ready for research lead` label
   - [x] When you have question or suggestions about the instructions in the new issue  issue you are using to test the template, please:
      - [x] leave comments in that new issue, @ messaging the person who made the template in your comment
      - [x] move it to the Questions column
      - [x] add `ready for research lead` label
      - [x] @ message the person who made the template in Slack with a link to your comment.
   - [x] Review changes to the template made by author and repeat your review process until you are satisfied that it's ready for deployment
      - [x] Leave a comment on the template issue and the new issue you created with your sign-off (@ messaging both the template author and the Research Lead)
      - [x] Add the issues to the next Research team agenda (Resource 1.04) and @ messaging both the template author and the Research Lead via the team Slack channel with a link to the issue comments)

#### Research lead action items
- [x] review the template again
   - [ ] if changes are needed, send back to author with notes
   - [ ] if no changes are needed, deploy template, close issues.
      - [ ] Add link to the finished template to Resource 2.01

#### Resources for creating this issue
- 1.01 https://github.com/hackforla/internship/issues/450#issuecomment-1641000299
- 1.02 [Blank issue template](https://github.com/hackforla/internship/issues/new)
- 1.03 `[TEST]`TWE: IS24: RP025: Research Roadmap - Other: Create
- 1.04 https://github.com/hackforla/internship/issues/62

#### Resources gathered during the completion of this issue
- 2.01 Research Roadmap Update/Creation

**Comment by jinyan0425** [comment]
@pandanista 

Hello Ying, there is a minor point regarding this Testing Template, and likely most other templates, primarily associated with the GitHub Migration. 
It says:
>  Add new issue to Project Board
 > - [ ] Under Projects, choose gear, choose Repository, and choose Program Management
 > - [ ] refresh the browser tab
>  - [ ] Under program management, choose the down arrow and change the selection from New Issue Approval to In Progress


However, in the new version, there is no Program Management Repository. It is called TWE: Project Board. In addition, after I chose "TWE: Project Board", I could directly select "In Progress" for Status by choosing the down-arrow icon. I did not need to refresh the browser tab and then change the status from "New Issue Approval" to "In Progress".

Another minor point is about 
> - [ ] Remove the label Milestone: missing

Perhaps, we should also add ```Remove the label "feature: missing"``` since we have added ```feature: roadmap```. Or we should still keep ```feature: missing```?

**Comment by pandanista** [comment]
> @pandanista
> 
> Hello Ying, there is a minor point regarding this Testing Template, and likely most other templates, primarily associated with the GitHub Migration. It says:
> 
> > Add new issue to Project Board
> > 
> > * [ ]  Under Projects, choose gear, choose Repository, and choose Program Management
> > * [ ]  refresh the browser tab
> > * [ ]  Under program management, choose the down arrow and change the selection from New Issue Approval to In Progress
> 
> However, in the new version, there is no Program Management Repository. It is called TWE: Project Board. In addition, after I chose "TWE: Project Board", I could directly select "In Progress" for Status by choosing the down-arrow icon. I did not need to refresh the browser tab and then change the status from "New Issue Approval" to "In Progress".
> 
> Another minor point is about
> 
> > * [ ]  Remove the label Milestone: missing
> 
> Perhaps, we should also add `Remove the label "feature: missing"` since we have added `feature: roadmap`. Or we should still keep `feature: missing`?

Thank you for catching those, @jinyan0425. Addressed both sections mentioned above.

**Comment by pandanista** [comment]
- #606 is assigned to Sandy for testing.
- Should we leave #605 open till she finishes?

**Comment by jinyan0425** [comment]
> [@sunannie27](https://github.com/sunannie27) and [@KC-skc](https://github.com/KC-skc):
> 
> * Please give us a thumbs up if you will be review this issue, [`[TEST]` TWE: IS24: RP025: Research Roadmap: Update/Create #606](https://github.com/hackforla/internship/issues/606), and [TWE: Create Template Issue: Create or update research roadmap details  #450](https://github.com/hackforla/internship/issues/450).
>   
>   * [TWE: Create Template Issue: Create or update research roadmap details  #450](https://github.com/hackforla/internship/issues/450) is step 1 and 2b, the template draft.
>   * [Research: Test: Issue Template: Research Roadmap Update/Creation #605](https://github.com/hackforla/internship/issues/605) is step 2a, the testing template that set up the template test.
>   * [`[TEST]` TWE: IS24: RP025: Research Roadmap: Update/Create #606](https://github.com/hackforla/internship/issues/606) is step 3, the template test.
> * The research roadmap:update/Create template has finished the testing using RP025.
> * [RP025's research roadmap document](https://docs.google.com/document/d/1j0FOrYd6eyoSb3u8Ek0QDZeFq9_9Qecz8JtUG021ZoA/edit#bookmark=id.k8iqhgse577h) has been reviewed and approved by Bonnie and Tim.
> * Let me know what you think. Once approved, we can deploy the template in the repo.

Did you guys have any chance to discuss this in last week's all-leads meeting? @pandanista I also believe it is time to close this issue since the road map for RP025 has been created

**Comment by ExperimentsInHonesty** [comment]
- Template test is completed, so I am closing this issue. The template will be deployed under issue #450
