### ISSUE TITLE
`[TEST]` TWE: IS24: RP025: Research Roadmap: Update/Create

### ISSUE THREAD

**Issue by jinyan0425** [hackforla/internship#606]
## Research Roadmap Update/Creation Template

---
**name:** TWE: Template Issue: Research: Create or Update Research Roadmap Details 
**about:** This issue helps you structure your template issue to be consistent with our other template issues in research roadmap creation or updates
**title:** TWE: Research: RP025: Other Research Roadmap: Create/Update
**labels:** 'feature: research', 'feature: research roadmap', 'Participant Type: missing', 'Research 000: missing', 'size: 1pt', 'role: UI/UX research', 'milestone: missing', 'complexity: medium'
**assignees:** ' '

---
### Dependencies
- [x] A research setup structure (wiki, GitHub labels, Google Drive, etc.) has been created and approved https://github.com/hackforla/internship/issues/548. Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Structure+for+RP) to search the issue tab for potential results
- [x] https://github.com/hackforla/internship/issues/327 If there is an existing roadmap issue for Other,  Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Roadmap) to search the issue tab for potential results

### Overview
We need to update the details of the `Other Research Roadmap` for `RP025` so that the high level overview captures why we are doing all the research plans with this user group.

During these tasks you will be asked to add link to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

#### Customize Resource Links
- Customize Resource for Wiki Page Links
    - [x] Go to the wiki page: Research Output Overview (Resources # 1.01)
    - [x] Open relevant wiki page for Other
    - [x] Copy the link for the Other wiki page in your browser
    - [x] In Resources # 2.01, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
    - [x] Go to Other Research Overview wiki page (Resources # 2.01)
    - [x] Open relevant wiki page for RP025
    - [x] Copy the link for the RP025 wiki page in your browser
    - [x] In Resources # 2.02, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked <img width="100" alt="Screenshot 2023-02-21 at 6 47 15 PM" src="https://user-images.githubusercontent.com/57029070/220508425-5d0c0a1b-ef87-4ef2-a683-d4a21d5b2672.png">
- Customize Resource for Google Drive Folder by Participant Type
    - [x] Choose the "Research by Participant Type" folder on the shared Google Drive (Resources  # 1.02)
    - [x] Choose `Other` folder
    - [x] Copy the link of the `Other` folder
        1. Choose the three vertical dots on the right side of the `Other` folder  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link"
    - [x] In Resources # 2.03, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked
- Customize Resource for Other Research Roadmap doc
    - [x] Open the `Other` folder (linked in Resources # 2.03)
    - [x] Locate `TWE: Research Roadmap: Other` Google doc in the folder
    - [x] Copy the link of the `TWE: Research Roadmap: Other` Google doc
        1. Choose the three vertical dots on the top right side of the `TWE: Research Roadmap: Other` Google doc  <img width="50" alt="Screenshot 2023-10-10 at 5 58 13 PM" src="https://github.com/hackforla/internship/assets/57029070/f8b81823-6e66-40c1-b885-881c356baa96">
        1. Choose "Share"
        1. Choose "Copy link"
    - [x] In Resources # 2.04, place the link you just copied between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
    - [x] Choose "Update comment" in Github and make sure all the checkboxes above have been checked

#### Check & Fix Research Roadmap Document Formatting
- Review File Name
    - [x] Open the roadmap document (linked in Resources # 2.04)
    - [x] Confirm that the document uses the following naming convention: `TWE: Research Roadmap: Other`. If it does not follow that format, change the filename to match the project's naming convention.
- Compare Document Headings
    - [x] With the roadmap document open in one tab (linked in Resources # 2.04), open in another tab the `TWE: Template: Research Roadmap` (linked in Resources # 1.03)
    - [x] Click inside the roadmap document (linked in Resources # 2.04) and scroll through the document to determine whether the document contains the same headings as the research roadmap template (linked in Resources # 1.03).
- Adjust Incorrect Document Headings
    - [x] If the document does not have the correct headings, then adjust the headings according to the template.
        - [x] Check that each major heading is formatted as Header 1.
        - [x] To check formatting, place your cursor inside the heading text and look at the Styles dropdown menu next to the Font dropdown menu. If it needs adjusted, select the entire heading text and choose "Header 1" in the Styles dropdown menu.
    - [x] Check off the items below as you review their formatting (a check mark indicates that you've reviewed the item regardless of whether you fixed it or not).
        - [x] Background
        - [x] Other Research Goals and Objectives
        - [x] Participants
        - [x] Research Framework and Methodologies
        - [x] Individual Research Plans
            - [x] Research Plan Section Titles (see specific instructions in the next section)
        - [x] Resources
        - [x] Notes
- Review Research Plan Names and Formatting
     - [x] Confirm that all the research plans section titles are named in `RP000: [TITLE OF RESEARCH]` format. 
     - [x] Confirm each research plan name in the research roadmap document is correct by checking Other Research Output Overview page (linked in Resources # 2.01). If they need to be adjusted, fix them according to how they are named in the Research Output Overview page (linked in Resources # 2.01) or ask the UXR lead if there is no corresponding wiki page.
     - [x] Confirm that the research plan names are formatted as Header 2 in the document heading options.
        - [x] To check, place your cursor inside the heading text and look at the Styles dropdown menu next to the Font dropdown menu. If it needs adjusted, select the entire heading text and choose "Header 2" in the Styles dropdown menu.
    - [x] Confirm research plan's subsection has the following sections
        - Goals
        - Requirements
        - Timelines
        - Delivery
        - Follow-up Options
        - Research Analysis
    - [x] Confirm research plan's subsection are formatted as Header 3.  
        - [x] To check, place your cursor inside the heading text and look at the Styles dropdown menu next to the Font dropdown menu. If it needs adjusted, select the entire heading text and choose "Header 3" in the Styles dropdown menu.

#### Update and/or create research roadmap details for Other and RP025
- Update Overview Sections
    - [ ] If the Other research roadmap overview sections have been drafted, please review and revise the general overview of research roadmap as necessary. 
        - [ ] Compare the Other Research Roadmap against the Other Research Overview Wiki Page (linked in Resources # 2.01). If you notice any discrepancy, please inform the team about the discrepancy in the Other Research Roadmap by inserting a comment in the Google doc.
        - [ ] Read through the following sections to see if they make sense. Check for typos, completeness, and general formatting as you read through each section. If you think the content should be revised, please use "Suggesting Mode" to suggest revisions. <img width="300" alt="Screenshot 2023-07-20 at 5 17 12 PM" src="https://github.com/hackforla/internship/assets/57029070/d7a45458-afd1-4bb1-b526-befa3dd34188"> If you have questions or concerns, please insert comments in the Other Research Roadmap Google doc for the UX Research Lead to review.
            - [ ] Background about the project/product.
            - [ ] Research goals and/or objectives of the type of research.
            - [ ] Summary of the target participants.
            - [ ] Research framework and methodologies.
    - [x] If the Other research roadmap has not been drafted, please fill out the overview sections of the research roadmap by following the steps
        - [x] Open the Research Roadmap for Other if it is not open in your browser (Resources # 2.04)
        - [x] Make sure the structure and format of a research roadmap stays consistent. Check `Research Roadmap Template` (linked in Resources # 1.03) or `Report Template - Roadmap Overview` below Resources for the structure of the roadmap overview sections if needed.        
        - [x] Go to Other Research Overview wiki page (Resources # 2.01) to gather information  
        - [x] Refer to an existing research roadmap as an example for the research roadmap overview you are creating (Resources # 1.04)
        - [ ] Fill out the overview sections of Other research roadmap based on the information you gathered
            - [ ] Background
            - [ ] Other Research Goals and Objectives
            - [ ] Participants
            - [ ] Research Framework and Methodologies   
- Update Research Plan Section
    - [ ] If the research roadmap for RP025 has been created, please review and revise each subsection under the RP025's research roadmap as necessary. 
        - [ ] Compare the RP025's research roadmap subsections against the RP025's wiki page (linked in Resources # 2.02). If you notice any discrepancy, please inform the team about the discrepancy in the RP025's research roadmap by inserting a comment in the Google doc.
        - [ ] Read through each section to see if they make sense. Check for typos, completeness, and general formatting as you read through each section. If you think the content should be revised, please use "Suggesting Mode" to suggest revisions. <img width="300" alt="Screenshot 2023-07-20 at 5 17 12 PM" src="https://github.com/hackforla/internship/assets/57029070/d7a45458-afd1-4bb1-b526-befa3dd34188"> If you have questions or concerns, please insert comments in the RP025 Research Roadmap Google doc for the UX Research Lead to review. 
            - [ ] Goals
            - [ ] Requirements
            - [ ] Timelines
            - [ ] Delivery
            - [ ] Follow-up Options
            - [ ] Research Analysis
    - [x] If the research roadmap for RP025 has not been created, please fill out the research roadmap for RP025 by following the steps
        - [x] Open the Research Roadmap for Other if it is not open in your browser (Resources # 2.04)
        - [x] Identify the placement of RP025's research roadmap in the ascending sequence in the Google doc
        - [x] Make sure to copy the structure and format of a research plan's research roadmap to keep the documentation consistent. Copy `Report Template - Research Plan` below Resources to the research roadmap Google Doc if needed. 
            - [x] Rename the research plan title `RP???: Research Plan Name` with `RP025: Negative Research Experiences Survey`
            - [x] Apply formatting to `RP025: Negative Research Experiences Survey` 
                - [x] Apply "Header 2" in section title `RP025: Negative Research Experiences Survey`
                - [x] Apply "Header 3" to all the subsections: Goals, Requirements, Timelines, Delivery, Follow-up Options, and Research Analysis        
        - [x] Go to RP025's wiki page (Resources # 2.02) to gather information 
        - [ ] Refer to an existing research roadmap as an example for the research roadmap overview you are creating (Resources # 1.04)
        - [x] Fill out the research roadmap for RP025 based on the information you gathered
            - [x] Goals
            - [x] Requirements
            - [x] Timelines
            - [x] Delivery
            - [x] Follow-up Options
            - [x] Research Analysis
- Update the Resource Section at the end of research roadmap Google doc
    - [x] Check the final sections (Resources and Notes) to see if they are updated, have functional links, and do not include redundant information.
        - [x] In the Resources section, double check that links to the individual research plans are accurate and complete according to the Overview wiki page (Resources # 2.01).
- [x] Go to the Table of Contents of Other Research Roadmap document once you finish revising or updating the research roadmap draft
- [x] Update the Table of Contents by clicking on the circle icon <img width="132" alt="Screenshot 2023-07-13 at 4 01 49 PM" src="https://github.com/hackforla/internship/assets/57029070/94ac0437-995c-4734-9780-27e6c55ce230">

#### Next steps
- [x] Discuss and review the research roadmap document at the next meeting
- [x] Make new issues for research plan(s) under the Other Research Roadmap if the research plan issue hasn't been created yet
    - [x] Include this issue as the dependency in the newly created research plan issue
- Product sign-off 
    - [ ] Research roadmap Google doc (Resources # 2.04)
    - [ ] New issues created for research plan(s) under the Other Research Roadmap    
- [ ] Release the research plan issue when this issue is closed

#### Resources for creating this issue
1.01 [Wiki: Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
1.02 [Google Drive Folder: Research by Participant Type](https://drive.google.com/drive/folders/1f5Qgq-ikT_UwcgRBuoBamqY0Wacsg9f5?usp=share_link)
1.03 [TWE: Template: Research Roadmap](https://docs.google.com/document/d/1_4ihjsfKFiRNEZQnlihhRMYwPaM7WoSZNauY3GTbdpI/template/preview)
1.04 [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit?usp=sharing)
1.04.01 [Individual Research Plan Roadmap Example: RP001](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#heading=h.awbtyfb4whri)
1.04.02 [Individual Research Plan Roadmap Example: RP006](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#heading=h.8pgwqzm57ukj)

#### Resources gathered during the completion of this issue
2.01 [Wiki Other Research Overview Page](https://github.com/hackforla/internship/wiki/Other-Research-Overview)
2.02 [RP025 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-25:-Negative-Research-Experiences-Survey)
2.03 [Other Google Drive Folder](https://drive.google.com/drive/u/1/folders/1Vb9TVPskfealzK2skTk5R6uN_RqKsodO)
2.04 [TWE: Research Roadmap: Other](https://docs.google.com/document/d/1j0FOrYd6eyoSb3u8Ek0QDZeFq9_9Qecz8JtUG021ZoA/edit?usp=drive_link)

#### Report Template - Roadmap Overview
```
- [ ] Background
- [ ] Other Research Goals and Objectives
- [ ] Participants
- [ ] Research Framework and Methodologies
- [ ] Resources
- [ ] Notes
```

#### Report Template - Research Plan (each RP in the roadmap should be in the same structure and format)
```
- [ ] RP025: Negative Research Experiences Survey
   - [ ] Goals
   - [ ] Requirements
   - [ ] Timelines
   - [ ] Delivery
   - [ ] Follow-up Options
   - [ ] Research Analysis 
```

**Comment by jinyan0425** [comment]
@pandanista 

Hi Ying, I will comment on the Research Roadmap Update/Creation Template in this comment. It is developing.

1. [MINOR] I may change the label `feature: research roadmap` to `feature: roadmap` to match the actual label.

**Comment by pandanista** [comment]
> @pandanista
> 
> Hi Ying, I will comment on the Research Roadmap Update/Creation Template in this comment. It is developing.
> 
> 1. [MINOR] We may change the label `feature: research roadmap` to `feature: roadmap` to match the actual label.
- Good catch. We should update using `feature: roadmap` since we don't have `feature: research roadmap`, but let's check in with product to make sure the `feature: roadmap` label is intended for research roadmaps.

> 2. [MINOR] The action item below is easy for experienced HfLA researchers to follow. But new researchers may feel difficult to locate the specific RP folder on the[ Research Output Overview](https://github.com/hackforla/internship/wiki/Research-Output-Overview) page. Shall we add one more step such as  `Choose 'Research Plans, sorted by number'`
> 
> > * [ ]  Choose the appropriate research roadmap or research plan folder (ie., RP###) on the wiki page

- Sure, that makes sense. Edited in the [template](https://github.com/hackforla/internship/issues/450#issuecomment-1641000299).

> 3. **[MAJOR]** Does the action below mean to remove `[TEST]` in the title?
> 
> > * Update the issue title
> >   - [ ] Copy
> >   `        TWE: IS[Replace YY]: RP[Replace 000]: Research Roadmap: Update/Create        `
> 
- Not in this case since we are testing the template. 
- When the template is deployed, then the [test] won't be needed. That's why it didn't have [test] in the template.

> 4. [MINOR] Due to migration, `Project Management` no longer exists in the Repository. Instead, it is TWE: Project Board.
> 
> > * [ ]  Under Projects, choose gear ![Screenshot 2023-01-11 at 10 50 11 AM](https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png), choose `Repository`, and choose `Program Management`
> 
- Edited in the [template](https://github.com/hackforla/internship/issues/450#issuecomment-1641000299).

> 5. [MINOR] The action item below: Above "Dependencies" or "Overview"?
> 
> > * [ ]  After all the checkboxes above are complete and the issue is ready to be worked on, delete all text below the "Instructions for Creating this Issue" (top heading) and above "Overview" (heading below) -- i.e., the issue assignee will never see this part
> 
- It should be "Dependencies". Edited in the [template](https://github.com/hackforla/internship/issues/450#issuecomment-1641000299).

> 6. **[MAJOR]** For the section **Dependencies**:
>    
>    1. Shall the assignee tick the two action items after replacing the links?
>    2. Shall the assignee remove the instruction texts, such as "If there is an existing roadmap issue for Other, Use this [URL](https://github.com/hackforla/internship/issues?q=is%3Aissue+TWE%3A+Research+Roadmap) to search the issue tab for potential results", and
>    3. What if the requested issues and links have not been created? There are no instructions for this scenario.
- 1. Either the assignee or the person who assigns the issue should tick the two action items.
- 2. Ideally yes after the issue links are included in the Dependencies. For example, they can add the issue number where it says [REPLACE WITH RESEARCH ROADMAP ISSUE #], and they can remove the instruction texts. However, if the instruction texts are not removed, that is okay since it doesn't affect the process or the results.
- 3. If the requested issues and links have not been created, then it means at least one action item has not been ticked, which indicates it is the blocker. In that case, a new issue to tackle the dependency needs to be created, and this issue needs to be put into the icebox.
- If there are better ways to phrase the process, please do share.  

> 7. **[EPIC]** I need more information to draft the overview sections for Other research roadmap because Resource # 2.01 [Wiki Other Research Overview Page](https://github.com/hackforla/internship/wiki/Other-Research-Overview) provides little information. Or this instruction means that I should read through all RPs for Other and then summarize?
> 
> > * [ ]  Fill out the overview sections of Other research roadmap based on the information you gathered
> 
- I hear you, and we can discuss it more on the overview section of Other research roadmap. For now, we are just setting up the structure so Sandy could fill out the information on RP025.

> 8. **[EPIC]** Similar for drafting the details for the RP025's research roadmap. I can draft the research summary based on Resource # 2.02 [RP025 Wiki Page](https://github.com/hackforla/internship/wiki/Research-Plan-25:-Negative-Research-Experiences-Survey) but the information for timeline, delivery, and requirements are limited.
> 
> > * [ ]  Fill out the research roadmap for RP025 based on the information you gathered
> 
- That is also for Sandy. :)

> 9. [MINOR] Resource # 1.04 [TWE: Research Roadmap: Interns](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#heading=h.x60q1ibhwskf) lacks the sub-title (level 1 heading): `Individual Research Plans `
- I added 1.04.01 and 1.04.02 as examples to demo the individual research plan roadmap based on your suggestion. Would that be sufficient? 
- 1.04.01 [Individual Research Plan Roadmap Example: RP001](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#heading=h.awbtyfb4whri)
- 1.04.02 [Individual Research Plan Roadmap Example: RP006](https://docs.google.com/document/d/1BKFiKRcqDovcaKsEqtWMPU8vUs_Mq3gjNYLU6A5E7dQ/edit#heading=h.8pgwqzm57ukj)

**Comment by pandanista** [comment]
@doctorsandy Hi Sandy, the RP025's research roadmap issue has been created and edited, so it is now ready for you to fill out the research roadmap info. 
- The RP025's research roadmap document has been set up, please check Resources 2.04.
- The unchecked action items circled in the screenshot under the "Update Research Plan Section" is the part we need your help with. <img width="500" alt="Screenshot 2024-07-31 at 6 40 02 PM" src="https://github.com/user-attachments/assets/a1bf9021-59ea-4127-8d46-ce2a42c128ee">
- Example for individual research plan's roadmap documents can be found in Resources 1.04 (See 1.04.01 and 1.04.02).

Thank you, and let me know if you have any questions.

**Comment by jinyan0425** [comment]
Hi All, @pandanista @doctorsandy @bonniewolfe:

I summarized Sandy's inputs for the [RP025 roadmap](https://docs.google.com/document/d/1j0FOrYd6eyoSb3u8Ek0QDZeFq9_9Qecz8JtUG021ZoA/edit#heading=h.szz0j4wioe4s) to be more concise and aligned with the other RP roadmaps. **All of my inputs are in green (suggesting mode). Sandy (@doctorsandy), could you please review it and let me know if any updates are needed. **Please do not delete what you've written as they will be used in developing the research plan.**

I wasn't able to complete the section because roadmaps for other RPs under "Other Research" (e.g., RP003, RP004, RP005, RP021) have not been created yet. The wiki page for ["Other Research"](https://github.com/hackforla/internship/wiki/Other-Research-Overview) also lacks information I can reference. I assume this section is supposed to summarize general information for all "Other Research" plans, not just RP025. @pandanista @bonniewolfe 

> - [ ] Fill out the overview sections of Other research roadmap based on the information you gathered
>      - [ ] Background
>      - [ ]  Other Research Goals and Objectives
>      - [ ] Participants
>      - [ ] Research Framework and Methodologies

Additionally, should we create an issue for developing the Research Plan for RP025 before I proceed with it, based on Sandy's inputs in the roadmap document? @pandanista @bonniewolfe 

> - [ ] Make new issues for research plan(s) under the Other Research Roadmap if the research plan issue hasn't been created yet

Thank you all!

**Comment by pandanista** [comment]
@sunannie27: 
- The research roadmap:update/Create template has finished the testing. #606 is the testing issue.
- Let me know what you think. Once approved, we can deploy the template in the repo.
