### ISSUE TITLE
Research: Test: Issue Template: Rapid Qualitative Analysis (RQA): Pre-process

### ISSUE THREAD

**Issue by jinyan0425** [hackforla/internship#620]
### Dependencies
- https://github.com/hackforla/internship/issues/618

### Overview
We need to test the Rapid Qualitative Analysis (RQA): Pre-process Issue Template so that researchers can start making Rapid Qualitative Analysis (RQA): Pre-process issues on/for the various research plans/tasks

#### Details
We expect that the template you are testing will need some improvement and the fact that you don't know much about the project is a benefit here, because it's likely that the person making the template can overlook something that they already know how to do, but should be fully explained in the template so that people can do the work independently.

### Action Items
- [x] Go to the draft issue template in a comment on the issue where the draft you are testing is being created in Resource 1.01
- Copy the draft
   - [x] Click on three dots
   - [x] Choose edit 
   - [x] Select the contents (Use Select All **Mac:** ⌘+A or **PC**: Ctrl+A) 
   - [x] Copy the contents (Use Copy **Mac:** ⌘+C or **PC**: Ctrl+C) 
- Create the new issue
   - [x] Open a new blank issue template (Resource 1.02)
- Use the template to customize the issue
   - [x] Paste the draft into the new issue body
   - [x] Replace the title with the following text
      ```
      `[TEST]` 
      ```
   - [x] Add the title from Resource 1.03 after the text: `[TEST]`.  This part is the title that would have been provided if the issue was made from a template instead of this testing process. 
   - [x] Submit the new issue
- Add Labels to the new issue
   - [x] Locate the labels associated with the template to be tested (see Resource 1.01)
      <details><summary>Example: See the highlighted section</summary>
      <p>
      <img width="400" alt="Screenshot 2024-05-28 at 11 35 24 AM" src="https://github.com/hackforla/internship/assets/57029070/4146ecaa-a893-41e7-9c65-3c0704eb1686">
      <p>
      </details>               
   - Add all the labels associated with the template to be tested in the new issue you just submitted
      - [x] Under Labels, choose gear <img src="https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png" width=25px>
      - [x] Select each label you previously located from the template to be tested
   - [x] Add `feature: template test (step 3)` label to the new issue you just submitted
- Add new issue to Project Board
   - [x] Under Projects, choose gear <img src="https://user-images.githubusercontent.com/57029070/211904252-46521281-b8f8-495d-b31f-d06e425f0096.png" width=25px>, choose `Repository`, and choose `TWE: Project Board`
   - [x] Under `TWE: Project Board`, choose the down arrow and change the status to `In Progress`
- Assign yourself the issue
   - [x] Under Assignees, Choose No one - assign yourself
- Use the new issue to test the template
   - [x] Follow the instructions in the new issue.  Your goal is to test that the template is sufficient for creating the issue and working on it, so for the purposes of this test, you are the creator of the issue and the assignee.
   - [x] If you have any questions about the instructions in this issue, leave a new comment below. Then move this issue to the `Questions/Review` column, and add `ready for research lead` label
   - [x] When you have question or suggestions about the instructions in the new issue you are using to test the template, please:
      - [x] leave comments in that new issue, @ messaging the person who made the template in your comment
      - [x] move it to the Questions/Review column
      - [x] add `ready for research lead` label
      - [x] @ message the person who made the template in Slack with a link to your comment.
   - [x] Review changes to the template made by author and repeat your review process until you are satisfied that it's ready for deployment
      - [ ] Leave a comment on the template issue and the new issue you created with your sign-off (@ messaging both the template author and the Research Lead)
      - [ ] Add the issues to the next Research team agenda (Resource 1.04) and @ messaging both the template author and the Research Lead via the team Slack channel with a link to the issue comments)

#### Research lead action items
- [x] review the template again
   - [ ] if changes are needed, send back to author with notes
   - [x] if no changes are needed, deploy template, close issues.
      - [x] Add link to the finished template to Resource 2.01

#### Resources for creating this issue
- 1.01 https://github.com/hackforla/internship/issues/618#issuecomment-2327661203
- 1.02 [Blank issue template](https://github.com/hackforla/internship/issues/new)
- 1.03 [TEST]TWE: IS21: RP001:Rapid Qualitative Analysis (RQA): Pre-process
- 1.04 https://github.com/hackforla/internship/issues/62

#### Resources gathered during the completion of this issue
- 2.01 [Rapid Qualitative Analysis (RQA): Pre-process](https://github.com/hackforla/internship/issues/new?assignees=&labels=complexity%3A+medium%2C+Feature%3A+research+analysis%2C+feature%3A+research%2C+milestone%3A+missing%2C+Participant+Type%3A+missing%2C+Research+000%3A+missing%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&projects=&template=research--rapid-qualitative-analysis--rqa---pre-process-.md&title=TWE%3A+IS%5BReplace+YY%5D%3A+RP%5BReplace+000%5D%3A+Rapid+Qualitative+Analysis+%28RQA%29%3A+Pre-process)

**Comment by pandanista** [comment]
- Testing is done in issue #621.
- Template is in issue #618.

**Comment by jinyan0425** [comment]
> * Testing is done in issue [`[TEST]`  TWE: IS21: RP001:Rapid Qualitative Analysis (RQA): Pre-process #621](https://github.com/hackforla/internship/issues/621).
> * Template is in issue [TWE: Create Template Issue: Rapid Qualitative Analysis (RQA): Pre-process #618](https://github.com/hackforla/internship/issues/618).

Thanks!

**Comment by pandanista** [comment]
Updated the issue with the template url in resources 2.01. 
Closing this issue as it is now completed.
