### ISSUE TITLE
logo, color pallet , typography, branding initial work

### ISSUE THREAD

**Issue by priyatalwar** [hackforla/internship#68]
### Overview
To achieve consistency, communicate  and present with clarity, we need to create our brand identity

### Action Items
- [ ] Create a color palette
   - [ ] Kelly will try 3-color combos with each word having its own color
      - TechWorkExperience
      - TechWorkInternship 
    - [ ] Color Palette - Still needs work depending on if we decided to keep the multi-color logo.    
- [ ] Design a logo
- [ ] Typography
   - [ ] Please vote font style.  Heading and Body.  Leave a comment if any.  
      - Currently on pause because we need to see what the fonts look like with the colors
- [ ] Improve images

### Resources/Instructions
[Google doc -Thoughts On Research Report Deck And Branding ](https://docs.google.com/document/d/1TiymWJCs0kPsi3JFgUX2VDFuJM6RgdyqpJBGX36-Q2A/edit)

#### Related issues
- [Brand Values](https://github.com/hackforla/internship/issues/68#issuecomment-998150906)
- #96 
- [All issues with the branding label](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+branding%22)
- #97

### Related work that is ready to be done or is being done: 

- [ ] Comp Analysis (example: Intern works) #84 
- [ ] #98
- [ ] #99
- [ ] Seena is going to take a pass at use cases from a PM point of view #97

#### Use these links
- [Internship project figma file](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=0%3A1)
- [ FigJam Brand Exercise](https://www.figma.com/file/VgxjTXP3PJhzZxMeMURf2f/Branding-Exercise?node-id=0%3A1) -  for Brand Identity
- Kelly's [recording](https://drive.google.com/file/d/1c4UE7_6EIOL9J_OLUCAnb6IO9Jo1iztx/view?usp=sharing) of what she expects from the brand personality exercise

#### Results
- Down to two names
  - TechWorkInternship
  - TechWorkExperience
- Decided on Tagline: 
  - Where learning STEMS from doing
- Decided on Brand personality
  - [Name of Brand] has an inclusive, supportive, welcoming, experimental, fun, collaborative, forgiving, can-do personality.
- Decided on using colorful logo 
  - coming soon
- Brand Values
   - Supportive: We incorporate mentorship into our culture.  It supports through defined interaction with peers, pros and managers
   - Collaboration:  We share ideas and knowledge on diverse cross functional teams to make better software.
   - Practical, Impactful & Fun: We have fun while work on visible projects addressing real world problems.
   - Innovative:  We use Agile techniques, open source and ethical structures to achieve extraordinary results. 
   - Structured / Adaptive: We believe a program should be structured to reach your goals, and adaptive to your learning methodologies and creative thinking.
   -  Inclusivity: We create a place of kindness, generosity and belonging, where you can feel welcome and confident irrespective of age, skill, background, and experience.

#### Depreciated links
- [Kelly's view only Brand Platform draft](https://www.figma.com/file/WcNk1SN4Hmdo7vpBX5O5Oa/Internship-Branding-Platform.?node-id=0%3A1) - the content from this was moved to our main figma file on 2021-12-20
- [Font and Color Figma](https://us02st1.zoom.us/web_client/rnqzmq/html/externalLinkPage.html?ref=https://www.figma.com/file/kbMrSrWEWmWU8ykoWz4jhF/Branding-style-guide-examples?node-id=0%25253A1) - this got copied to the Internship team figma on 2021-12-07

**Comment by priyatalwar** [comment]
Add missing label: Collaborative work

**Comment by maruja0516** [comment]
Let let me know how I can contribute with this. I will be more than happy to help.

**Comment by kellychoe** [comment]
For Next Week (11/11/2021) : 

1) Brand Values Part 2- Take the Attributes we've identified, see below and define them as our values.  See Cars.com for ref. and will add the Hotel Chocolate Values for reference in the Figjam.

Our Brand Attributes:
Supportive
Collaboration
Practical 
Innovative
Structured / Adaptive
Inclusive
Fun

2) Project Name Scenario exercise @ Bonnie.

To Do for the future:

- Comp Analysis (example: Intern works) 
- Google search our brand attributes and taglines- to see results.

**Comment by kellychoe** [comment]
1. @ExperimentsInHonesty Bonnie to add definitions for the Brand Values and edit to the final internship core values.
2. For those that left,  Inclusive yet Adaptive blank, please complete. 
3. The rest of the team needs to vote on the Brand name.
4. Test out top-rated brand names with students.  Survey...?  InternshipSTEM and STEMintoREAL.
5. Land on Brand mission statement, tagline.

**Comment by kellychoe** [comment]
@ExperimentsInHonesty, I created a quick branding Platform for you to share with other teams for name suggestions.  Please note it's not for actual fonts or visual guides.   It's per your request "a prettier, simpler" view.  It's a Figma file. Let me know if you have trouble opening it.  I can share in slack as well.   

Internship Branding Platform (https://www.figma.com/file/WcNk1SN4Hmdo7vpBX5O5Oa/Internship-Branding-Platform.?node-id=0%3A1)

**Comment by Rabia2219** [comment]
> @ExperimentsInHonesty, I created a quick branding Platform for you to share with other teams for name suggestions. Please note it's not for actual fonts or visual guides. It's per your request "a prettier, simpler" view. It's a Figma file. Let me know if you have trouble opening it. I can share in slack as well.
> 
> Internship Branding Platform (https://www.figma.com/file/WcNk1SN4Hmdo7vpBX5O5Oa/Internship-Branding-Platform.?node-id=0%3A1)

Looks good...some thoughts:
the Mission Statement needs a little tweaking? 
also for the values...maybe Collaborative and Inclusive sound better?

**Comment by kellychoe** [comment]
@Rabia2219 Yes, agree. The Misson Statement and also the Brand Personality description need tweaking.  A better definition of why Sesame Street personality is relevant to the internship.  I'll leave that for our marketing/content writer team!  😄  or we can look at it as a group. I started pulling  Fonts and colors. I hope to review this with the team next time.

**Comment by kellychoe** [comment]
To Do: (Home Work)  

1) Please vote on font style.  Heading and Body.  Leave a comment if any.  
2) Color Palette - Still needs work depending on if we decided to keep the multi-color logo.  But feel free to comment, any feedback is much appreciated!  
3) FYI - The brand platform and style guide are now in the Internship Teams Project.   Style Guide(https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A2)

**Comment by kellychoe** [comment]
Hi Guys, 

@hackforla/internship I know most of you didn't get a chance to vote on the fonts. Please take a moment to vote on one each Header and Body font.  I created color dots for voting.  

@ExperimentsInHonesty Let me know if there are any other name suggestions from other teams.

**Comment by ExperimentsInHonesty** [comment]
Kelly will try 3-color combos with each word having its own color

**Comment by priyatalwar** [comment]
Update 12/16: Created an issue for user testing https://github.com/hackforla/internship/issues/96

**Comment by ExperimentsInHonesty** [comment]
- [ ] Create task issues for each team member for brand values
- #87 
- #86 
- #85
- #91 
- #90 
- #88 
- #89 
- [ ] Hide this comment when all the issues are closed

**Comment by seenaiype** [comment]
For Seena's review - #97

**Comment by ExperimentsInHonesty** [comment]
@kellychoe I have updated the top of the issue to reflect where we are now and what everyone is working on related to this effort.

Question for you: Do you think we have resolved this suggestion that you made here: https://github.com/hackforla/internship/issues/68#issuecomment-977723476
> A better definition of why Sesame Street personality is relevant to the internship. I'll leave that for our marketing/content writer team! 😄 or we can look at it as a group.

With this info, or do you think we need to go further?
- Decided on Brand personality
  - BigBird: kind, curious, uses his words, inclusive/friendly/welcoming, supportive/encouraging
  - Adults:  there to help the journey
  - "Everyone makes mistakes, so why can't you?"
  - "If you keep practicing, you can do anything.”

**Comment by kellychoe** [comment]
@ExperimentsInHonesty - I was hoping for a short paragraphic of how sesame street inspired us or the similar personality trades that the internship shares with sesame street.  The above describes Sesamesteet, we need a few sentences to describe our connection and similar personality/Character trade with sesame street.   this is currently what we have...

**Comment by kellychoe** [comment]
[Uploading Personality.pdf…]()

**Comment by kellychoe** [comment]
@hackforla/internship- I forgot to share this last time. 

Web Accessibility for Visual Disabilities (https://webaim.org/articles/visual/colorblind)

**Comment by ExperimentsInHonesty** [comment]
@kellychoe I think you meant to upload a pdf to this issue, but it did not work https://github.com/hackforla/internship/issues/68#issuecomment-998786694

Please put it in the[ branding folder](https://drive.google.com/drive/folders/1NeYnJpEEd9IjBJXt7B53vk9q6b6QLFNK?usp=sharing) in the google drive

**Comment by ExperimentsInHonesty** [comment]
![IMG-3513](https://user-images.githubusercontent.com/37763229/147279937-7322ce37-6ecb-44e7-8e83-47abeb2ba741.jpg)

**Comment by ExperimentsInHonesty** [comment]
@kellychoe 

Can you provide some examples of how other companies have written their "Personality" page of a brand guide?

> @ExperimentsInHonesty - I was hoping for a short paragraphic of how sesame street inspired us or the similar personality trades that the internship shares with sesame street. The above describes Sesamesteet, we need a few sentences to describe our connection and similar personality/Character trade with sesame street. this is currently what we have...

**Comment by ExperimentsInHonesty** [comment]
Hi @kellychoe, Any luck coming up with examples for us?

Can you provide some examples of how other companies have written their "Personality" page of a brand guide?

@ExperimentsInHonesty - I was hoping for a short paragraphic of how sesame street inspired us or the similar personality trades that the internship shares with sesame street. The above describes Sesamesteet, we need a few sentences to describe our connection and similar personality/Character trade with sesame street. this is currently what we have...

**Comment by Rabia2219** [comment]
Kelly has the following for us regarding the brand personality example:
[Brand Personality: Traits of Top Brands](https://www.ebaqdesign.com/blog/brand-personality#2)
[Jamie Oliver Brand](https://drive.google.com/file/d/1j04PqS2s8mAGfOuAGUcsrUapfgoMhP34/view?usp=sharing)
[Avaon Haute Brand](https://drive.google.com/file/d/1wIgt2KwrmB5SntfbuEjapSvtHxOS11pt/view?usp=sharing)
[Bandit Coffee Brand](https://drive.google.com/file/d/1pe8sYUHzeHVEmJgDVLvsYc-pSaDjwObU/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
<details>
<Summary>Nike</summary>

<img src="https://uploads-ssl.webflow.com/5de2db6d3719a1e2f3e4454c/5de41ea95f17622f593c027d_Nike-Brand-Personality.png" />
</details>

**Comment by ExperimentsInHonesty** [comment]
Personality notes from our Inspiration
BigBird: kind, curious, uses his words, inclusive/friendly/welcoming, supportive/encouraging
Adults: there to help the journey
"Everyone makes mistakes, so why can't you?"
"If you keep practicing, you can do anything.”

Nike Style

<details>
<summary>Drafts</summary>

- Bonnie: [Name of Brand] has an inclusive, supportive, inspirational and can-do personality.
- Priyanka: [Name of Brand] has a welcoming, supportive, kind, friendly, forgiving and curious personality.
- Rabia: [Name of Brand] has an inclusive environment, supportive, welcoming, patient personality.
</details?

All: [Name of Brand] has an inclusive, supportive, welcoming, experimental, forgiving, can-do personality.

**Comment by ExperimentsInHonesty** [comment]
Personality notes from our Inspiration
BigBird: kind, curious, uses his words, inclusive/friendly/welcoming, supportive/encouraging
Adults: there to help the journey
"Everyone makes mistakes, so why can't you?"
"If you keep practicing, you can do anything.”

Avon Style
How do write content on the website and marketing materials?
How does the voice sound?
- Tone (jokes/casual but not stodgy)
- Technical (results oriented explanations over technical jargon but be technical when you need to)
- Industry standard language while being grounded (to prove you know what you are talking about without loosing your audience or showing off when an ordinary word will do)
- empowerment
- contractions?

**Comment by ExperimentsInHonesty** [comment]
Tone is factual
provide examples wherever possible
soft skills advice giving throughout
opportunities for self evaluation
Conversational
methodical and informative
nonjudgmental
succinct
respectful no matter how little experience the audience has
responsible

**Comment by ExperimentsInHonesty** [comment]
@kellychoe we have been working on the personality.  All our notes are above. We can review with you on Thursday when we meet.

**Comment by kellychoe** [comment]
Amazing!  :)

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
Progress: Met with Susan to compile notes from all team meeting and figure out next steps
Blockers: None
Availability: plenty
ETA: Hopefully in the next week.

**Comment by Rabia2219** [comment]
@kellychoe @Susanz7 @seetho-c 

This is some of the material you can test the logo on. Please make sure you make a copy to work on and save all the work on the Internship drive. Thanks

- [IS22: Slides for AMA](https://docs.google.com/presentation/d/1Uy3c1ZbWbytllA1KqL4pu3LI5ma8IDxwLQSjRe3h0g0/edit#slide=id.gea24f90547_0_3)
- [Internship FAQ Summer 2022](https://docs.google.com/document/d/1TpacAma_vmAZ4MGq_VAQme22BsgKm1DW5rFBhYgm6vM/edit#heading=h.o31w6jmip2eh)
- [Summer Internship Check-In](https://docs.google.com/forms/d/1dLnvtsApjcWHgcvzjNoBAy_5LJSZ8YJpfJNV4NkeFIM/edit)

**Comment by ExperimentsInHonesty** [comment]
we have moved all this info to the wiki https://github.com/hackforla/internship/wiki/Internship-Brand-Book
