### ISSUE TITLE
Review usecases for the project

### ISSUE THREAD

**Issue by seenaiype** [hackforla/internship#97]
### Overview
To review the figma for use cases for people looking for internship opportunities, this would help us find the target markets appropriately.

### Action Items

- [x] Review the Scenarios section in figma
- [x] Review with Team on any new use cases reviewed. 
- [ ] Create [document](https://docs.google.com/document/d/1B1ZQN4DOkNukcVQefCQpT9AfkUVaIDf1QQQVHf_gFQg/edit?usp=sharing) with all the scenarios using the Audience document as a example (you do not have to add any other info beside the scenarios to it)
- [ ] Identify issues that need to be created based on the use cases.  You don't have to make the issues, we will make them on another issue
   - [ ] Create Research Plan: Prospective Funders (philanthropy)
   - [ ] Create Research Plan: Prospective Funders (corporate opportunity)
   - [ ] Create Research Plan: Prospective Parents
   - [ ] Create Research Plan: Parents of Prior Interns
   - [ ] Create Research Plan: Future interns
  
### Resources/Instructions
[figma](https://www.figma.com/file/VgxjTXP3PJhzZxMeMURf2f/Branding-Exercise?node-id=0%3A1)
[Audience document from open community survey](https://docs.google.com/document/d/1qTqxgMRi7y7Qqt1LvSDoPXGQOYGzH49_KM4txghBMkQ/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@seenaiype Please provide an update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by seenaiype** [comment]
Reviewed the Figma. The scenarios looks great. Couple of small things:

1. For the educators - should it be educators who are interested in the STEM fields to make it a little more specific?

Couple of scenarios that could be added:
1. Students - Siblings or friends of students who want to explore internship together as a group
2. LAcity - to be involved with young people for solutions around social causes

**Comment by ExperimentsInHonesty** [comment]
@seenaiype The next step is for the information in the figjam to get copied to a google doc and add your senarios to it.  See this [Audience document from open community survey](https://docs.google.com/document/d/1qTqxgMRi7y7Qqt1LvSDoPXGQOYGzH49_KM4txghBMkQ/edit?usp=sharing) as an example of where we are going with this:

**Comment by ExperimentsInHonesty** [comment]
@seenaiype 
- Q1: For the educators - should it be educators who are interested in the STEM fields to make it a little more specific?
  - A1: Any educator.  For instance in the user story "As an English teacher I want to find something that will be a good extra activity for my students who are having trouble focusing on stories which will allow them to develop critical reading skills."

For now we will not be including this group
- Students - Siblings or friends of students who want to explore internship together as a group
   - Reasons:
      - Paid internships don't let you bring your friends, its just like getting any other job
      - We want them to get out of their comfort zone and start making relationships quickly in the new space so that they can learn how to find mentors and allies fast.
      - working with adults to get the experience of that.

We do need to include these group:
- Students - Home-school students and parents, who are interested in coding or STEM projects
- LAcity - to be involved with young people for solutions around social causes

**Comment by ExperimentsInHonesty** [comment]
@seenaiype I just realized that I already created a template doc for this.  Use this
https://docs.google.com/document/d/1B1ZQN4DOkNukcVQefCQpT9AfkUVaIDf1QQQVHf_gFQg/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
@seenaiype Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by seenaiype** [comment]
Updated the document with the scenarios - https://docs.google.com/document/d/1B1ZQN4DOkNukcVQefCQpT9AfkUVaIDf1QQQVHf_gFQg/edit#

**Comment by ExperimentsInHonesty** [comment]
@seenaiype Sorry for the delay, we will have feedback for you next week.  We had to reprioritize this week to respond to a stakeholder
